### ISSUE TITLE
Update closing Chrome

### ISSUE THREAD

**Issue by Stanzilla** [ShareX/ShareX#692] opened 2015-05-17 02:09 UTC
So I just found out that changing your InnoSetup to not run as `/silent` as you currently do, will cause a prompt to appear that asks the user if he really wants to close the programs that have a handle on your files, which is in my opinion, a better way to go at it.

See: http://www.jrsoftware.org/ishelp/index.php?topic=setup_closeapplications

Also you can restart the applications that had to be closed with http://www.jrsoftware.org/ishelp/topic_setup_restartapplications.htm

**Comment by Stanzilla** [comment] 2015-05-17 02:17
If you don't want to go completely without /silent, one could test if setting RestartApplications to "yes" just brings up that one popup dialog or is ignored when /silent is on.

Anyway, adding RestartApplications might be good to have.

**Comment by Nathan-Lane** [comment] 2015-05-17 02:35
Yeah my Chrone randomly closed too, completely cut off my music and then messed up my Spotify playlist as it always does when chrome is restarted.

**Comment by Stanzilla** [comment] 2015-05-17 02:54
We discussed this on IRC and the problem is that the same installer is used for update and initial installation which makes it impossible to hide the Wizard pages because the user *has* to see that for the first time install.

**Comment by Jaex** [comment] 2015-05-17 03:54
Disabling silent is not a solution. Because people lazy to update and even now keep telling updating is long process when it is fully automated with single click. So I'm trying to make it fast and silent as possible.

Disabling auto closing solving this problem and creating another problem:

![](http://i.imgur.com/2MqTilB.png)

It not tells that Chrome using this dll so people can't figure out why it is in use and what to close so they will keep opening issues. More issues than current Chrome issues. So while fixing this problem it will create another big problem.

So I can't find proper solution to it therefore why it is not fixed yet.

And actually this problem kinda to do with Chrome too because Firefox and IE don't use this dll when it is not required, why Chrome doing this I don't even know.

**Comment by 3ventic** [comment] 2015-05-17 13:04
Some people being too lazy to click 3 more times during an update is a bad reason to cause some other people to lose unsaved information because the installer didn't say it would close some programs.

**Comment by Jaex** [comment] 2015-05-18 06:44
You losing unsaved info because Chrome using dll when it is not need to. Also InnoSetup don't have option to show that Chrome using this dll warning in silent mode. So I don't want updater to have unnecessary next, next etc. dialogs when it is currently doing everything automatically and quickly. It is not about clicking 3 times it makes updating take like 1 second and without even see installing new ShareX opening automatically so it becomes very easy to update.

You not giving solution either. Am I don't know it is very bad to close applications without tell? How am I supposed to fix it then? Easy to tell about these.

**Comment by 3ventic** [comment] 2015-05-18 10:18
Silent mode is pointless. *Without* silent mode, we get the useful prompt that something needs closing before the updating can continue. *With* silent mode *all we have is unnecessary next, next, next!* Might as well use /VERYSILENT to make it not appear at all! Yay, lazy people win and *have no idea which programs were closed in the process.*

The problem is not that it closes Chrome specifically. The problem is that it's closing programs without warning me about it. I don't want it to close some important background program I have running without being told about it in advance.

As it stands, I consider it malicious and won't be installing the updates for as long as the old version keeps working.

**Comment by Jaex** [comment] 2015-05-18 10:20
If you consider it malicious then don't use old version too.

**Comment by Jaex** [comment] 2015-05-24 20:42
I really want to fix this issue and keep doing hours of searching but unable to find solution. I'm very limited with this InnoSetup related issue. Even if I make it not use silent then it will still show that dll in use warning for everybody and people will keep opening issues asking why setup want me to close Chrome, so even then it is not solution. Only solution would be Chrome to not use this dll when it is not needed to. Or for InnoSetup workaround, ignoring this dll registration if it is in use and continue installing which I can't manage to do.

**Comment by Nathan-Lane** [comment] 2015-05-24 20:48
I believe just an alert at the start of the setup saying "Some programs may need to be closed during this setup process, it is advised that you save all your work." would suffice.

**Comment by 3ventic** [comment] 2015-05-24 20:50
How about adding a check box for "Quick install", which would be ticked by default, to the "Do you want to download and install the update now?" prompt, which would either add the /SILENT or leave it out?

**Comment by Stanzilla** [comment] 2015-05-24 23:57
I made tickets at both Chromium [1] and screen-capture-recorder that ShareX is using for this feature, so you can follow those for additional info if something gets found.

[1] https://code.google.com/p/chromium/issues/detail?id=488964
[2] https://github.com/rdp/screen-capture-recorder-to-video-windows-free/issues/58

**Comment by Jaex** [comment] 2015-06-21 23:27
Only solution I have is making separate setup file for these dlls and adding setup button to FFmpeg options window that way auto update won't try to install these automatically but manually people can install them. Still people needed to go FFmpeg options and select these new sources anyway so it won't make big difference I guess.

**Closed** 2015-06-22 01:26 UTC
Labels: Cannot fix
