### ISSUE TITLE
Mouse is little off in Video Capture

### ISSUE THREAD

**Issue by ArunEdathadan** [ShareX/ShareX#3457] opened 2018-06-20 11:11 UTC
The mouse should be on top of Milestone, it is giving me confusion

![chrome_2018-06-20_16-40-47](https://user-images.githubusercontent.com/16814342/41654960-b94787ca-74a8-11e8-9ae1-4c0ffd9a5a9c.png)

**Comment by Jaex** [comment] 2018-06-20 11:12
Duplicate of #1329

**Closed by Jaex** 2018-06-20 11:12 UTC
