### ISSUE TITLE
Multi region resize elements are too bulky

### ISSUE THREAD

**Issue by Artinaix** [ShareX/ShareX#3461] opened 2018-06-21 18:08 UTC
The resizing elements when in multi region mode are too big and bulky, they are usually fine when the region you want is big
![sharex 06-21-2018 13h54m](https://user-images.githubusercontent.com/29335214/41737065-31969e60-755c-11e8-82e8-c8e33a7b5f10.png)
but when the area gets too small, the top or bottom circles just disappear and make you unable to resize in the direction you want.
![sharex 06-21-2018 13h55m](https://user-images.githubusercontent.com/29335214/41737119-53f7925c-755c-11e8-81c2-cca847404211.png)

After looking through the options it doesn't appear to have an option to change this.
There should be an option for you to change how it looks, like the old way with smaller squares that don't disappear when an area is too small for them to fit.

**Comment by Jaex** [comment] 2018-07-05 09:07
Duplicate of #2955

**Closed by Jaex** 2018-07-05 09:07 UTC
