### ISSUE TITLE
ShareX won't open

### ISSUE THREAD

**Issue by Beeb17** [ShareX/ShareX#4160] opened 2019-06-06 16:49 UTC
ShareX hasn't let me upload any screenshots for a while, so I finally just got around to downloading the latest version to see if that would work. Now ShareX won't even open... I keep getting this screen: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at ShareX.SettingManager.ApplicationConfigBackwardCompatibilityTasks()
   at ShareX.SettingManager.LoadApplicationConfig()
   at ShareX.SettingManager.LoadInitialSettings()
   at ShareX.Program.Run()
   at ShareX.Program.Main(String[] args)

ShareX 12.4.1 (Release)

And when I click "Continue", it says "ShareX has stopped working" and the program closes.

**Comment by fluoroom** [comment] 2019-06-07 06:12
same here, it doesn't stop working but it never opens after clicking continue

**Comment by Jaex** [comment] 2019-06-07 09:07
Duplicate of #3976

**Closed by Jaex** 2019-06-07 09:07 UTC
