### ISSUE TITLE
Wrong mouse cursor position when screen recording (region) with display scale set to 150%

### ISSUE THREAD

**Issue by pharanbrush** [ShareX/ShareX#6520] opened 2022-09-25 14:15 UTC
Using Windows 10.
I tried to screen record on desktop with Windows display scale set to 150% and the cursor enabled.

The cursor position in the video comes out way off so it looks like I'm not clicking on the thing I'm clicking.

I assumed it had something to do with the resolution not being correctly applied without restarting so I restarted first before recording again.

Same result.

Is there a workaround for this? Or is this just an unsupported thing for now?

**Comment by Jaex** [comment] 2022-09-25 22:18
Duplicate of #1329

**Closed by Jaex** 2022-09-25 22:18 UTC
