### ISSUE TITLE
System tray icon darkens as main display is switched

### ISSUE THREAD

**Issue by xDownSetx** [ShareX/ShareX#6254] opened 2022-05-12 09:40 UTC
I have noticed an issue with the System tray icon that causes it to slowly dim each time the main display is switched between two connected monitors. This is cumulative and will eventually lead to the tray icon turning completely black. I noticed this while using a KVM to switch between my work and home computer. The work and home computer share one monitor, but the home computer has a second display that becomes the primary when the KVM is switched. See the progression below.

![1](https://user-images.githubusercontent.com/46777197/168039405-018cfaba-e2b3-4fc9-8fa3-b2c64504b2d0.png)
![2](https://user-images.githubusercontent.com/46777197/168039406-fcfc73d9-e08e-4b73-975b-8c86062b74ea.png)
![3](https://user-images.githubusercontent.com/46777197/168039402-5da64aaf-7afe-4aa0-8cd9-0e243dd0401e.png)

To verify whether it is linked to the main display switching, instead of using the KVM, I opened Display settings and checked the "Make this my main display" box between two monitors and it had the same effect.

OS: Windows 10 21H2 Build 19044.1706, latest updates installed
ShareX version: 13.7.0

**Comment by xDownSetx** [comment] 2022-05-12 15:43
This appears to be related to DPI scaling. When I set both displays to 100%, there is no change in the tray icon. With scaling applied to one display I can reproduce the issue.

**Comment by Jaex** [comment] 2022-05-13 23:45
Duplicate of #6172

**Closed by Jaex** 2022-05-13 23:45 UTC
