### ISSUE TITLE
Can I take a screenshot and pin it to the top of the desktop?

### ISSUE THREAD

**Issue by honkerjha** [ShareX/ShareX#5760] opened 2021-08-13 03:25 UTC
Can I take a screenshot and pin it to the top of the desktop?

**Comment by Jaex** [comment] 2021-08-13 03:37
Duplicate of #2363

**Closed by Jaex** 2021-08-13 03:37 UTC

**Comment by zhupengfeivip** [comment] 2021-11-15 13:14
This is a great feature. When will it be available?
