### ISSUE TITLE
Colors dull and faded on capture

### ISSUE THREAD

**Issue by Cyph3r** [ShareX/ShareX#3859] opened 2018-12-31 01:25 UTC
Attached is an image showing colors dull and faded from ShareX capture. The right side is region capture with ShareX. Then placed next to the original, then captured them both side by side with built in Windows capture. The left looks like the original - the colors are vibrant. The right is faded, like the color saturation has been turned down considerably. The result is the same whether or not the clipboard is uploaded to imgur or just used locally without any upload, so imgur is not the issue.

Thanks!

![colorssharex](https://user-images.githubusercontent.com/593648/50553225-28135b00-0c68-11e9-9ad5-25e1b06c1a78.png)

**Comment by Jaex** [comment] 2019-02-24 07:46
Duplicate of #3734, #1236

**Closed by Jaex** 2019-02-24 07:46 UTC
Labels: Duplicate
