### ISSUE TITLE
thumbnail view is not scrolled by mouse wheel

### ISSUE THREAD

**Issue by finejustice** [ShareX/ShareX#4399] opened 2019-09-29 08:01 UTC
1.3.0 made "thumbnail view" as default. 
It looks great, but it has a small problem. I cannot scroll it with mouse wheel. 
scrolling with ScrollBar have no problem.

I suspect its scroll orientation is mis-configured: it might be configured to scroll horizontally, which is natural orientation at list mode.

**Comment by Scrxtchy** [comment] 2019-09-29 17:22
I don't have this issue

**Comment by Jaex** [comment] 2019-09-29 18:05
This issue not exists in Windows 10. I added workaround for it already.

**Comment by Jaex** [comment] 2019-09-29 18:06
Duplicate of #4306

**Closed by Jaex** 2019-09-29 18:05 UTC
