### ISSUE TITLE
Feature Request: Update to .NET Framework 4.7.x and add HiDPI Support

### ISSUE THREAD

**Issue by AluminiumTech** [ShareX/ShareX#3103] opened 2018-01-28 20:01 UTC
Hi, 
I'd like to suggest that ShareX start targeting .NET Framework 4.7 instead of 4.0 so that it can support HiDPI devices such as modern ultrabooks etc.

The current GUI scaling on low DPI devices looks fine but on HiDPI devices it's not good looking due to the lack of optimization.

.NET Framework 4.7 added ways to make HiDPI Windows Forms Support a lot easier through the configuration of the Project files. 

There are some changes that will have to be made to accommodate this change. ShareX would need to stop supporting Windows XP even though Microsoft hasn't supported it since 2014 and ShareX would need to stop supporting Windows Vista even though Microsoft hasn't supported it since April 2017.

Also, I'd like to suggest that ShareX set the "Prefer 32 Bit" property from true to false so that by default ShareX can run as a 64 Bit app instead.

I would submit a PR for this but I'm somewhat busy right now.
Thanks.

**Comment by Jaex** [comment] 2018-01-28 20:05
Duplicate of #1477

**Closed** 2018-01-28 20:05 UTC
Labels: Duplicate
