### ISSUE TITLE
"Removed Greenshot image editor"

### ISSUE THREAD

**Issue by SnIPeRSnIPeR** [ShareX/ShareX#3226] opened 2018-03-23 16:53 UTC
Why you removed very usable Greenshot image editor from new version? I am using this very long time and LOVE it so much. Your image redactor is uncomfortable compare to GREENSHOT. WHY? How can I return it??

**Comment by jacksonisiah** [comment] 2018-03-23 17:48
Duplicate of #3220

**Comment by trollmad3** [comment] 2018-03-23 22:00
Greenshot image editor is litterally garbage. If you love it that much you can download it [here.](http://getgreenshot.org/)

**Closed** 2018-03-24 00:33 UTC
Labels: Duplicate

**Comment by SnIPeRSnIPeR** [comment] 2018-03-24 13:51
You ruined your app.

**Comment by trollmad3** [comment] 2018-03-24 21:19
@SnIPeRSnIPeR How? The app is litterally **perfect** without greenshhot. Infact Greenshot made sharex worse of how buggy it is.
