### ISSUE TITLE
missing Arial font causes ShareX to fail with an exception (Windows 7)

### ISSUE THREAD

**Issue by erictrue** [ShareX/ShareX#3294] opened 2018-04-08 23:45 UTC
Occasionally, the Arial Regular font disappears from my Windows 7 machine (apparently removed by a faulty uninstaller for some other application). Some apps handle this case by falling back to Arial Italic -- I don't know how the fallback on a particular system is determined.

I doubt this is a common issue, and it has a simple workaround (copy arial.ttf to the fonts directory again), but it seemed worth reporting.

    ShareX 11.1 (Release)
    2018-04-08 15:34:18.758 - ShareX closing. Reason: Unhandled exception
    2018-04-08 15:45:15.403 - ShareX 11.1
    2018-04-08 15:45:15.490 - Build: Release
    2018-04-08 15:45:15.532 - Personal path: C:\Users\Eric\Documents\ShareX
    2018-04-08 15:45:15.575 - Command line: "C:\Program Files\ShareX\ShareX.exe" 
    2018-04-08 15:45:15.617 - Operating system: Windows 7 Home Premium
    2018-04-08 15:45:15.693 - ApplicationConfig load started: C:\Users\Eric\Documents\ShareX\ApplicationConfig.json
    2018-04-08 15:45:16.063 - ApplicationConfig load finished: C:\Users\Eric\Documents\ShareX\ApplicationConfig.json
    2018-04-08 15:45:16.101 - UploadersConfig load started: C:\Users\Eric\Documents\ShareX\UploadersConfig.json
    2018-04-08 15:45:16.152 - MainForm init started
    2018-04-08 15:45:16.212 - Unhandled exception:
    System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentException: Font 'Arial' does not support style 'Regular'.
       at System.Drawing.Font.CreateNativeFont()
       at System.Drawing.Font.Initialize(FontFamily family, Single emSize, FontStyle style, GraphicsUnit unit, Byte gdiCharSet, Boolean gdiVerticalFont)
       at System.Drawing.Font..ctor(SerializationInfo info, StreamingContext context)
       --- End of inner exception stack trace ---
       at System.RuntimeMethodHandle.SerializationInvoke(IRuntimeMethodInfo method, Object target, SerializationInfo info, StreamingContext& context)
       at System.Runtime.Serialization.ObjectManager.CompleteISerializableObject(Object obj, SerializationInfo info, StreamingContext context)
       at System.Runtime.Serialization.ObjectManager.FixupSpecialObject(ObjectHolder holder)
       at System.Runtime.Serialization.ObjectManager.DoFixups()
       at System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(HeaderHandler handler, __BinaryParser serParser, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
       at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, HeaderHandler handler, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
       at System.Resources.ResourceReader.DeserializeObject(Int32 typeIndex)
       at System.Resources.ResourceReader.LoadObjectV2(Int32 pos, ResourceTypeCode& typeCode)
       at System.Resources.ResourceReader.LoadObject(Int32 pos)
       at System.Resources.ResourceReader.ResourceEnumerator.get_Entry()
       at System.Resources.ResourceReader.ResourceEnumerator.get_Current()
       at System.ComponentModel.ComponentResourceManager.FillResources(CultureInfo culture, ResourceSet& resourceSet)
       at System.ComponentModel.ComponentResourceManager.FillResources(CultureInfo culture, ResourceSet& resourceSet)
       at System.ComponentModel.ComponentResourceManager.FillResources(CultureInfo culture, ResourceSet& resourceSet)
       at System.ComponentModel.ComponentResourceManager.ApplyResources(Object value, String objectName, CultureInfo culture)
       at ShareX.HelpersLib.MyPictureBox.InitializeComponent()
       at ShareX.HelpersLib.MyPictureBox..ctor()
       at ShareX.MainForm.InitializeComponent()
       at ShareX.MainForm.InitializeControls()
       at ShareX.Program.Run()
       at ShareX.Program.Main(String[] args)

**Comment by sylveon** [comment] 2018-04-08 23:46
Would you mind upgrading to the latest version and see if it can reproduce?

**Comment by Jaex** [comment] 2018-04-08 23:47
Duplicate of #374

**Closed** 2018-04-08 23:47 UTC
Labels: Duplicate
