### ISSUE TITLE
Allow feature sets to be disabled/plug-in based

### ISSUE THREAD

**Issue by mrandreastoth** [ShareX/ShareX#3512] opened 2018-07-08 12:35 UTC
Yes, I know it's called ShareX but I never ever use ShareX for anything other than as a capture tool. In fact, I originally purchased SnagIt back in the days when all it was was a powerful capturing utility. However, since then Techsmith have bloated Snagit (and Camtasia) with library, editing, and sharing features; while all professional users like me want is a powerful capturing tool that does one thing extremely well: captures.

I've given up hope for Snagit and am now hoping ShareX is the future. However, I wish I could disable ShareX feature sets that I am not interested in, in my case that being uploading. After all, all that these unwanted extras do for a user like me is to clutter the interface and makes the features that I actually need difficult to get to,

A better solution would be if, instead of settings to disable feature sets, ShareX instead supported a plug-in architecture that allowed it to be extended. If that was the case then the core ShareX could deal with providing capturing services and then plug-ins could be independently developed and maintained to provide extra functionality such as library, editing, and sharing, in a way like web-browsers can be extended. There are many benefits to such a decoupled architecture not only to end-users but to development including third-party developers.

**Comment by Jaex** [comment] 2018-07-08 13:07
Duplicate of #1024

**Closed by Jaex** 2018-07-08 13:07 UTC
