### ISSUE TITLE
Bug in the button palette when I resize or put everything to one side.

### ISSUE THREAD

**Issue by luapfr** [ShareX/ShareX#7480] opened 2024-05-30 12:42 UTC
Bug in the button palette when I resize or place everything to one side of the screen to the left or right, I noticed this problem in the last version.

See this image

![toolbar](https://github.com/ShareX/ShareX/assets/50739062/070a621d-27c4-4fbe-b7d7-05f81eea2acb)

**Comment by Jaex** [comment] 2024-06-03 07:05
Duplicate of #7422

**Closed by Jaex** 2024-06-03 07:05 UTC
Labels: Duplicate
