### ISSUE TITLE
Save Destinations Configurations

### ISSUE THREAD

**Issue by darwin4ever** [ShareX/ShareX#3450] opened 2018-06-16 14:46 UTC
I'm using ShareX 12.0 Portable

Seems there is a problem with the Destination Configuration.

After having configured the Tinipic Destination login credentials, login is working, but the credentials are NOT memorized, so they must be entered every time.

When going back into Destinations / Destination Settings / TinyPic the credentials are empty !

**Comment by Jaex** [comment] 2018-06-17 10:39
Duplicate of #3186

**Closed by Jaex** 2018-06-17 10:39 UTC
