### ISSUE TITLE
Error Message since latest update

### ISSUE THREAD

**Issue by Speiger** [ShareX/ShareX#4679] opened 2020-03-15 14:39 UTC
![ShareX_2020-03-15_15-36-22](https://user-images.githubusercontent.com/2556269/76703558-cd321c00-66d2-11ea-99a8-f8f1e42d1ed7.png)

I am just taking a normal screencapture with share X and then the picture shows up in my screenshot folder but the actual "ding" sound and the highlight won't show up until i remove this message. 
And if I enable upload then it uploads it to imigur which i dont want.

![ShareX_2020-03-15_15-38-30](https://user-images.githubusercontent.com/2556269/76703599-0bc7d680-66d3-11ea-8dcb-49ff3b611980.png)

This is my settings and I am using Ctrl + Print.

How can I disable this issue popup because its getting annoying really quickly

Thanks for reading

Edit: My settings
![ShareX_2020-03-15_15-40-15](https://user-images.githubusercontent.com/2556269/76703659-521d3580-66d3-11ea-935e-353ebb6ea376.png)

**Comment by Jaex** [comment] 2020-03-15 15:01
Duplicate of #4652

**Closed by Jaex** 2020-03-15 15:01 UTC

**Comment by Speiger** [comment] 2020-03-15 15:40
@Jaex nope that setting was disabled for me. And after enableing and then disabling it it still does it.
