### ISSUE TITLE
[Image Editor] Cropping image cant be undone.

### ISSUE THREAD

**Issue by JABirchall** [ShareX/ShareX#7129] opened 2023-11-05 00:56 UTC
Recently editing an image in the image edit and cropped it a bit too small. 

Tried everything and nothing can undo a crop. Instead everything else i did was undone, but the crop remained.

Reproduction steps

1. Take screenshot
2. Open in image editor
3. Edit the image
4. Crop the image
5. Undo
6. Observe step 3 being undone and the crop staying.

**Comment by Jaex** [comment] 2023-12-27 05:35
Duplicate of #4079

**Closed by Jaex** 2023-12-27 05:35 UTC
