### ISSUE TITLE
Mouse pointer doesn't show on higher zoom in scale in windows display settings with 300% or 350%.

### ISSUE THREAD

**Issue by Nuero** [ShareX/ShareX#4182] opened 2019-06-21 02:50 UTC
![5ixvs0IIp8](https://user-images.githubusercontent.com/26434335/59894057-c57a6b00-9411-11e9-9a9f-f66124ff84c5.gif)
When the capture started, there is no mouse pointer captured on GIF file, with 350% or 300% zoom in scale, on P52. Is it able to get mouse pointer captured on such a scale?
I tried on 100%, it works.

**Comment by Jaex** [comment] 2019-06-21 02:55
Duplicate of #1329

**Closed by Jaex** 2019-06-21 02:55 UTC
Labels: Duplicate
