### ISSUE TITLE
Delete at ftp

### ISSUE THREAD

**Issue by makkesk8** [ShareX/ShareX#1133] opened 2015-11-22 20:40 UTC
I recently discovered this amazing software and I just love it!

I feel though you should be able to delete screenshots / files etc from the client on the ftp.

Thanks.

**Comment by Jaex** [comment] 2015-11-22 20:42
Because of multiple destination support it will be very complicated to add generic delete support because each destination can require different infos like account info, file path, file id etc. Also other settings and paths can change in time and unintended files can delete.

**Comment by makkesk8** [comment] 2015-11-22 20:44
Well, how about a setting for each ftp and add an option to allow the user to delete files on this ftp via the contextmenu. Shouldn't really be complicated or run into any issues.

**Comment by Jaex** [comment] 2015-11-22 20:45
I need Dropbox file delete option other people can require Google Drive delete file etc. so many work.

**Comment by makkesk8** [comment] 2015-11-22 20:46
Well I'm not really talking about dropbox, google drive etc... Just ftp.

**Comment by Jaex** [comment] 2015-11-22 20:46
Well I'm using Dropbox :D

**Comment by makkesk8** [comment] 2015-11-22 20:51
Well think about it. FTP deletion is really easy and as you release more versions add support to dropbox, google drive one by one over a period of time?

**Comment by Scrxtchy** [comment] 2015-11-22 22:20
Duplicate of #92 #141

**Closed** 2015-11-22 22:22 UTC
Labels: Duplicate
