### ISSUE TITLE
MAJOR issues with losing work and keyboard annoyance

### ISSUE THREAD

**Issue by u12bdragon** [ShareX/ShareX#6792] opened 2023-03-04 18:25 UTC
There is a ctrl+z but not a ctrl+y keybind. Therefore it is possible to do minutes worth of work (eg, in a text box), then have it deleted forever when all you were trying to do was to undo a scaling of an image-from-file that was on the screen (which undo does not apply to for some reason). I have been affected by not being able to ctrl+y probably 10 times now over the course of 4 years of use

secondly, ctrl+backspace does not delete an entire word, like it should, rather it inserts a default box character into the text.

**Comment by u12bdragon** [comment] 2023-03-04 18:28
it's amazing that you have all these tools not only for taking screenshots, but for screenshot editing as well without opening a separate program, but it is criminal that the basic functionalities of these type of programs are not implemented.

I don't mean to be negative though, as this is genuinely the one of the best if not the best screenshot programs on any platform

**Comment by andaluspc** [comment] 2023-05-28 07:52
I'd add same comment here.
No only ctrl+y is missing. also, some actions like cut-out and crop can't be reversed with ctrl+z. It would be big achievement to add ctrl+y and to allow ctrl+z on all editing features including cut-out and crop. I think I am going to mention crop and cut-out in a separate issue.

**Comment by Jaex** [comment] 2023-12-27 05:40
Duplicate of #4079

**Closed by Jaex** 2023-12-27 05:40 UTC
