### ISSUE TITLE
Imgur upload failed

### ISSUE THREAD

**Issue by Joyce11111** [ShareX/ShareX#3361] opened 2018-04-30 02:40 UTC
Imgur upload failed: (400) These actions are forbidden.

Message:
The remote server returned an error: (400) Bad Request.

Request URL:
https://api.imgur.com/3/image

Response:
{"data":{"error":"These actions are forbidden."},"success":false,"status":400}

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)

**Comment by MAGICCC** [comment] 2018-04-30 03:35
dupe of https://github.com/ShareX/ShareX/issues/2962

**Closed** 2018-04-30 07:13 UTC
Labels: Duplicate
