### ISSUE TITLE
Error after uploading file to NextCloud. File is uploaded but share link is not retrieved. 

### ISSUE THREAD

**Issue by Dreegzer** [ShareX/ShareX#3420] opened 2018-05-20 21:03 UTC
This is the error I recieve after trying to share using NextCloud. The file is uploaded to the server, but ShareX does not get a share link. I can confirm by manually checking that the file is uploaded correctly.
```
Message:
The server committed a protocol violation. Section=ResponseHeader Detail=CR must be followed by LF

Request URL:
https://<domain>/remote.php/webdav/ShareX/ShareX_2018-05-20_22-56-16.png

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.GetResponse(HttpMethod method, String url, Stream data, String contentType, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies)
```

[These are my settings for uploading](https://i.imgur.com/dMFK7C4.png)

**Comment by Jaex** [comment] 2018-05-20 21:06
Duplicate of #2308

**Closed** 2018-05-20 21:07 UTC
Labels: Duplicate
