### ISSUE TITLE
Azure Storage uploader should have option to remove $root from URL when container name is $root

### ISSUE THREAD

**Issue by samwise800** [ShareX/ShareX#3144] opened 2018-02-14 00:26 UTC
I am trying to configure ShareX to upload to my Azure Storage service, that has a single root container, called $root (the standard name for the root container).

The purpose for this is so that files can be accessed directly from
`http://<name>.blob.core.windows.net/<filename>`  rather than
`http://<name>.blob.core.windows.net/<containername>/<filename>`

I have set up ShareX to upload to the $root folder, and it works, however the result URL returned is of the form
`http://<name>.blob.core.windows.net/$root/<filename>`

Could there be a checkbox added to the options that will, when the container name is $root, remove the extra part from the URL so that the returned URL is instead of the form
`http://<name>.blob.core.windows.net/<filename>`

Thanks

**Comment by Scrxtchy** [comment] 2018-03-12 01:16
This could be implemented alongside #2845

**Comment by Lego6245** [comment] 2018-06-05 13:37
This is also a duplicate of #2710

**Comment by Jaex** [comment] 2018-06-09 00:49
Fixed by #3436

**Closed by Jaex** 2018-06-09 00:49 UTC
Labels: Duplicate

**Comment by Jaex** [comment] 2018-06-21 12:30
@samwise800 I was doing testing and noticed that when upload path is used (for example: 2018/06) with $root then it fails because first part of upload path becomes container. And if I use $root in request url (like this: $root/2018/06) then it also fails. So there is no way to have upload path when using $root?
