### ISSUE TITLE
[Suggested Features] Paste the picture on the screen

### ISSUE THREAD

**Issue by qhq** [ShareX/ShareX#6497] opened 2022-09-09 08:19 UTC
Like Snipaste, you can paste the picture on the screen and move it freely after taking the screenshot

![QQ截图20220909162051](https://user-images.githubusercontent.com/3319385/189305581-fe51aa10-4504-4a30-ae8e-be9131aadb6f.png)

**Comment by Jaex** [comment] 2022-09-09 23:17
Duplicate of #2363

**Closed by Jaex** 2022-09-09 23:17 UTC
