### ISSUE TITLE
Feature request: zoom tool for small area

### ISSUE THREAD

**Issue by ooker777** [ShareX/ShareX#3709] opened 2018-11-05 14:56 UTC
Sometimes it is necessary to capture the whole screen, but the important information is small, so it is handful if we have a zoom tool for such scenario.
 
![](https://i.imgur.com/2mJXxxJ.png)

**Comment by Jaex** [comment] 2018-11-05 14:58
Duplicate of #2891

**Closed by Jaex** 2018-11-05 14:58 UTC
