### ISSUE TITLE
Imgur upload failed: (417) Internal expectation failed

### ISSUE THREAD

**Issue by Paleepower** [ShareX/ShareX#5660] opened 2021-06-26 00:43 UTC
ShareX was working completely fine and for some random reason i am now repeatedly getting this error, saw someone before posting here with same thing, almost identical logs as well but I am not trying to upload BMP image it is specifically set to PNG > JPG if too large. I have not ever changed this or any setting involved here.

Tried re-installing, resetting settings to default and then going back to imgur nothing has worked still gives same error.

```
Imgur upload failed: (417) Internal expectation failed

Error message:
The remote server returned an error: (417) Expectation Failed.

Request URL:
https://api.imgur.com/3/upload

Status code:
(417) Expectation Failed

Headers:
Connection: close
X-Post-Rate-Limit-Limit: 1250
X-Post-Rate-Limit-Remaining: 1237
X-Post-Rate-Limit-Reset: 2991
X-Ratelimit-Clientlimit: 12500
X-Ratelimit-Clientremaining: 12500
X-Ratelimit-Clientreset: 86400
X-Ratelimit-Userlimit: 500
X-Ratelimit-Userremaining: 500
X-Ratelimit-Userreset: 3600
Content-Length: 116
Content-Type: application/json; charset=utf-8
Date: Sat, 26 Jun 2021 00:32:27 GMT

Response text:
{"status":417,"success":false,"data":{"error":"Internal expectation failed","request":"/3/upload","method":"POST"}}


Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)
```

**Comment by Paleepower** [comment] 2021-06-26 00:44
Full log - https://pastebin.com/F0cDrw2P

**Comment by Jaex** [comment] 2021-06-26 00:50
It is issue in Imgur side and we don't know when they gonna fix it.

**Comment by Paleepower** [comment] 2021-06-26 01:07
great thank you

**Comment by Duckrinium** [comment] 2021-06-26 01:12
Duplicate of #5657

**Comment by Jaex** [comment] 2021-06-26 01:26
I sent ticket using this link https://help.imgur.com/hc/en-us/requests/new to make sure that Imgur engineers aware of the issue.

Currently they sent this link as auto reply to my ticket: https://imgur.com/gallery/BwVDKoi

I will report here when they give further response!

**Comment by DanielVALAT** [comment] 2021-06-26 02:54
Imgur is experiencing upload problemes
Regarding : https://status.imgur.com/

**Comment by Jaex** [comment] 2021-06-26 03:01
> Imgur is experiencing upload problems
> Regarding : https://status.imgur.com/

Thanks for letting us now.

**Comment by Jaex** [comment] 2021-06-26 04:22
Got response to the ticket:

> At this time we are unfortunately experiencing a partial outage affecting upload across all mobile platforms (desktop is not affected), our team is working hard to resolve this issue and I will be happy to alert you once we have a fix pushed to resolve this.
>
> In the meantime, any updates we have will be shared on our status page first: https://status.imgur.com/

**Comment by Jaex** [comment] 2021-06-26 05:59
Duplicate of #5657

**Closed by Jaex** 2021-06-26 05:59 UTC
Labels: Invalid

**Comment by ZnelArts** [comment] 2023-03-04 03:48
Is there an update on this issue, I am still experiencing this error

**Comment by DanielVALAT** [comment] 2023-03-29 14:45
> Is there an update on this issue, I am still experiencing this error

Hello :wave: 
This error occur when Imgur servers are unavailable.
I think it's a good idea too add a more explaining message when upload fail @Jaex ?

Regards
