### ISSUE TITLE
Video editing after Screenrecord with ffmpeg

### ISSUE THREAD

**Issue by dyfcom** [ShareX/ShareX#4789] opened 2020-05-03 13:37 UTC
Would to ask if it is possible to add a Video editing after the screen recording, like with the image editing.

The video editing don't need something like Sony Vegas, only a function where to cut the beginning or the ending of a video. And a build-in option for convert the file, like the video-converter

This would be great!

**Comment by Jaex** [comment] 2020-05-07 06:02
Duplicate of #2278

**Closed by Jaex** 2020-05-07 06:02 UTC
