### ISSUE TITLE
Dropbox destination folder name is URL-encoded

### ISSUE THREAD

**Issue by TomoyukiAota** [ShareX/ShareX#2810] opened 2017-10-01 15:49 UTC
**How to reproduce:**
1. Go to Destinations, and set file uploader as Dropbox.
2. Go to Destinations -> Destination settings... -> Dropbox -> Upload path:.
3. In Upload path: text box, write "A B". Note that there is a space between A and B.
4. Close Destination settings window.
5. Go to Upload -> Upload file..., and select any file.

Expected: The selected file is saved in ${Dropbox_root_folder}\A B
Actual: The selected file is saved in ${Dropbox_root_folder}\A%20B

***
**Note:**
When I URI-decode "A%20B", I get "A B".
(I used [here](https://meyerweb.com/eric/tools/dencoder/) to URL-decode.)
This issue is serious for non-English-alphabet language user (such as Japanese like me) because any non-English alphabets will be converted to unreadable percent-encoded style.
For example, "スクリーンショット", which is "screenshot" in English, will be "%E3%82%B9%E3%82%AF%E3%83%AA%E3%83%BC%E3%83%B3%E3%82%B7%E3%83%A7%E3%83%83%E3%83%88", which is totally unreadable.

**Comment by Jaex** [comment] 2017-10-01 17:48
Duplicate of #2731

**Closed** 2017-10-01 17:48 UTC
Labels: Duplicate

**Comment by TomoyukiAota** [comment] 2017-10-01 23:44
#2731 is closed. Why? Is this issue tracked?

**Comment by TomoyukiAota** [comment] 2017-10-01 23:47
Oh, fixed in 36c9faf but not released yet. I got it.
