### ISSUE TITLE
Color Picker give incorrect color

### ISSUE THREAD

**Issue by fabryss** [ShareX/ShareX#5998] opened 2021-12-23 16:55 UTC
When i use the color picker, it give me a different color!
![23 12 2021_17 53 47_REC](https://user-images.githubusercontent.com/12843943/147270569-98172011-3932-4772-b22e-6576bfdc9690.png)

Can any help me to solve the problem?

Computer: Windows 10

**Comment by Jaex** [comment] 2021-12-24 03:48
Duplicate of #1236

**Closed by Jaex** 2021-12-24 03:48 UTC
