### ISSUE TITLE
Error durring shutdown

### ISSUE THREAD

**Issue by dthieme704** [ShareX/ShareX#3738] opened 2018-11-13 16:45 UTC
When shutting down the machine or logging out an "Arithmetic operation resulted in an overflow" error occurs.
[ShareX Log.txt](https://github.com/ShareX/ShareX/files/2577171/ShareX.Log.txt)

**Comment by trollmad3** [comment] 2018-11-13 19:37
If a value overflows, an exception is thrown to prevent unexpected behavior of your program.

**Comment by Jaex** [comment] 2018-11-14 05:38
Related to #3668, sylveon gonna check it.

**Comment by cmbail** [comment] 2018-11-15 20:41
I'm getting this too, regularly. Since updating to the latest 12.3.
--
System.OverflowException: Arithmetic operation resulted in an overflow.
   at ShareX.MainForm.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

ShareX 12.3 (Release)

**Comment by sylveon** [comment] 2018-11-16 05:33
What operating system are you using, and is it 32 or 64 bits?

**Comment by dthieme704** [comment] 2018-11-16 11:02
It is happening on 2 different machines both are 64 bit, one is Windows 10 and the other is Windows 7. And just like the last post this only started happening after upgrading to the 12.3 release.

**Comment by Jumpy91** [comment] 2018-11-16 13:45
Same Problem here:

`System.OverflowException: Die arithmetische Operation hat einen Überlauf verursacht.
   bei ShareX.MainForm.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

ShareX 12.3 (Release)`

This happens every time I sign out, shutdown or restart the pc.

Some Shortfacts:
- Windows 10 1803 (Build 17134.407) 64bit
- ShareX 12.3 64bit
- 16GB RAM
- Intel Core i7-4700MQ
- Intel HD Graphics 4600
- NVIDIA Geforce GTX 770M
- No additional antivirus engine besides Windows Defender

If you Need further Information please dont hesitate to contact me.
Thanks for your awesome work!

**Comment by krab** [comment] 2018-11-16 17:55
Same issue on every user logout and PC reboot/shutdown. Windows 10 1809 64-bit.

**Comment by krab** [comment] 2018-11-16 18:30
> 
> 
> does the **ENTIRE** PC shutdown, when you close ShareX?

No. I mean this error/bug preventing windows from shutting down. Looks like: [https://i.imgur.com/QhhIrOd.png](https://i.imgur.com/QhhIrOd.png)

**Comment by rjCousineau** [comment] 2018-11-16 18:36
Same thing on Windows 7 when it shows 'There is programs waiting to close
before Shutdown"

**Comment by Truesh00ter** [comment] 2018-11-16 19:33
Same thing here on Windows 10 Enterprise and on Windows Server 2016 Version 1607 (OS Build 14393.2580), I can reproduce the bug by logging of or shutting down any of my machines.

Logs below are from logging in (booting ShareX on login/start), logging off error and pressing continue on the Windows Server 2016 machine.

`ShareX 12.3 (Release)
2018-11-16 20:29:01.624 - ShareX 12.3
2018-11-16 20:29:01.624 - Build: Release
2018-11-16 20:29:01.624 - Command line: "C:\Program Files\ShareX\ShareX.exe" -silent
2018-11-16 20:29:01.624 - Personal path: C:\Users\Administrator\Documents\ShareX
2018-11-16 20:29:01.624 - Operating system: Windows Server 2016 Datacenter
2018-11-16 20:29:01.624 - Flags: SilentRun
2018-11-16 20:29:01.717 - ApplicationConfig load started: C:\Users\Administrator\Documents\ShareX\ApplicationConfig.json
2018-11-16 20:29:02.311 - ApplicationConfig load finished: C:\Users\Administrator\Documents\ShareX\ApplicationConfig.json
2018-11-16 20:29:02.327 - MainForm init started.
2018-11-16 20:29:02.389 - UploadersConfig load started: C:\Users\Administrator\Documents\ShareX\UploadersConfig.json
2018-11-16 20:29:02.530 - UploadersConfig load finished: C:\Users\Administrator\Documents\ShareX\UploadersConfig.json
2018-11-16 20:29:02.530 - HotkeysConfig load started: C:\Users\Administrator\Documents\ShareX\HotkeysConfig.json
2018-11-16 20:29:02.577 - HotkeysConfig load finished: C:\Users\Administrator\Documents\ShareX\HotkeysConfig.json
2018-11-16 20:29:02.795 - MainForm init finished.
2018-11-16 20:29:02.952 - Startup time: 1405 ms
2018-11-16 20:29:02.952 - CommandLine: silent
2018-11-16 20:29:02.983 - Hotkey registered: Hotkey: Ctrl + Print Screen, Description: Capture region, Job: RectangleRegion
2018-11-16 20:29:02.983 - HotkeyManager started.
2018-11-16 20:29:02.999 - WatchFolderManager started.
2018-11-16 20:29:05.843 - Unhandled exception:
System.OverflowException: Arithmetic operation resulted in an overflow.
   at ShareX.MainForm.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

ShareX 12.3 (Release)`

**Comment by sylveon** [comment] 2018-11-16 19:34
Fixed by #3760, try downloading the dev build.

**Comment by Jaex** [comment] 2018-11-17 07:39
Can you guys try dev build to verify is issue fixed?

**Comment by Truesh00ter** [comment] 2018-11-17 10:15
@Jaex fixed on one of my Windows Server 2016 with the dev build.

**Closed** 2018-11-18 10:34 UTC
Labels: Bug, Cannot reproduce
