### ISSUE TITLE
Replay Feature

### ISSUE THREAD

**Issue by iMGDE** [ShareX/ShareX#4484] opened 2019-11-11 13:55 UTC
A replay feature like NVIDIA and AMD have it: it records all the time and if the user performs a command/shortcut the last X seconds/minutes get encoded and saved as Video. You probably know how it works, im too dumb to describe it

**Comment by canpolat** [comment] 2019-11-12 10:27
This sounds like a duplicate of #4479

**Closed** 2019-11-12 10:58 UTC
Labels: Duplicate
