### ISSUE TITLE
HDR in Windows 10 on GTX 970 looks pale and unusable

### ISSUE THREAD

**Issue by PredragBoksic** [ShareX/ShareX#4570] opened 2020-01-13 21:10 UTC
Screenshots appear pale and unusable in HDR 10 mode (that is used in combination with the good old LG Ultrawide monitor with good results).

**Comment by sylveon** [comment] 2020-01-13 21:13
Duplicate of #3751 and #4105

**Closed** 2020-01-14 06:35 UTC
Labels: Duplicate
