### ISSUE TITLE
GIF encoding 

### ISSUE THREAD

**Issue by W1T3C** [ShareX/ShareX#4420] opened 2019-10-10 08:28 UTC
System.NullReferenceException: Object reference not set to an instance of an object.
   at ShareX.HelpersLib.MyPictureBox.LoadImage(Image img)
   at ShareX.HelpersLib.ImageViewer.InitializeComponent()
   at ShareX.HelpersLib.ImageViewer..ctor(Image image)
   at ShareX.HelpersLib.ImageViewer.ShowImage(String filepath)
   at ShareX.TaskThumbnailPanel.PbThumbnail_MouseClick(Object sender, MouseEventArgs e)
   at System.Windows.Forms.Control.OnMouseClick(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

ShareX 13.0.1 (MicrosoftStore)

**Comment by Jaex** [comment] 2019-10-10 09:47
How do you reproduce this issue?

**Comment by W1T3C** [comment] 2019-10-10 10:19
Hello Jaex
Thanks for contact.

Lucky issue does not reproduce anymore.
ShareX restart helped.
Previously scenario RMB on ShareX icon on windows (10 ver 1904) system tray
> capture > screen recording GIF > Then I recorded ~15 sec chrome session
> end capturing by LMB on red recording icon on system tray > 5 sec of
waiting to get error that I share on github

greetings
PW

czw., 10 paź 2019 o 11:48 Jaex <notifications@github.com> napisał(a):

**Comment by Jaex** [comment] 2019-11-22 09:22
Duplicate of #4303

**Closed by Jaex** 2019-11-22 09:22 UTC
