### ISSUE TITLE
[Bug] MouseCursor Offset with HiDPI and UI Scaling

### ISSUE THREAD

**Issue by lasselauch** [ShareX/ShareX#4618] opened 2020-02-18 11:15 UTC
Hi there,

when creating *.gifs my cursor is invisible or has a huge offset. I guess it's related to UI Scaling. If I record on my other montior without scaling it works just fine.

Cheers,
Lasse

**Comment by Jaex** [comment] 2020-02-25 10:18
Duplicate of #1329

**Closed by Jaex** 2020-02-25 10:18 UTC
