### ISSUE TITLE
Images do not load in Google Photos

### ISSUE THREAD

**Issue by aprilman** [ShareX/ShareX#3936] opened 2019-02-05 15:55 UTC
When loading images on Google Photos, an error occurs:

Message:
Удаленный сервер возвратил ошибку: (400) Недопустимый запрос.

Request URL:
https://picasaweb.google.com/data/feed/api/user/default/albumid/default

Response:
The Picasa API is deprecated. See https://developers.google.com/picasa-web/ for more details and the migration guide.

Stack trace:
   в System.Net.HttpWebRequest.GetResponse()
   в ShareX.UploadersLib.Uploader.GetResponse(HttpMethod method, String url, Stream data, String contentType, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, Boolean allowNon2xxResponses)

**Comment by lucario** [comment] 2019-02-05 17:41
https://getsharex.com/docs/dev-builds

**Comment by Jaex** [comment] 2019-02-06 07:51
Duplicate of #3884

**Closed by Jaex** 2019-02-06 07:51 UTC
Labels: Duplicate
