### ISSUE TITLE
The remote server returned an error: (400) incorrect request

### ISSUE THREAD

**Issue by NystriX** [ShareX/ShareX#3528] opened 2018-07-13 00:19 UTC
Message:
השרת המרוחק החזיר שגיאה: (400) בקשה שגויה. [Translate- The remote server returned an error: (400) incorrect request]

Request URL:
https://api.imgur.com/3/image

Stack trace:
   ב-  System.Net.HttpWebRequest.GetResponse()
   ב-  ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)

**Comment by Jaex** [comment] 2018-07-13 00:20
Duplicate of #3526

**Closed by Jaex** 2018-07-13 00:20 UTC
Labels: Duplicate
