### ISSUE TITLE
Arithmetic operation resulted in an overflow

### ISSUE THREAD

**Issue by Patrick-Spiegel** [ShareX/ShareX#3770] opened 2018-11-19 10:15 UTC
2018-11-19 11:13:35.082 - Unhandled exception:
System.OverflowException: Arithmetic operation resulted in an overflow.
   at ShareX.MainForm.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

ShareX 12.3 (Release)
2018-11-19 11:14:10.019 - URL opened: https://github.com/ShareX/ShareX/issues?q=is%3Aissue

Additional Information:

Occurred when I tried to sign out from windows 10

**Comment by Patrick-Spiegel** [comment] 2018-11-19 10:16
Duplicate of #3738

**Comment by Jaex** [comment] 2018-11-19 10:16
Duplicate of #3738

**Closed** 2018-11-19 10:16 UTC
