### ISSUE TITLE
Bug: Huge memory leak (first time occurring), where to bug report/how to troubleshoot?

### ISSUE THREAD

**Issue by zejjnt** [ShareX/ShareX#7356] opened 2024-03-26 15:33 UTC
My work setup is two computers where I RDP in to one of them. A few hours ago programs started responding and I couldn't even use task manager. I got a dialog complaining that ShareX couldn't allocate more memory, so I killed Chrome (taskkill /F /IM chrome.exe) to free up some and got what I could out of ShareX in hopes of having something to post here.
![image](https://github.com/ShareX/ShareX/assets/20284369/0b81814e-84ad-42be-aaff-c24fa6370b46)

I was not doing anything at the time and ShareX shouldn't have been processing anything either.
In the attached log there is unfortunately (from what I can tell) nothing of use.
The incident happened around 15:30, information from Windows Event Viewer that could be of use is also attached.
[systemevent.txt](https://github.com/ShareX/ShareX/files/14760819/systemevent.txt)
[appevent.txt](https://github.com/ShareX/ShareX/files/14760835/appevent.txt)
[sharexlog.txt](https://github.com/ShareX/ShareX/files/14760893/sharexlog.txt)

The computer in question has 32 GB DDR5 4800 MHz and a page file of 8 GB. Free disk space is around 200 GB of a Samsung 990 Evo.

What can I give you in order to troubleshoot this further?

**Comment by Jaex** [comment] 2024-03-26 16:04
Duplicate of #7329

**Closed by Jaex** 2024-03-26 16:04 UTC
