### ISSUE TITLE
Cannot add img to imgur 400 error

### ISSUE THREAD

**Issue by gitalexhubuser** [ShareX/ShareX#2971] opened 2017-12-02 16:25 UTC
Imgur upload failed: (400) Forbidden

Message:
Удаленный сервер возвратил ошибку: (400) Недопустимый запрос.

Request URL:
https://api.imgur.com/3/image

Response:
{"data":{"error":{"code":403,"message":"Forbidden","type":"ImgurException","exception":[]},"request":"\/3\/image","method":"POST"},"success":false,"status":400}

Stack trace:
   в System.Net.HttpWebRequest.GetResponse()
   в ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)

**Comment by campbeb** [comment] 2017-12-02 16:41
Are you uploading as anonymous or using an account?
You can check in Destinations / Destination Settings / Imgur

I'm not having any problems uploading as anonymous

**Comment by Jaex** [comment] 2017-12-02 18:21
Duplicate of #2962

**Closed by Jaex** 2017-12-02 18:21 UTC

**Comment by gitalexhubuser** [comment] 2018-07-14 20:59
Nice.
This problem is totally **gone**. I`m shooting a short video _how to fix it_.
https://www.youtube.com/watch?v=yH8b9DzTySg
