### ISSUE TITLE
Plugin Support

### ISSUE THREAD

**Issue by LewisTehMinerz** [ShareX/ShareX#3681] opened 2018-10-20 17:54 UTC
I believe that ShareX should support plugins for a few reasons:

- It would allow people to add their own functionality without having to build ShareX from source
- It would be easy to install plugins to add functionality
- It would allow people to combine multiple features of ShareX into one button press
- It would be safe if there's a central repository (I made a mockup one, which is available at https://sharex.center)

A couple of the community members believe it would be a great idea. I know Jaex thinks it would be a bad idea due to security, but if there was a moderated repository for plugins then it would be a lot more safer.

Speaking of that, there are some issues:

- Malicious plugins
- Plugins that state that they do one thing but actually do something else
- Conflicting plugins (which might crash ShareX)
- etc.

But again, a moderated repository would help out with the first two, and the third could be fixed using a dedicated plugin manager that can detect what plugins you installed recently and give suggestions on what to disable.

Very much a similar request to #1024, but that points more to actually implementing it rather than giving issues and solutions. I would actually write the system as a demonstration of what it could look like, but I can't get ShareX to compile on my system.

**Comment by iamluca** [comment] 2018-10-21 04:50
@LewisTehMinerz Make an approval system.

**Comment by LewisTehMinerz** [comment] 2018-10-21 08:34
What I was planning to do.

________________________________

**Comment by stuntguy3000** [comment] 2018-10-21 10:44
What type of functionality do you see plugins giving to ShareX?

**Comment by LewisTehMinerz** [comment] 2018-10-21 11:19
Effects, capture methods, uploaders (sounds useless because of ShareX's built in custom uploaders, but it might be easier to just add them as a built in option instead of trying to get endpoints, return URLs, etc.), after x tasks, workflows, I think you get the point.

**Comment by LewisTehMinerz** [comment] 2018-10-21 11:28
I can give an example of a tool.

Jaex developed a network monitor tool for testing when his wi-fi connection dropped out and came back (I think, correct me on that if I'm wrong) and he wanted to implement it into ShareX, but he said it would be bloat. It would be useful as a plugin in the case you wanted to monitor your network connection but it shouldn't be baked into ShareX since it's completely unnecessary and very few people may use it.

**Comment by stuntguy3000** [comment] 2018-10-21 11:31
ShareX is made for screen capture, not for network monitoring. I also think
some of the "tools" already available are totally bloat and should not
exist, but hey that's just my opinion.

>

**Comment by LewisTehMinerz** [comment] 2018-10-21 11:31
So why not move all the tools into plugins?

**Comment by stuntguy3000** [comment] 2018-10-21 11:33
I don't think they should belong at all in any capacity.

Plugins should *somehow* enhance the capabilities of the core functionality
of ShareX - screen capture - not assist with changing DNS settings or
monitoring networks.

**Comment by LewisTehMinerz** [comment] 2018-10-21 11:35
Just remember, ShareX is a screen capture, file sharing, and productivity tool. Tools to have a place in ShareX, it's just that most people use it for the screen capture portion. This is why plugins should be added - if people don't want parts of ShareX, they can just disable them.

**Comment by Jaex** [comment] 2018-11-03 09:43
Duplicate of #1024

**Closed by Jaex** 2018-11-03 09:43 UTC
