### ISSUE TITLE
[Feature request] Step tool : ability to choose the number

### ISSUE THREAD

**Issue by matheod** [ShareX/ShareX#3784] opened 2018-11-25 12:17 UTC
Hi,

Issue #2187 is closed so I make this new one.

Is it possible to get the ability to choose the step starting number ?

It would be really usefull to create multiple image tutorial.

Thanks.

**Comment by Jaex** [comment] 2018-11-25 17:55
It is already added:

![](https://jaex.getsharex.com/2018/11/8t2NUblmil.png)

**Comment by Jaex** [comment] 2018-11-25 17:56
Duplicate of #2187

**Closed by Jaex** 2018-11-25 17:56 UTC
Labels: Duplicate

**Comment by matheod** [comment] 2018-11-27 00:13
Oh thanks, I was clicking on the wrong icon (the icon just at the right of the good icon). Thanks a lot !
