### ISSUE TITLE
Region capture is broken when using touch screen

### ISSUE THREAD

**Issue by mghiasi75** [ShareX/ShareX#2820] opened 2017-10-05 17:16 UTC
When I tap the region capture in the context menu of the tray icon the app correctly enters the region capture mode. but then trying to choose a region is not working correctly.

**Expected behavior:** After entering region capture mode, user should be able to put his finger somewhere on screen. It should be treated as starting point. Then user can move theirs finger to some other point (while still touching the screen), and the point that user puts theirs finger away should be the end point. The region between the two points will be captured.

**Observed behavior:** The app treats the previous place that finger was (which is where the context menu item of region capture was) as the starting point. So when user puts theirs finger on the screen, starting point is already set; and by moving finger, end point is moving with it. So every region that user captures begins with the place of context menu item of region capture.

**Comment by Jaex** [comment] 2017-10-05 17:25
Duplicate of #2673

**Closed** 2017-10-05 17:25 UTC
Labels: Duplicate

**Comment by mghiasi75** [comment] 2017-10-05 17:38
Sorry for duplicate.
