### ISSUE TITLE
[BUG] Japanese OCR

### ISSUE THREAD

**Issue by JUN-PRODUCE** [ShareX/ShareX#6382] opened 2022-07-16 07:31 UTC
A half-width space will be inserted between the recognized characters when Japanese OCR is executed.

Recognized image
![Imgur Image](https://i.imgur.com/2EQU6zF.png)

Result
![Imgur Image](https://i.imgur.com/f617rEX.png)

---
Temporary solution(AHK code)
```
WinWait, ShareX - Optical character recognition,, 2
Clipboard := ""
WinActivate, ShareX - Optical character recognition
Send, ^a
Send, ^c
Sleep, 30
clip1 := RegExReplace(Clipboard, A_Space, "")
Clipboard := RegExReplace(clip1, "\r\n", "")
Sleep, 30
Send, ^v
Return
```

**Comment by Jaex** [comment] 2022-07-16 16:44
Duplicate of #6322

**Closed by Jaex** 2022-07-16 16:44 UTC
