### ISSUE TITLE
[Feature Request] Share'x image Editor Save Image as.. Doesn't remember last used location

### ISSUE THREAD

**Issue by greypo** [ShareX/ShareX#3822] opened 2018-12-12 09:59 UTC
Share'x Image Editor **"Save Image as.."**  default location always reverts back to default location of the personal folder for the screenshots. I really miss feature where it would save location of the last used folder instead. It's a lot of unnecessary clicks if I have to make a lot of screenshots and save them to specific folder.

**Comment by Jaex** [comment] 2018-12-12 10:11
Duplicate of #3791

**Closed by Jaex** 2018-12-12 10:11 UTC
