### ISSUE TITLE
Request to be able to change Image Editor key binds - Especially copying image

### ISSUE THREAD

**Issue by ekhcentrics** [ShareX/ShareX#6710] opened 2023-01-25 12:49 UTC
This was mentioned multiple times in https://github.com/ShareX/ShareX/issues/2984

Can we get the ability to CHANGE the keybindings for the image editor? ( https://getsharex.com/docs/keybinds)
ESPECIALLY for copying the image.

I truly don't understand why Ctrl+C copies the position and size info instead of the image itself - the position and size info seems immensly non-helpful

**Comment by tehmichael** [comment] 2023-04-07 16:40
I second this.  I'd rather copy and paste functions work similarly to other applications (or at least have the option to change key bindings).

**Comment by znre** [comment] 2023-06-06 02:27
Agree with this.

**Comment by warchiefmarkus** [comment] 2023-11-04 23:03
Up, I want ability to set my own hotkey for "End capturing" or while capturing from "Enter" to other (ctrl + c)

**Comment by selaromdotnet** [comment] 2023-12-06 23:46
adding my vote as well, would love to use ctrl c to copy the image, it gets me every time that I just end up with coordinates that I don't think would ever be of any use to me whatsoever.

thanks!

**Comment by Export33** [comment] 2024-01-05 08:38
yes, please change copy to ctrl+c or make some of the basic keybindings configurable.

**Comment by phantasm** [comment] 2024-01-11 01:42
seriously? it hasn't been done from the start, or yet implemented, or at least added to settings? o_O wow

**Comment by Jaex** [comment] 2024-02-06 08:42
Duplicate of #3495

**Closed by Jaex** 2024-02-06 08:42 UTC
