### ISSUE TITLE
V12.3.1 Taskbar position can cause menu detachment

### ISSUE THREAD

**Issue by chrisjj** [ShareX/ShareX#3842] opened 2018-12-17 23:47 UTC
E.g. with a left-side taskbar on Windows 7:

![image](https://user-images.githubusercontent.com/6157073/50122782-083a6b00-0256-11e9-941e-6b920bb5b69d.png)

**Comment by Jaex** [comment] 2018-12-18 05:37
Duplicate of #2173

**Closed by Jaex** 2018-12-18 05:37 UTC
