### ISSUE TITLE
Add support for Amazon Photos \ Amazon Drive

### ISSUE THREAD

**Issue by rolltidehero** [ShareX/ShareX#5685] opened 2021-07-05 07:35 UTC
Amazon Photos has **unlimited full-resolution storage** for all of your images and photos.
It's only for Prime members, but it's definitely the best image host I've used.
Can you please add this or help me figure out how to set it up under the custom uploader settings?

[https://developer.amazon.com/docs/amazon-drive/ad-restful-api-getting-started.html](https://developer.amazon.com/docs/amazon-drive/ad-restful-api-getting-started.html)

![image](https://user-images.githubusercontent.com/11590510/124434275-4b3b8b80-dd39-11eb-9a9b-63751519cdb4.png)

**Comment by Jaex** [comment] 2021-07-05 09:49
Duplicate of #1532

**Closed by Jaex** 2021-07-05 09:49 UTC
