### ISSUE TITLE
Not uploading

### ISSUE THREAD

**Issue by TWSSYesterday** [ShareX/ShareX#3032] opened 2017-12-29 18:59 UTC
Getting this error: https://pastebin.com/u3ErMkqh
All I'm doing is the default Ctrl + Print Screen and that normally uploads to imgur. If it's 100% a problem with imgur I'll just do it to my own server, please advise.
Many thanks

**Comment by chaseoes** [comment] 2017-12-29 19:02
I'm also currently unable to upload, may be an imgur issue.

**Comment by TWSSYesterday** [comment] 2017-12-29 19:05
Gotta love Github follow aha.

**Comment by chaseoes** [comment] 2017-12-29 19:07
Not even following you, my ShareX wasn't working so I immediately came here to look to see if anyone reported it!

**Comment by Jaex** [comment] 2017-12-29 19:14
Duplicate of #3027

**Closed** 2017-12-29 19:14 UTC
Labels: Duplicate
