### ISSUE TITLE
This feature will not work when "Disableupload" is enabled.

### ISSUE THREAD

**Issue by davcomNZ** [ShareX/ShareX#4682] opened 2020-03-16 19:45 UTC
Only been happening since latest update and only on some of my PC's but when I go to take a screenshot I get the popup "This feature will not work when "DisableUpload" is enabled".
I have no idea what "this feature" might be and I've had DisableUpload enabled for literally years without this happening.
Can the feature in question be identified in the popup so it is possible to know what to tick or untick so this advisory message does not needed to be cleared every time a screenshot is taken.
TIA.

**Comment by sylveon** [comment] 2020-03-16 19:47
Duplicate of #4652

**Closed** 2020-03-16 20:43 UTC
Labels: Duplicate
