### ISSUE TITLE
rightclick stops working properly when i screenshot and i cant screenshot any active windows

### ISSUE THREAD

**Issue by boop9** [ShareX/ShareX#5730] opened 2021-08-02 06:56 UTC
![WP6wz6Wd3K](https://user-images.githubusercontent.com/85202743/127816317-73ddbd62-b0a4-400e-8e47-2b636647c310.png) (recreation, since i cant actually screenshot the problem)

as soon as i screenshot anything, even if i cancel the screenshot, my rightclick stops working.
restarting my computer fixes the problem until i screenshot again. i tried using other screenshotting software and it worked so the problem seemed to lie in sharex.
does anyone know a solution? is this not a sharex related problem? if so where do i go to find a solution/ where is a solution?

**Comment by Jaex** [comment] 2021-08-02 06:59
Duplicate of #5712

**Closed by Jaex** 2021-08-02 06:59 UTC
