### ISSUE TITLE
Can't upload the image

### ISSUE THREAD

**Issue by Active-Baby** [ShareX/ShareX#3031] opened 2017-12-29 16:56 UTC
Account type: User
Authorization: successful

After uploading an image to server I get next error:

```
Message:
The remote server returned an error: (400) Bad Request.

Request URL:
https://api.imgur.com/3/image

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata) 
```

**Comment by Jaex** [comment] 2017-12-29 16:58
Duplicate of #3027

**Closed by Jaex** 2017-12-29 16:58 UTC
Labels: Duplicate
