### ISSUE TITLE
Pointer misplacement in GIF recording

### ISSUE THREAD

**Issue by o-l-a-v** [ShareX/ShareX#3902] opened 2019-01-22 09:29 UTC
When doing GIF recordings, the pointer is not placed correctly. It misses by quite a lot actually. Looks wierd in GIFs.

System:
* Lenovo X1 Carbon 5th Gen, Intel UHD 620 latest drivers.
* Windows 10 Enterprise 1809 x64
* Monitors: 2x 1920x1200px, 125% scaling on all screens including laptop.
* ShareX Microsoft Store version

What have I tried to mitigate the issue:
* Tried the same GIF recording on all of my screens.
* Set the scale options inside properties \ compatibility \ change high DPI settings \ High DPI scaling override to Application, for ShareX found inside "%ProgramFiles%\WindowsApps\19568ShareX.ShareX_12.3.2.0_x64__egrzcvs15399j"

Tell me what you need of logs or similar, and I'll provide

Heres a ShareX recorded GIF to show you the problem.
![2019-01-22_10-23-33](https://user-images.githubusercontent.com/6450056/51525135-ef623e00-1e2f-11e9-87c5-45f9b50e3294.gif)

**Comment by Jaex** [comment] 2019-01-22 10:08
Duplicate of #1329

**Closed by Jaex** 2019-01-22 10:08 UTC
Labels: Duplicate

**Comment by o-l-a-v** [comment] 2019-01-22 15:37
@Jaex 
As stated in the initial issue description: Overriding scaling settings in Windows does not help.
