### ISSUE TITLE
ShareX Integration Kutt Shorturl

### ISSUE THREAD

**Issue by xianx** [ShareX/ShareX#3455] opened 2018-06-19 02:29 UTC
Hello,

I am trying to integrate Kutt https://github.com/thedevs-network/kutt#api with shareX with Custom Short URL https://github.com/ShareX/CustomUploaders like Yourls https://github.com/ShareX/CustomUploaders/blob/master/yourls.org.sxcu

but could not figure out how to do that and what to enter which field on Custom ShortURL making interface see the screenshot https://zdrive.techtunes.com.bd/s/JYr9qcJWk2orPC3

I have also generate API key and passed the value as Header Value of X-API-Key see the screenshot https://zdrive.techtunes.com.bd/s/N2r3bF3k6XD78PS

In debug window its showing {"error":"No target has been provided."}
https://zdrive.techtunes.com.bd/s/4MeEReQrd2TP9cX

How to integrate Kutt with ShareX properly?

**Comment by Jaex** [comment] 2018-06-19 08:59
Duplicate of https://github.com/thedevs-network/kutt/issues/67

**Comment by xianx** [comment] 2018-06-19 15:54
Can you add kutt in url shortener service in ShareX?

**Comment by xianx** [comment] 2018-06-19 16:00
Kutt supports urlencoded POST data as answered by kutt. How to make them work with shareX?

**Comment by xianx** [comment] 2018-06-26 20:49
Is this been added?

**Comment by xianx** [comment] 2018-06-29 01:08
I am waiting for the integration. Any ETA?

**Comment by xianx** [comment] 2018-07-02 13:36
Can I get a reply?

**Comment by nightah** [comment] 2018-07-02 15:45
If your services sit behind NGINX or apache you can have the webserver manipulate the request to allow this to work, per https://github.com/thedevs-network/kutt/issues/67.

**Closed** 2018-10-01 23:14 UTC
Labels: Enhancement

**Comment by Jaex** [comment] 2018-10-01 23:40
I added Kutt support but I'm unable to test custom host.

**Comment by DananFlander** [comment] 2020-07-02 20:12
I am unable to get custom host to work with Kutt through ShareX. Has anyone tested this successfully?

@Jaex

**Comment by nightah** [comment] 2020-07-03 00:13
Works fine over here.

**Comment by DananFlander** [comment] 2020-07-03 00:25
Default Kutt integration works, but custom domain doesn't appear to work.
Is there anything I need to do other than redirect my A record and then
enter my host URL and API key into ShareX?

**Comment by nightah** [comment] 2020-07-03 00:29
Do you mean a custom host as in from the kutt website or as in hosting yourself?
I only have experience with the latter not the former.

**Comment by DananFlander** [comment] 2020-07-03 00:59
Yeah, the custom host function from the Kutt website works manually, but the custom host portion of the ShareX integration doesn't appear to be functioning.

**Comment by DananFlander** [comment] 2020-07-03 01:18
Here are my settings that are not working as intended. I get thrown kutt.it links, not danan.gg ones.

![chrome_2020-07-02_18-14-50](https://user-images.githubusercontent.com/4238186/86421906-62601d00-bc90-11ea-9452-80a065d97692.png)

**Comment by InsaneSplash** [comment] 2020-07-17 15:56
I have the same issue... Unable to use the custom domain. Maybe this plugin needs the ability to select or enter your custom domain when the url is submitted?

**Comment by Jaex** [comment] 2020-07-29 15:37
Added custom domain support now. You can try it with [dev build](https://getsharex.com/docs/dev-builds).
