### ISSUE TITLE
The remote server returned an error: (400) Bad Request.

### ISSUE THREAD

**Issue by donniess** [ShareX/ShareX#3802] opened 2018-12-03 11:09 UTC
I have no clue about coding and this issue is pretty frustrating. 

Here is the log file

2018-12-03 11:57:42.042 - Executing: Capture region
2018-12-03 11:57:45.421 - Task in queue. Job: Job, Type: Image, Host: Imgur
2018-12-03 11:57:45.426 - Task status: Preparing
2018-12-03 11:57:45.443 - Image copied to clipboard.
2018-12-03 11:57:45.456 - Image saved to file: C:\Users\NAME\Documents\ShareX\Screenshots\2018-12\2018-12-03_11-57-45.png
2018-12-03 11:57:45.460 - Upload started. Filename: 2018-12-03_11-57-45.png, Filepath: C:\Users\NAME\Documents\ShareX\Screenshots\2018-12\2018-12-03_11-57-45.png
2018-12-03 11:57:45.695 - Error:
Message:
The remote server returned an error: (400) Bad Request.
 
Request URL:
https://api.imgur.com/3/image
 
Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)

**Comment by Jaex** [comment] 2018-12-03 11:09
Duplicate of #3800

**Closed by Jaex** 2018-12-03 11:09 UTC
Labels: Duplicate
