### ISSUE TITLE
Install on Surface Pro, ARM

### ISSUE THREAD

**Issue by AStove** [ShareX/ShareX#4961] opened 2020-08-03 19:49 UTC
On a Microsoft Surface Pro X , OS Windows 10, I can run the portable version, which is x86 but I cannot run the installer. This has an ARM CPU but it is able to run x86 executables using emulation. I feel like the processor check in the installer is stopping it but it would actually work if the check wasn't there.

Can only run 32bit though. Maybe the installer does not include 32bit?

Cannot install from the store either.

**Comment by Jaex** [comment] 2020-08-03 20:12
Duplicate of #4922

**Closed by Jaex** 2020-08-03 20:12 UTC
