### ISSUE TITLE
hey

### ISSUE THREAD

**Issue by mohamedb11117** [ShareX/ShareX#3498] opened 2018-07-03 19:46 UTC
Imgur upload failed: (400) These actions are forbidden.

Message:
أرجع الملقم البعيد الخطأ: (400) طلب غير صالح.

Request URL:
https://api.imgur.com/3/image

Response:
{"data":{"error":"These actions are forbidden."},"success":false,"status":400}

Stack trace:
   عند System.Net.HttpWebRequest.GetResponse()
   عند ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)

**Comment by Jaex** [comment] 2018-07-03 19:47
Duplicate of #3395

**Closed by Jaex** 2018-07-03 19:47 UTC
