### ISSUE TITLE
Mouse cursor offset with 4k resolution

### ISSUE THREAD

**Issue by JeFawk** [ShareX/ShareX#3522] opened 2018-07-11 19:49 UTC
I recently switched to a 4k monitor and ShareX now shows the cursor offset from where it is. You can see in the video that I press the button. I then go and make a rectangle where the description text area is.

The cursor is offset with a decent amount. Thanks for the program btw, it's great!
[2018-07-11_22-43-44.zip](https://github.com/ShareX/ShareX/files/2185981/2018-07-11_22-43-44.zip)

**Comment by Jaex** [comment] 2018-07-11 19:51
Duplicate of #1329

**Closed by Jaex** 2018-07-11 19:51 UTC
Labels: Duplicate

**Comment by JeFawk** [comment] 2018-07-12 16:02
Sorry :/
