### ISSUE TITLE
%pn not working for subfolder naming.

### ISSUE THREAD

**Issue by Nyhmz** [ShareX/ShareX#3704] opened 2018-11-02 05:04 UTC
I read in another issue that the reason why you made it not work there is because if it does not capture an application it would leave the folder name empty. 

However why not make it so if it doesn't detect a process default to what it can see. 

For example if I take an image of Discord using %pn%y%m it would name the folder Discord 2018 11 but if it's a process it cannot identify just name it 2018 11?

**Comment by Jaex** [comment] 2018-11-03 09:41
Duplicate of #2293

**Closed by Jaex** 2018-11-03 09:41 UTC
