### ISSUE TITLE
Issues when capturing Desktop by click with Region Capture

### ISSUE THREAD

**Issue by HIJIKIsw** [ShareX/ShareX#3112] opened 2018-02-01 05:21 UTC
When I place the cursor on the desktop with Region Capture,
Part of the area at the bottom of the screen will not be captured.

https://imgur.com/a/JbxhZ

The image captured by clicking as it is will be as follows.

https://imgur.com/a/3hoCi

**Comment by Jaex** [comment] 2018-02-01 13:35
Duplicate of #1338

**Closed** 2018-02-01 13:36 UTC
Labels: Duplicate
