### ISSUE TITLE
capture video crash

### ISSUE THREAD

**Issue by Aokromes** [ShareX/ShareX#964] opened 2015-09-02 17:59 UTC
Hi, i got this when i clicked abort after capture one video:

Os: Windows 10 build 10532
ShareX: 10.1

http://pastebin.com/mymLrXBB

**Comment by Jaex** [comment] 2015-09-03 10:27
Was it started and recording when you pressed abort? Were you recording mp4/webm or animated gif? I'm not sure how this happened because it was doing what you do normally when you press Stop button and this error never happened to me before. So something must be different.

**Comment by Aokromes** [comment] 2015-09-03 10:38
Yes, it was started, i have got this crash few times, but i am unable to reproduce 100% of times.
As for format it was mp4.

**Comment by SharkWipf** [comment] 2015-09-10 11:32
Ah, didn't see this issue was open already, I've added more information on reproduction in #982

**Comment by Jaex** [comment] 2015-09-10 19:23
Wrote solution in #982 therefore closing this. Problem to do with FFmpeg GDIGrab.

**Closed by Jaex** 2015-09-10 19:23 UTC
Labels: Cannot reproduce
