### ISSUE TITLE
OCR totally broken for Japanese

### ISSUE THREAD

**Issue by nammerduong** [ShareX/ShareX#6361] opened 2022-07-12 06:32 UTC
I was using OCR just fine before version 14. Now after version 14 any OCR I do has terrible accuracy to what is actually shown on screen. Also, even if the OCR gets the text correctly, it would put a space between each character like this: "何 し て る の ?". Which makes the OCR pretty useless. I even tried to revert back to version 13.7.0 but for some reason any time I try to OCR, I just get an error now. The OCR wont pickup anything.

**Comment by Jaex** [comment] 2022-07-12 06:37
Duplicate of #6322

**Closed by Jaex** 2022-07-12 06:37 UTC
