### ISSUE TITLE
[Imgur] The remote server returned an error: (403) Forbidden.

### ISSUE THREAD

**Issue by avia666** [ShareX/ShareX#1138] opened 2015-11-24 10:49 UTC
Idk this randomly started happening and wont stop giving me this error every time i take a screenshot

Message:
The remote server returned an error: (403) Forbidden.

Response:
{"data":{"error":"The access token provided is invalid.","request":"\/3\/image","method":"POST"},"success":false,"status":403}

StackTrace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.UploadData(Stream dataStream, String url, String fileName, String fileFormName, Dictionary`2 arguments, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String requestContentType, String metadata)

**Comment by Jaex** [comment] 2015-11-24 18:01
Re authenticate your login from destination settings.

**Comment by AGSPhoenix** [comment] 2015-11-25 00:43
This temporarily resolves the issue, but it starts happening again after an hour or so.

I've noticed that imgur added a captcha at some point in the past (the support article about it was added on the 11th); maybe that's related?

**Comment by Jaex** [comment] 2015-11-25 00:49
Look like they did changes to oauth tokens today maybe that causing this issues.

**Comment by Jaex** [comment] 2015-11-25 02:42
According to API changes page "Changed access_token expiration from one hour to one month." but I think they changed expire time of token one month but it actually expire still one hour and because ShareX still see one month left for it to expire it not trying to refresh it. So they need to fix it in their end.

**Comment by Sleavely** [comment] 2015-11-25 14:24
I'm experiencing the same thing as of very recently (past two days). Couldn't this be solved in ShareX by simply refreshing the token more often?

**Comment by Jaex** [comment] 2015-11-25 18:26
What you suggesting is not good solution. Brute forcing refresh just in case their API have problem. What if this problem get solved in few hours? Then for no reason ShareX would be refreshing it a lot and slowing uploads when it is supposed to expire in one month.

I emailed them yesterday to report this problem but I don't think they will reply because they were not replied to my previous 4 emails too. I'm not even sure are they reading my emails to be honest. But we will see.

**Comment by Sleavely** [comment] 2015-11-25 18:36
Fair enough, I just figured it would be nice if it worked - regardless of whos fault it is that the expiration is set to an hour.

From what I can tell, they list api@imgur.com as the point of contact.

**Comment by Jaex** [comment] 2015-11-25 18:38
I emailed api@imgur.com last 5 times but got no response yet so I'm not sure are they receiving my emails or just ignoring them. Maybe someone known need to email them for them to notice it.

**Comment by jeremejevs** [comment] 2015-11-25 19:31
As a non-brute-force solution, couldn't ShareX just try refreshing the token upon receiving a 403? I can see this being useful even if the API is returning a correct `expires_in`, e.g. when client's computer clock isn't very accurate or the service provider decides to revoke all active sessions for some reason. This could also be a setting in `Settings > Upload > Retry` (or on per-destination basis).

**Comment by Jaex** [comment] 2015-11-25 20:50
Imgur replied now they telling issue should be fixed now. But you will get one more time error and after refreshing your token, it will work fine afterwards.

**Comment by jeremejevs** [comment] 2015-11-25 21:36
That's nice to hear, but still, shouldn't a 403 error be a trigger for a one-time token refresh attempt?

**Comment by Jaex** [comment] 2015-11-25 21:37
They fixed it for new tokens so previous tokens we obtained before fix still gonna have this problem.

**Comment by jeremejevs** [comment] 2015-11-25 21:42
Yeah, I understand that this particular issue is resolved, but I'm just saying that it [probably?] wouldn't hurt anybody, if ShareX would attempt to re-login when getting a 403, because that's exactly what this HTTP code is for.

**Comment by Jaex** [comment] 2015-11-25 21:46
There can be another reasons for 403 too also refreshing key sometimes becomes invalid too. So it won't be good idea.

**Comment by jeremejevs** [comment] 2015-11-25 21:48
It could be per-destination then. For example, in this case, Imgur explicitly says in `data.error` that `The access token provided is invalid.`.

**Comment by Jaex** [comment] 2015-11-25 21:48
Also ignoring/hiding errors with workarounds can be problematic like we couldn't figure out that there is error in Imgur side and be able to report them to fix it.

**Comment by jeremejevs** [comment] 2015-11-25 21:52
But then your users wouldn't experience any discomfort either. But yeah, I'm here to suggest :)

**Comment by Jaex** [comment] 2015-11-25 22:03
New token is not expired after one hour so problem is fixed now.

**Closed by Jaex** 2015-11-25 22:03 UTC
Labels: Cannot fix

**Comment by jeremejevs** [comment] 2015-12-02 10:56
Went through the full authorization process a couple of times (as in clearing the token and getting a new PIN), the issue is still here. Please, just implement automatic token refresh on 403, as an opt-in setting or something. Most users (including myself) likely don't care whether this is Imgur's or ShareX's fault, they just want this tool to not interfere with their workflow, and there's a both logical *and* straightforward-to-implement solution right there. I don't see how 403 + `data.error: The access token provided is invalid.` can be interpreted as something other than a call for a token refresh.

**Comment by Jaex** [comment] 2015-12-02 11:08
How you can find that solution as straightforward when it was requiring you to upload same file two times and delay whole process alot?

**Comment by jeremejevs** [comment] 2015-12-02 11:11
Whole difference right now is that a user is required to refresh the token manually, instead of having ShareX do it for him (still two uploads). I understand that this is like having pain, which forces a user to report the problem, but this is the case when fixing the source of the problem is out of your hands, and the workaround I proposed isn't really a workaround, it's merely a valid reaction to a message from the server.

**Comment by Sleavely** [comment] 2015-12-14 08:37
Since this is yet again an issue I'd like to share my thoughts and take-aways here:

* Writing code without dealing with exceptions is weird, no matter why the exception occurs. **Your** users are experiencing issues, not Imgurs.
* The error message explicitly calls for using the refresh token once. If it has been revoked the refresh token will not work and ShareX should not retry using the refresh token.
* The user wants to upload an image, not save bandwidth (then why try to upload an image in the first place?).
* Obtaining a new access token and retrying is - on most connections - faster than having the user:  
  1. Manually open up the Imgur settings dialog
  2. Logging in to Imgur in a browser
  3. Copy-pasting the PIN into ShareX
  4. Manually finding the screenshot in a dialog somewhere in ShareX (a program that I normally never have to navigate)
  5. Finding the right upload option in a context menu

**Comment by Jaex** [comment] 2015-12-14 09:15
"Writing code without dealing with exceptions is weird" what is weird about it, how am I supposed to know every single error Imgur can return to me to handle them when programming them first. Not to mention in majority of errors Imgur actually not even returns proper json response. Also how am I supposed to implement them when I couldn't reproduce that error cases. Actually few days ago I tried to upload image to Imgur from their web site and I got Forbidden error so Imgur experience so many issues in their web site too not just ShareX.

**Comment by Jaex** [comment] 2015-12-14 09:26
And it is not that quick fix I can just check error message and refresh authentication. Like http web request not even returns response when error code is 403 so I handle error separately to show them later but this need to be handled in upload process and so many other changes will be required for uploading codes etc.

**Comment by Jaex** [comment] 2015-12-14 10:50
http://api.imgur.com/changelog
```Changed access_token expiration back to confirm it wasn't causing extra load.	12/10/15```

Look like because of this again tokens expired. Interesting thing is making it expire every hour will cause more load so I'm not sure why they reverted it.

**Comment by lupuleasa-core** [comment] 2018-12-03 10:04
Experiencing this one right now.
Will check the chain here for #1240 and #1226
