### ISSUE TITLE
Bug: No hotkey or tray action will start a GIF

### ISSUE THREAD

**Issue by dylanh724** [ShareX/ShareX#7369] opened 2024-03-29 04:08 UTC
I have a Logitech G502X:

1. Set opts to set middle click on tray icon:
  ![image](https://github.com/ShareX/ShareX/assets/8840024/adb1354a-89fb-43f9-b6df-d44096ad2c1a)

2. Middle click tray icon: 
    - **Expected:** GIF start
    - **What actually happened:** Same as left click (prep take a screenshot)
    
**EDIT:** Similarly, a hotkey setting *also* fails to start a GIF (and instead just takes a normal screenshot area action)
![image](https://github.com/ShareX/ShareX/assets/8840024/00d50622-fe8d-4b52-90d6-626af6adcbad)

This means no possible way to start a GIF with a hotkey.

Win11, ShareX 16.0.1

**Comment by Combinacijus** [comment] 2024-04-09 20:56
![image](https://github.com/ShareX/ShareX/assets/16375702/eb73bd99-a088-477d-ab2f-79fedf5704a6)

Can confirm middle click still opens main window instead of starting GIF even after restarting ShareX. Other options doesn't work either on middle click. Even setting to None still opens main window.

But Ctrl + Print Screen works for me

**Comment by Combinacijus** [comment] 2024-04-09 23:01
Related https://github.com/ShareX/ShareX/issues/7254

**Comment by Jaex** [comment] 2024-06-16 23:14
Duplicate of #6791

**Closed by Jaex** 2024-06-16 23:14 UTC
