### ISSUE TITLE
[Feature Request]Firefox Send

### ISSUE THREAD

**Issue by x9cf9w73cv7y** [ShareX/ShareX#4020] opened 2019-03-12 16:15 UTC
It would be nice to add support for Firefox Send since it's not a beta anymore.
https://send.firefox.com/
https://github.com/mozilla/send

**Comment by Kezxo** [comment] 2019-03-12 16:59
This command line tool can upload files to Firefox Send if that helps in some way: https://github.com/timvisee/ffsend

**Comment by Jaex** [comment] 2019-03-14 06:05
Duplicate of #2736

**Closed by Jaex** 2019-03-14 06:05 UTC
