### ISSUE TITLE
Can't revert BorderlessWindow, HELP!

### ISSUE THREAD

**Issue by minnieoo** [ShareX/ShareX#6994] opened 2023-07-18 01:26 UTC
I tried out the borderless window tool on the sharex program and now I have no idea how to reverse it, help

**Comment by eqoffical** [comment] 2024-05-25 16:15
[same thing](https://github.com/ShareX/ShareX/issues/6115#issuecomment-2131303293)

**Comment by Jaex** [comment] 2024-06-25 16:43
Duplicate of #6015

**Closed by Jaex** 2024-06-25 16:43 UTC
Labels: Duplicate
