### ISSUE TITLE
Unable to save screenshots (different error from CJampion)

### ISSUE THREAD

**Issue by Kiokurashi** [ShareX/ShareX#3776] opened 2018-11-20 07:40 UTC
Sometime after November 15th I have been unable to save any captures. I can still upload them, but anything that I try to save to my computer fails. If I just save the full screen then it stops the task right there, but if I resize the capture and then try to save I get the following exception text.
************** Exception Text **************
System.ArgumentException: Parameter is not valid.
   at System.Drawing.Image.get_Width()
   at ShareX.TaskHelpers.GetFilename(TaskSettings taskSettings, String extension, ImageInfo imageInfo)
   at ShareX.TaskHelpers.<>c__DisplayClass41_0.<AnnotateImage>b__0(Image output, String newFilePath)
   at ShareX.ScreenCaptureLib.RegionCaptureForm.OnSaveImageRequested()
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripButton.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at ShareX.HelpersLib.ToolStripEx.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

I have also atteched the rest of the dialogue for the loaded assemblies.
[Sharex exception log..txt](https://github.com/ShareX/ShareX/files/2598598/Sharex.exception.log.txt)

**Comment by Jaex** [comment] 2018-11-20 09:15
It is fixed:

![](https://jaex.getsharex.com/2018/11/ShareX_ZcxiwIAZVn.png)

**Comment by Jaex** [comment] 2018-11-20 09:17
Duplicate of #3735

**Closed by Jaex** 2018-11-20 09:17 UTC

**Comment by Kiokurashi** [comment] 2018-11-20 11:34
All I can say is that it works fine and the window closes when I press the save button. In the Main window it shows that it was stopped, and that it was bmp file despite me having set it to be png. Perhaps that might help isolate it? Also I never get the windows popup save window like I used to.

**Comment by Jaex** [comment] 2018-11-20 11:36
Main window never show saved file path in previous versions too? I even checked 12.2 to verify that. So it works same as before.

**Comment by Kiokurashi** [comment] 2018-11-20 11:39
I'm not saying that it showed it, I'm saying that my image isn't there and it says it stopped. I can still upload shots so here's a screenshot: https://i.imgur.com/5Hnq1H9.png

**Comment by Jaex** [comment] 2018-11-20 11:40
Because you stopped task by closing annotation window without press continue button at left top corner.

**Comment by Kiokurashi** [comment] 2018-11-20 11:43
What are you talking about? https://i.imgur.com/3gYsLVH.png

**Comment by Kiokurashi** [comment] 2018-11-20 16:05
Now I see by reading another thread what you meant. It's highly unintuitive, and seems to have been a recent change.
