### ISSUE TITLE
[Feature request] WebP and animated WebP

### ISSUE THREAD

**Issue by o-l-a-v** [ShareX/ShareX#3656] opened 2018-10-08 10:58 UTC
Edge and Chromium supports WebP, Mozilla Firefox is right around the corner.
Would be nice if we could export screen shots and captures (videos) to WebP and animated WebP to save bytes, make web pages more responsive.

ZDNET.com: "Firefox and Edge add support for Google's WebP image format"
https://www.zdnet.com/article/firefox-and-edge-add-support-for-googles-webp-image-format/
* Whatch out for auto playing videos

**Comment by Jaex** [comment] 2018-10-08 20:26
Duplicate of #765

**Closed by Jaex** 2018-10-08 20:26 UTC
