### ISSUE TITLE
Lambda changed domain (again)

### ISSUE THREAD

**Issue by Rodocks** [ShareX/ShareX#3102] opened 2018-01-28 19:33 UTC
they now use https://lbda.net/ instead of lambda.sx, lambda.sx now redirects to the new site so now meaning that you cannot properly upload directly to lambda using the preset. Really at this point you should be able to pick whatever domain you want for lambda encase they change domain again.

**Comment by Jaex** [comment] 2018-01-28 19:42
Duplicate of #3101

**Closed** 2018-01-28 19:42 UTC
Labels: Duplicate
