### ISSUE TITLE
Lambda file hosting changed url

### ISSUE THREAD

**Issue by Kaos1337** [ShareX/ShareX#3101] opened 2018-01-28 14:05 UTC
Hi,
the default file uploader settings "Lambda" isn't working anymore, they have changed the url to: https://lbda.net

**Comment by Jaex** [comment] 2018-01-28 14:06
Duplicate of #3100

**Closed by Jaex** 2018-01-28 14:06 UTC
Labels: Duplicate

**Comment by mstojcevich** [comment] 2018-01-28 21:07
I have removed the domain redirect, so the existing URLs should at least work until I can write a better fix to update the config files that use the old domain (xn--wxa, which is no longer up)
