### ISSUE TITLE
Icon in Tray - double click or wheel click do the same as single click

### ISSUE THREAD

**Issue by zalupakonya** [ShareX/ShareX#7254] opened 2024-02-02 20:21 UTC
Stable version and dev version
Windows canary - latest build
Different settings for different clicks in Sharex settings, but they all do the same, how single click was set up.

**Comment by dylanh724** [comment] 2024-04-10 00:44
Same

**Comment by Jaex** [comment] 2024-06-16 23:17
Duplicate of #6791

**Closed by Jaex** 2024-06-16 23:17 UTC
