### ISSUE TITLE
[Bug] Multiple monitors with different display scaling can cause cursor offset in video recordings

### ISSUE THREAD

**Issue by Gorialis** [ShareX/ShareX#5412] opened 2021-02-19 13:28 UTC
My monitor setup is as such:
![image](https://user-images.githubusercontent.com/8049998/108508360-091c2b00-72ff-11eb-92b2-b4e0b44c910d.png)

The left monitor (monitor 2) is 1920x1080 native res at 100% display scaling.
The right monitor (monitor 1) is 2560x1440 native res at 125% display scaling.

When recording on the right (1) monitor using either `screen-capture-recorder` or `GDI grab`, in both standard and GIF recording modes, the cursor appears noticeably offset up and to the left of where it should be:

> https://user-images.githubusercontent.com/8049998/108508939-e9d1cd80-72ff-11eb-8200-ab11db9fd052.mp4

Conversely, recording on the left (2) monitor using `GDI grab` in either recording mode, the inverse effect happens:

> https://user-images.githubusercontent.com/8049998/108509441-9449f080-7300-11eb-9924-8676203abbd7.mp4

While `screen-capture-recorder` offsets incorrectly on the right monitor, it does not do so on the left:

> https://user-images.githubusercontent.com/8049998/108509599-c6f3e900-7300-11eb-9a4f-a35d944c60fc.mp4

My suspicion is thus that:

- `screen-capture-recorder` does not handle display scaling properly. It incorrectly assumes the right (1) monitor has the same display scaling as the left (2) at 100%, or maybe doesn't factor display scaling in at all. Thus, the cursor ends up at 100/125 of where it should be relative to the monitor, resulting in an upwards-left offset in the recording, the severity of which is dependent on how far the recording takes place from the top left of the screen.

- `GDI grab` is aware of display scaling and attempts to compensate for it, but assigns the wrong scales to each monitor, potentially because monitor 2 is to the left of monitor 1, a relatively unusual configuration. Because of this, `GDI grab` makes the cursor end up at 100/125 of where it should be on the right monitor (upwards-left), and 125/100 of where it should be on the left monitor (downwards-right).

This issue can be worked around by setting all monitors to the same display scale and using `GDI grab`, but this is inconvenient to do for quick recordings and messes with the windows on the workspace.

**Comment by Jaex** [comment] 2021-02-19 13:45
Duplicate of #1329

**Closed by Jaex** 2021-02-19 13:45 UTC
