### ISSUE TITLE
 Error while capturing the region

### ISSUE THREAD

**Issue by Navka1** [ShareX/ShareX#2358] opened 2017-03-10 12:12 UTC
System.Runtime.InteropServices.ExternalException (0x80004005): В GDI+ возникла ошибка общего вида.
   в System.Drawing.Image.Save(String filename, ImageCodecInfo encoder, EncoderParameters encoderParams)
   в ShareX.TaskHelpers.CreateThumbnail(Image img, String folder, String filename, TaskSettings taskSettings)
   в ShareX.WorkerTask.DoAfterCaptureJobs()
   в ShareX.WorkerTask.DoThreadJob()
   в ShareX.WorkerTask.ThreadDoWork()
   в ShareX.HelpersLib.ThreadWorker.WorkThread()
   в System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   в System.Threading.ThreadHelper.ThreadStart()

**Comment by YasseenDeHerdt** [comment] 2017-03-21 16:31
Looks like duplicate of #2337

**Closed** 2017-04-01 17:57 UTC
Labels: Duplicate
