### ISSUE TITLE
Blank entries in main windows' recent captures list

### ISSUE THREAD

**Issue by arusergithub** [ShareX/ShareX#4520] opened 2019-12-11 22:41 UTC
This and quite a few others show blank:

![image](https://user-images.githubusercontent.com/50074375/70666776-49960880-1c67-11ea-8522-23855af2ee02.png)

even though a click confirms it is present.

**Comment by Zaczero** [comment] 2019-12-18 17:53
Looks like a similar problem to #4510 which should be fixed by now =)

**Comment by Jaex** [comment] 2019-12-18 18:42
Duplicate of #4510

**Closed by Jaex** 2019-12-18 18:42 UTC

**Comment by arusergithub** [comment] 2019-12-18 19:59
> Looks like a similar problem to #4510 which should be fixed by now =)

The 13.0.1 (up to date) still shows the fail: 
![image](https://user-images.githubusercontent.com/50074375/71118895-e0ffdc00-21d0-11ea-93e4-702fda04043f.png)

**Comment by Jaex** [comment] 2019-12-18 19:59
It is fixed in dev build.
