### ISSUE TITLE
#5957 current date / time in extracted photos 

### ISSUE THREAD

**Issue by Ritterkuno** [ShareX/ShareX#5959] opened 2021-11-25 09:47 UTC
I'm opening this thread again here, because my additional comment on this has apparently not been read or is not readable:
I'm sorry, but it doesn't work. The date is visible in the preview (see attached photo), but not in the real picture. 
here are my settings:

![Date1](https://user-images.githubusercontent.com/94909017/143417449-3979d59c-708f-4298-9151-eaf24d085e33.JPG) 

The problem is that I had to enter the specifications:% y% m .... etc. manually. It was not possible to enter the 
data with a mouse click to the right of the form, the field always remained empty ....

**Comment by Ritterkuno** [comment] 2021-11-25 09:47
I testet this with two pc (WIN 10)

**Comment by Jaex** [comment] 2021-11-25 09:49
Duplicate of #5957

**Closed by Jaex** 2021-11-25 09:49 UTC
