### ISSUE TITLE
Request: for video capture, allow to capture mouse clicks and keyboard types

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [ShareX/ShareX#3488] opened 2018-06-29 08:06 UTC
Show on the recorded video which is clicked: mouse right/left click, keyboard keys, etc...

**Comment by Jaex** [comment] 2018-06-30 14:58
Duplicate of #1040

**Closed by Jaex** 2018-06-30 14:58 UTC

**Comment by AndroidDeveloperLB** [comment] 2018-06-30 15:00
Why duplicate?
I'm talking about all kinds of interaction.
Not just mouse. Also keyboard...

**Comment by abaumgaertner** [comment] 2020-10-22 06:01
give try this: https://github.com/bfritscher/carnac/
