### ISSUE TITLE
Uploading error

### ISSUE THREAD

**Issue by RangoMyouta** [ShareX/ShareX#3036] opened 2017-12-29 22:33 UTC
I found 1 threat to this problem, but didnt really help me out to much, im having issues uploading images. Here is the error message: 

Message:
Der kunne ikke skrives data til transportforbindelsen: En eksisterende forbindelse blev tvangsafbrudt af en ekstern vært.

Request URL:
https://api.imgur.com/3/image

Stack trace:
   ved System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   ved System.Net.Security._SslStream.StartWriting(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   ved System.Net.Security._SslStream.ProcessWrite(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   ved System.Net.TlsStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   ved System.Net.ConnectStream.InternalWrite(Boolean async, Byte[] buffer, Int32 offset, Int32 size, AsyncCallback callback, Object state)
   ved System.Net.ConnectStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   ved ShareX.UploadersLib.Uploader.TransferData(Stream dataStream, Stream requestStream)
   ved ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)

**Comment by SC2Mitch** [comment] 2017-12-29 22:42
#3027 retoast, Imgur replied with a statement on the problem:
Imgur Statement
I apologize for this hassle and inconvenience. This morning we were made aware of uploads failing for many Imgurians across all platforms: iOS, Android, Desktop. Unfortunately, while we work on this issue, your dank memes will have to wait to be shared with the community.
Our team is working hard on finding the cause and solution as soon as possible; we apologize for the inconvenience.

**Comment by Jaex** [comment] 2017-12-29 22:51
Duplicate of #3027

**Closed** 2017-12-29 22:51 UTC
Labels: Bug
