### ISSUE TITLE
[Feature Request] Undo/Redo function on image editor

### ISSUE THREAD

**Issue by jacquen** [ShareX/ShareX#4079] opened 2019-04-15 01:18 UTC
Hi

Can we add undo/redo function on image editor to support all operation in image editor, specially will be useful by corp and image resize operation, curently there is no way reverse back.

Thanks

**Comment by gpion** [comment] 2019-04-24 17:13
Duplicate of #3673 ?

**Comment by jacquen** [comment] 2019-04-25 01:18
not exactly same, if we can have redo/undo function in image resize or corp, even it will be better if we can have this function in image editor globally,  it will help lot.

**Comment by Caiuzx** [comment] 2019-08-24 16:08
there is still no redo function and all times  I lose my precious time: P

**Comment by derekantrican** [comment] 2020-02-05 15:54
+1 - could really use a "Ctrl+Y" redo function

**Comment by rogeriodec** [comment] 2020-05-23 17:24
Undo is working with Ctrl+Z. 
But I don't know why there is no redo (Ctrl+Shift+Z)...

**Comment by Slapbox** [comment] 2020-05-29 00:01
Undo without redo is just adding another delete button to the application but not labeling it as such :(

Otherwise, incredible app - wow.

**Comment by 3rady** [comment] 2020-07-06 01:58
@rogeriodec wrote:

> Undo is working with Ctrl+Z.

The Undo (Ctrl-Z) function works with many operations, but not all.  For example, the OP mentions the crop operation cannot be undone.

**Comment by NAL100** [comment] 2020-07-22 17:49
Definitely need undo and redo. Came here to make this a new issue but I spent 20 minutes highlighting and image only to find out I couldn't undo edits. Huge problem that almost makes it unusable.

**Comment by PontiacCZ** [comment] 2020-12-10 19:07
Oh, such a trivial issue opened from 2019? :-o I came here because I did a crop and was not able to undo it using CTRL + Z . 

Isn't this project abandoned? I have just noticed those 450 opened issues...

**Comment by Vampire** [comment] 2021-02-12 00:18
Shift + Del can also not be undone :-(

**Comment by Slapbox** [comment] 2021-02-12 01:03
The fact this issue still exists is so sad, because this is otherwise the greatest friggin' software...

**Comment by frizzr** [comment] 2021-06-02 22:16
We all love you ShareX developers, but please oh please give us some kind of redo capability here to undo the undo we did in error that leads us to repeat a _lot_ of lost editing work.

I confess I do find the undo operation very, _ahem_, **underwhelming** when it comes to granularity of actions (I'm screaming on the inside here...but with total love for the developers!) 

Seriously though, giving us just a very simple redo action here would save me _literally an hour a month_...and I'm just one person (who still loves your product dearly!)

Thanks so much for considering...really. We know it's not easy reading complaint sessions from your users, but at least one user like myself cares enough to craft this message in a way that might make you laugh and take our good-natured pleas to heart.

**Comment by Slapbox** [comment] 2021-06-02 23:13
It's the greatest app, but I assume this must be a really difficult thing to resolve or that the image editing is just not high on the developer priorities.

**Comment by Karlstens** [comment] 2021-07-28 03:52
Argghh, not having a "Redo" Ctrl Y in ShareX image editor makes me a sad panda! 

Also, what's with this right-click behaviour? I keep accidentally right-clicking to find that it acting as Undo (Ctrl Z) and then have no Redo option to repair an accidental right click.

**Comment by berkdemir** [comment] 2021-12-30 12:52
I cannot see any response from developers. Maybe there is a reason for not implementing this feature, but can someone from Dev Team comment on this?

**Comment by cknori** [comment] 2022-08-29 12:34
I might take a crack at this one if anybody could help me understand how exactly the editor is implemented?

Doing a quick search of "undo" on this repository has given me plenty of results but almost all of them seem to be for context menus. The only thing I can find that is related to undoing an action in the editor is in **ShareX/ShareX.ScreenCaptureLib/Shapes/ShapeManager.cs** where on line **702:** https://github.com/ShareX/ShareX/blob/e2b93615fdf4ed59bf80619f453dbf7801f73736/ShareX.ScreenCaptureLib/Shapes/ShapeManager.cs#L701-L703 it seems to call UndoShape() after pressing ctrl+z. 

UndoShape() is found in the same file on line **1525:** https://github.com/ShareX/ShareX/blob/e2b93615fdf4ed59bf80619f453dbf7801f73736/ShareX.ScreenCaptureLib/Shapes/ShapeManager.cs#L1525-L1531 and the function appears to outright delete the most recently created shape.

I imagine a good way to implement a redo function to this would be to push each undo onto a stack, pop them off the stack and draw the shape again when a redo is requested, and delete the stack when a new action is made after undoing. However, this does not fix the fact that undo doesn't work on every action in the editor, not to mention that deleting an object in the editor also cannot be undone due to how undo is currently implemented, so those deletion actions would also need to be pushed onto this stack.

As I've only recently started looking at this codebase, I'm not fully familiar with it and I appear to be unable to find much documentation on it? Since this is the only undo function I can find, and there are a few things in the editor than can be undone, it seems there's a few things that are considered to be a shape in the editor, and I'm curious what exactly those are and how the other features of the editor are implemented. If anybody can explain those, that would be a good starting point.

**Closed** 2023-12-27 04:13 UTC
Labels: Enhancement

**Comment by Jaex** [comment] 2023-12-27 09:35
Feel free to test undo/redo support which is implemented by @gregorygregio using [dev build](https://getsharex.com/docs/dev-builds).

Past 4 hours I'm doing testings and fixing the bugs I encounter, but there could be more bugs that I'm unable to find.

**Comment by Slapbox** [comment] 2023-12-27 21:38
Thank you @gregorygregio! Excited to give this a try.
