### ISSUE TITLE
Screen recording not working

### ISSUE THREAD

**Issue by NityanDesai** [ShareX/ShareX#4600] opened 2020-02-03 18:41 UTC

**Comment by NityanDesai** [comment] 2020-02-03 18:42
System.ArgumentException: Font 'Verdana' does not support style 'Regular'.
   at System.Drawing.Font.CreateNativeFont()
   at System.Drawing.Font.Initialize(FontFamily family, Single emSize, FontStyle style, GraphicsUnit unit, Byte gdiCharSet, Boolean gdiVerticalFont)
   at System.Drawing.Font..ctor(String familyName, Single emSize)
   at ShareX.ScreenCaptureLib.RegionCaptureForm..ctor(RegionCaptureMode mode, RegionCaptureOptions options, Image canvas)
   at ShareX.ScreenCaptureLib.RegionCaptureTasks.GetRectangleRegion(Rectangle& rect, RegionCaptureOptions options)
   at ShareX.ScreenRecordManager.StartRecording(ScreenRecordOutput outputType, TaskSettings taskSettings, ScreenRecordStartMethod startMethod)
   at ShareX.ScreenRecordManager.StartStopRecording(ScreenRecordOutput outputType, ScreenRecordStartMethod startMethod, TaskSettings taskSettings)
   at ShareX.TaskHelpers.ExecuteJob(TaskSettings taskSettings, HotkeyType job, CLICommand command)
   at ShareX.MainForm.HandleHotkeys(HotkeySettings hotkeySetting)
   at ShareX.HotkeyManager.OnHotkeyTrigger(HotkeySettings hotkeySetting)
   at ShareX.HotkeyManager.hotkeyForm_HotkeyPress(UInt16 id, Keys key, Modifiers modifier)
   at ShareX.HelpersLib.HotkeyForm.OnKeyPressed(UInt16 id, Keys key, Modifiers modifier)
   at ShareX.HelpersLib.HotkeyForm.WndProc(Message& m)
   at ShareX.MainForm.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by Jaex** [comment] 2020-02-04 01:33
Duplicate of #374

**Closed by Jaex** 2020-02-04 01:33 UTC
