### ISSUE TITLE
Increase the icon size in the editor for high res screen

### ISSUE THREAD

**Issue by Cozzie** [ShareX/ShareX#5076] opened 2020-09-26 06:09 UTC
![image](https://user-images.githubusercontent.com/1536187/94331738-693dc800-0012-11eb-821a-85736fea403b.png)

It's 2020, many people have high res screen. ShareX can lose many users simply because of poor user experience.

**Comment by Jaex** [comment] 2020-09-26 07:57
It's 2020, try to search issues before opening new ones.

Duplicate of #4960

**Closed by Jaex** 2020-09-26 07:57 UTC

**Comment by Cozzie** [comment] 2020-09-26 15:53
Thanks for the correction. I searched only open issues (understandably should have searched closed as well) and in google and both are old threads (Last one being https://github.com/ShareX/ShareX/issues/4450).

Hope this gets implemented soon.
