### ISSUE TITLE
Unhandled exception: Overflow Exception

### ISSUE THREAD

**Issue by Abzol** [ShareX/ShareX#3106] opened 2018-01-29 21:22 UTC
Process:
1 - Start a regional capture
2 - Paste an image or text onto the canvas
3 - Grab a handle of the pasted item
4 - While still holding the handle, press shift.

Expected result: Not sure. I was originally expecting aspect-locked scaling
Actual result: ShareX crashdumps and [flushes the entire canvas with a big red cross](https://i.imgur.com/MNMQQkN.png)

Reproduced on two machines.

    2018-01-29 22:11:55.152 - Hotkey triggered. Hotkey: Ctrl + Print Screen, Description: Capture to clipboard, Job: RectangleRegion
    2018-01-29 22:11:55.152 - Executing: Capture region
    2018-01-29 22:11:58.024 - Unhandled exception:
    System.OverflowException: Overflow error.
       at System.Drawing.Graphics.CheckErrorStatus(Int32 status)
       at System.Drawing.Graphics.DrawImage(Image image, Int32 x, Int32 y, Int32 width, Int32 height)
       at System.Drawing.Graphics.DrawImage(Image image, Rectangle rect)
       at ShareX.ScreenCaptureLib.ImageDrawingShape.DrawImage(Graphics g)
       at ShareX.ScreenCaptureLib.RegionCaptureForm.Draw(Graphics g)
       at ShareX.ScreenCaptureLib.RegionCaptureForm.OnPaint(PaintEventArgs e)
       at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
       at System.Windows.Forms.Control.WmPaint(Message& m)
       at System.Windows.Forms.Control.WndProc(Message& m)
       at System.Windows.Forms.Form.WndProc(Message& m)
       at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

    ShareX 12.0 (Release)

**Comment by Jaex** [comment] 2018-01-29 21:23
Duplicate of #2963

**Closed by Jaex** 2018-01-29 21:24 UTC
Labels: Duplicate
