### ISSUE TITLE
FFmpeg screen record stop/abort buttons not working

### ISSUE THREAD

**Issue by 1112e** [ShareX/ShareX#581] opened 2015-03-30 06:15 UTC
Was working before, changed a few settings, now I the recording keeps going until it decides to stop

**Comment by Jaex** [comment] 2015-03-30 06:18
Can you check in FFmpeg config window "Test with CMD" button is there any error it have? Because rarely when error happens it is supposed to close CMD window but it not closing and stucks like that. Because I can't reproduce this situation, I can't fix it too.

**Comment by 1112e** [comment] 2015-03-30 06:22
It only does this when I enable audio; Heres the error it gives me

http://pastebin.com/kj6mak1U

**Comment by Jaex** [comment] 2015-03-30 06:26
[webm @ 0000000004726280] Only VP8 or VP9 video and Vorbis or Opus audio and WebVTT subtitles are supported for WebM.

**Comment by Jaex** [comment] 2015-03-30 06:27
You trying webm recording with aac audio codec which not supported.

**Comment by 1112e** [comment] 2015-03-30 06:28
Ah, I see

**Comment by 1112e** [comment] 2015-03-30 06:29
I still get the same thing when I switched it to vorbis

**Comment by Jaex** [comment] 2015-03-30 06:30
VP8 and Vorbis together supposed to work.
But for real time recording I suggest x264 because with webm so much frame drops happens.

**Comment by Jaex** [comment] 2015-03-30 06:34
I'm failing to understand how in your case when CLI give error how it not closes automatically. I keep trying and same errors happens and then CLI exe closing so ShareX can continue.

**Comment by 1112e** [comment] 2015-03-30 06:35
I'm still getting the same problem after switching to x264. Works fine if I disable audio recording

**Comment by Jaex** [comment] 2015-03-30 06:36
Than your audio source is not supported by ffmpeg. Are you not using these?: ![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/03/aoYovoIsIui.png)

**Comment by 1112e** [comment] 2015-03-30 06:39
That seems to have fixed it! Oops

**Comment by 1112e** [comment] 2015-03-30 06:44
While I'm here, is there a way to set up a hotkey to start and stop a ffmpeg recording of a set area (1 monitor, not both)?

**Comment by Jaex** [comment] 2015-03-30 06:54
There is hotkey for active monitor screen capture but not for screen recording and I'm not planning to add it because there is already tons of hotkeys in list.

**Closed** 2015-03-30 06:55 UTC
Labels: Cannot fix
