### ISSUE TITLE
I get a bad error opening the app

### ISSUE THREAD

**Issue by madrbperu** [ShareX/ShareX#4831] opened 2020-05-26 21:39 UTC
This is what I get on the first and only window that opens...

System.Reflection.TargetInvocationException: Se produjo una excepción en el destino de la invocación. ---> System.ArgumentException: La fuente 'Arial' no es compatible con el estilo 'Regular'.
   en System.Drawing.Font.CreateNativeFont()
   en System.Drawing.Font.Initialize(FontFamily family, Single emSize, FontStyle style, GraphicsUnit unit, Byte gdiCharSet, Boolean gdiVerticalFont)
   en System.Drawing.Font..ctor(SerializationInfo info, StreamingContext context)
   --- Fin del seguimiento de la pila de la excepción interna ---
   en System.RuntimeMethodHandle.SerializationInvoke(IRuntimeMethodInfo method, Object target, SerializationInfo info, StreamingContext& context)
   en System.Runtime.Serialization.ObjectManager.CompleteISerializableObject(Object obj, SerializationInfo info, StreamingContext context)
   en System.Runtime.Serialization.ObjectManager.FixupSpecialObject(ObjectHolder holder)
   en System.Runtime.Serialization.ObjectManager.DoFixups()
   en System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(HeaderHandler handler, __BinaryParser serParser, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   en System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, HeaderHandler handler, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   en System.Resources.ResourceReader.DeserializeObject(Int32 typeIndex)
   en System.Resources.ResourceReader.LoadObjectV2(Int32 pos, ResourceTypeCode& typeCode)
   en System.Resources.ResourceReader.ResourceEnumerator.get_Entry()
   en System.Resources.ResourceReader.ResourceEnumerator.get_Current()
   en System.ComponentModel.ComponentResourceManager.FillResources(CultureInfo culture, ResourceSet& resourceSet)
   en System.ComponentModel.ComponentResourceManager.FillResources(CultureInfo culture, ResourceSet& resourceSet)
   en System.ComponentModel.ComponentResourceManager.FillResources(CultureInfo culture, ResourceSet& resourceSet)
   en System.ComponentModel.ComponentResourceManager.ApplyResources(Object value, String objectName, CultureInfo culture)
   en ShareX.HelpersLib.MyPictureBox.InitializeComponent()
   en ShareX.HelpersLib.MyPictureBox..ctor()
   en ShareX.MainForm.InitializeComponent()
   en ShareX.MainForm.InitializeControls()
   en ShareX.Program.Run()
   en ShareX.Program.Main(String[] args)

ShareX 13.1 (Release)

FOUR ONLY OPTIONS (buttons) to choose:  
![image](https://user-images.githubusercontent.com/49217274/82952714-1a522a00-9f6f-11ea-96d5-09c66295d4d4.png)

THEN THE REGISTRY:

2020-05-22 01:12:45.925 - ShareX starting.
2020-05-22 01:12:46.821 - Version: 13.0.1
2020-05-22 01:12:46.821 - Build: Release
2020-05-22 01:12:46.821 - Command line: "C:\Program Files\ShareX\ShareX.exe" 
2020-05-22 01:12:46.821 - Personal path: C:\Users\User\Documents\ShareX
2020-05-22 01:12:46.855 - Operating system: Windows 7 Ultimate (64-bit)
2020-05-22 01:12:47.111 - Running as elevated process: False
2020-05-22 01:12:52.722 - ApplicationConfig load started: C:\Users\User\Documents\ShareX\ApplicationConfig.json
2020-05-22 01:17:58.436 - ApplicationConfig load finished: C:\Users\User\Documents\ShareX\ApplicationConfig.json
2020-05-22 01:17:58.441 - UploadersConfig load started: C:\Users\User\Documents\ShareX\UploadersConfig.json
2020-05-22 01:18:18.430 - UploadersConfig load finished: C:\Users\User\Documents\ShareX\UploadersConfig.json
2020-05-22 01:18:20.337 - HotkeysConfig load started: C:\Users\User\Documents\ShareX\HotkeysConfig.json
2020-05-22 01:18:38.230 - Language changed to: Español (España)
2020-05-22 01:18:42.543 - MainForm init started.
2020-05-22 01:18:51.224 - HotkeysConfig load finished: C:\Users\User\Documents\ShareX\HotkeysConfig.json
2020-05-22 01:21:27.741 - Unhandled exception:
System.Reflection.TargetInvocationException: Se produjo una excepción en el destino de la invocación. ---> System.ArgumentException: La fuente 'Arial' no es compatible con el estilo 'Regular'.
   en System.Drawing.Font.CreateNativeFont()
   en System.Drawing.Font.Initialize(FontFamily family, Single emSize, FontStyle style, GraphicsUnit unit, Byte gdiCharSet, Boolean gdiVerticalFont)
   en System.Drawing.Font..ctor(SerializationInfo info, StreamingContext context)
   --- Fin del seguimiento de la pila de la excepción interna ---
   en System.RuntimeMethodHandle.SerializationInvoke(IRuntimeMethodInfo method, Object target, SerializationInfo info, StreamingContext& context)
   en System.Runtime.Serialization.ObjectManager.CompleteISerializableObject(Object obj, SerializationInfo info, StreamingContext context)
   en System.Runtime.Serialization.ObjectManager.FixupSpecialObject(ObjectHolder holder)
   en System.Runtime.Serialization.ObjectManager.DoFixups()
   en System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(HeaderHandler handler, __BinaryParser serParser, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   en System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, HeaderHandler handler, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   en System.Resources.ResourceReader.DeserializeObject(Int32 typeIndex)
   en System.Resources.ResourceReader.LoadObjectV2(Int32 pos, ResourceTypeCode& typeCode)
   en System.Resources.ResourceReader.ResourceEnumerator.get_Entry()
   en System.Resources.ResourceReader.ResourceEnumerator.get_Current()
   en System.ComponentModel.ComponentResourceManager.FillResources(CultureInfo culture, ResourceSet& resourceSet)
   en System.ComponentModel.ComponentResourceManager.FillResources(CultureInfo culture, ResourceSet& resourceSet)
   en System.ComponentModel.ComponentResourceManager.FillResources(CultureInfo culture, ResourceSet& resourceSet)
   en System.ComponentModel.ComponentResourceManager.ApplyResources(Object value, String objectName, CultureInfo culture)
   en ShareX.HelpersLib.MyPictureBox.InitializeComponent()
   en ShareX.HelpersLib.MyPictureBox..ctor()
   en ShareX.MainForm.InitializeComponent()
   en ShareX.MainForm.InitializeControls()
   en ShareX.Program.Run()
   en ShareX.Program.Main(String[] args)

ShareX 13.0.1 (Release)
2020-05-22 01:22:48.744 - ShareX continue.
2020-05-22 01:23:10.252 - URL opened: https://github.com/ShareX/ShareX/issues?q=is%3Aissue
2020-05-22 01:23:10.252 - URL opened: https://github.com/ShareX/ShareX/issues?q=is%3Aissue
2020-05-22 01:27:44.403 - ShareX starting.
2020-05-22 01:27:44.406 - Version: 13.0.1
2020-05-22 01:27:44.406 - Build: Release
2020-05-22 01:27:44.406 - Command line: "C:\Program Files\ShareX\ShareX.exe" 
2020-05-22 01:27:44.406 - Personal path: C:\Users\User\Documents\ShareX
2020-05-22 01:27:44.407 - Operating system: Windows 7 Ultimate (64-bit)
2020-05-22 01:27:44.408 - Running as elevated process: False
2020-05-22 01:27:44.601 - ApplicationConfig load started: C:\Users\User\Documents\ShareX\ApplicationConfig.json
2020-05-22 01:28:01.502 - ApplicationConfig load finished: C:\Users\User\Documents\ShareX\ApplicationConfig.json
2020-05-22 01:28:01.506 - UploadersConfig load started: C:\Users\User\Documents\ShareX\UploadersConfig.json
2020-05-22 01:28:01.785 - Language changed to: Español (España)
2020-05-22 01:28:01.787 - MainForm init started.
2020-05-22 01:28:02.666 - UploadersConfig load finished: C:\Users\User\Documents\ShareX\UploadersConfig.json
2020-05-22 01:28:02.670 - HotkeysConfig load started: C:\Users\User\Documents\ShareX\HotkeysConfig.json
2020-05-22 01:28:03.322 - HotkeysConfig load finished: C:\Users\User\Documents\ShareX\HotkeysConfig.json
2020-05-22 01:28:08.523 - Unhandled exception:
System.Reflection.TargetInvocationException: Se produjo una excepción en el destino de la invocación. ---> System.ArgumentException: La fuente 'Arial' no es compatible con el estilo 'Regular'.
   en System.Drawing.Font.CreateNativeFont()
   en System.Drawing.Font.Initialize(FontFamily family, Single emSize, FontStyle style, GraphicsUnit unit, Byte gdiCharSet, Boolean gdiVerticalFont)
   en System.Drawing.Font..ctor(SerializationInfo info, StreamingContext context)
   --- Fin del seguimiento de la pila de la excepción interna ---
   en System.RuntimeMethodHandle.SerializationInvoke(IRuntimeMethodInfo method, Object target, SerializationInfo info, StreamingContext& context)
   en System.Runtime.Serialization.ObjectManager.CompleteISerializableObject(Object obj, SerializationInfo info, StreamingContext context)
   en System.Runtime.Serialization.ObjectManager.FixupSpecialObject(ObjectHolder holder)
   en System.Runtime.Serialization.ObjectManager.DoFixups()
   en System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(HeaderHandler handler, __BinaryParser serParser, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   en System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, HeaderHandler handler, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   en System.Resources.ResourceReader.DeserializeObject(Int32 typeIndex)
   en System.Resources.ResourceReader.LoadObjectV2(Int32 pos, ResourceTypeCode& typeCode)
   en System.Resources.ResourceReader.ResourceEnumerator.get_Entry()
   en System.Resources.ResourceReader.ResourceEnumerator.get_Current()
   en System.ComponentModel.ComponentResourceManager.FillResources(CultureInfo culture, ResourceSet& resourceSet)
   en System.ComponentModel.ComponentResourceManager.FillResources(CultureInfo culture, ResourceSet& resourceSet)
   en System.ComponentModel.ComponentResourceManager.FillResources(CultureInfo culture, ResourceSet& resourceSet)
   en System.ComponentModel.ComponentResourceManager.ApplyResources(Object value, String objectName, CultureInfo culture)
   en ShareX.HelpersLib.MyPictureBox.InitializeComponent()
   en ShareX.HelpersLib.MyPictureBox..ctor()
   en ShareX.MainForm.InitializeComponent()
   en ShareX.MainForm.InitializeControls()
   en ShareX.Program.Run()
   en ShareX.Program.Main(String[] args)

ShareX 13.0.1 (Release)
2020-05-22 01:28:13.068 - URL opened: https://github.com/ShareX/ShareX/issues?q=is%3Aissue
2020-05-22 01:28:13.673 - URL opened: https://github.com/ShareX/ShareX/issues?q=is%3Aissue
2020-05-22 01:28:17.543 - URL opened: https://github.com/ShareX/ShareX/issues?q=is%3Aissue
2020-05-22 01:28:18.419 - URL opened: https://github.com/ShareX/ShareX/issues?q=is%3Aissue
2020-05-22 01:28:19.132 - URL opened: https://github.com/ShareX/ShareX/issues?q=is%3Aissue
2020-05-22 01:28:21.291 - ShareX continue.
2020-05-22 01:51:34.230 - ShareX starting.
2020-05-22 01:51:35.290 - Version: 13.1
2020-05-22 01:51:35.290 - Build: Release
2020-05-22 01:51:35.291 - Command line: "C:\Program Files\ShareX\ShareX.exe"
2020-05-22 01:51:35.291 - Personal path: C:\Users\User\Documents\ShareX
2020-05-22 01:51:35.302 - Operating system: Windows 7 Ultimate (64-bit)
2020-05-22 01:51:36.226 - Running as elevated process: False
2020-05-22 01:51:38.897 - ApplicationConfig load started: C:\Users\User\Documents\ShareX\ApplicationConfig.json
2020-05-22 01:52:12.327 - ApplicationConfig load finished: C:\Users\User\Documents\ShareX\ApplicationConfig.json
2020-05-22 01:52:12.413 - Migrating XML history file "C:\Users\User\Documents\ShareX\History.xml" to JSON history file "C:\Users\User\Documents\ShareX\History.json"
2020-05-22 01:52:14.582 - UploadersConfig load started: C:\Users\User\Documents\ShareX\UploadersConfig.json
2020-05-22 01:52:15.615 - UploadersConfig load finished: C:\Users\User\Documents\ShareX\UploadersConfig.json
2020-05-22 01:52:15.620 - HotkeysConfig load started: C:\Users\User\Documents\ShareX\HotkeysConfig.json
2020-05-22 01:52:16.660 - Language changed to: Español (España)
2020-05-22 01:52:16.687 - HotkeysConfig load finished: C:\Users\User\Documents\ShareX\HotkeysConfig.json
2020-05-22 01:52:17.307 - MainForm init started.
2020-05-22 01:52:25.521 - Unhandled exception:
System.Reflection.TargetInvocationException: Se produjo una excepción en el destino de la invocación. ---> System.ArgumentException: La fuente 'Arial' no es compatible con el estilo 'Regular'.
   en System.Drawing.Font.CreateNativeFont()
   en System.Drawing.Font.Initialize(FontFamily family, Single emSize, FontStyle style, GraphicsUnit unit, Byte gdiCharSet, Boolean gdiVerticalFont)
   en System.Drawing.Font..ctor(SerializationInfo info, StreamingContext context)
   --- Fin del seguimiento de la pila de la excepción interna ---
   en System.RuntimeMethodHandle.SerializationInvoke(IRuntimeMethodInfo method, Object target, SerializationInfo info, StreamingContext& context)
   en System.Runtime.Serialization.ObjectManager.CompleteISerializableObject(Object obj, SerializationInfo info, StreamingContext context)
   en System.Runtime.Serialization.ObjectManager.FixupSpecialObject(ObjectHolder holder)
   en System.Runtime.Serialization.ObjectManager.DoFixups()
   en System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(HeaderHandler handler, __BinaryParser serParser, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   en System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, HeaderHandler handler, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   en System.Resources.ResourceReader.DeserializeObject(Int32 typeIndex)
   en System.Resources.ResourceReader.LoadObjectV2(Int32 pos, ResourceTypeCode& typeCode)
   en System.Resources.ResourceReader.ResourceEnumerator.get_Entry()
   en System.Resources.ResourceReader.ResourceEnumerator.get_Current()
   en System.ComponentModel.ComponentResourceManager.FillResources(CultureInfo culture, ResourceSet& resourceSet)
   en System.ComponentModel.ComponentResourceManager.FillResources(CultureInfo culture, ResourceSet& resourceSet)
   en System.ComponentModel.ComponentResourceManager.FillResources(CultureInfo culture, ResourceSet& resourceSet)
   en System.ComponentModel.ComponentResourceManager.ApplyResources(Object value, String objectName, CultureInfo culture)
   en ShareX.HelpersLib.MyPictureBox.InitializeComponent()
   en ShareX.HelpersLib.MyPictureBox..ctor()
   en ShareX.MainForm.InitializeComponent()
   en ShareX.MainForm.InitializeControls()
   en ShareX.Program.Run()
   en ShareX.Program.Main(String[] args)

ShareX 13.1 (Release)
2020-05-22 01:52:51.351 - ShareX continue.
2020-05-22 01:54:38.256 - ShareX starting.
2020-05-22 01:54:38.259 - Version: 13.1
2020-05-22 01:54:38.259 - Build: Release
2020-05-22 01:54:38.260 - Command line: "C:\Program Files\ShareX\ShareX.exe" 
2020-05-22 01:54:38.260 - Personal path: C:\Users\User\Documents\ShareX
2020-05-22 01:54:38.261 - Operating system: Windows 7 Ultimate (64-bit)
2020-05-22 01:54:38.261 - Running as elevated process: True
2020-05-22 01:54:38.279 - ApplicationConfig load started: C:\Users\User\Documents\ShareX\ApplicationConfig.json
2020-05-22 01:54:39.143 - ApplicationConfig load finished: C:\Users\User\Documents\ShareX\ApplicationConfig.json
2020-05-22 01:54:39.148 - UploadersConfig load started: C:\Users\User\Documents\ShareX\UploadersConfig.json
2020-05-22 01:54:39.164 - Language changed to: Español (España)
2020-05-22 01:54:39.166 - MainForm init started.
2020-05-22 01:54:39.364 - UploadersConfig load finished: C:\Users\User\Documents\ShareX\UploadersConfig.json
2020-05-22 01:54:39.370 - HotkeysConfig load started: C:\Users\User\Documents\ShareX\HotkeysConfig.json
2020-05-22 01:54:39.399 - Unhandled exception:
System.Reflection.TargetInvocationException: Se produjo una excepción en el destino de la invocación. ---> System.ArgumentException: La fuente 'Arial' no es compatible con el estilo 'Regular'.
   en System.Drawing.Font.CreateNativeFont()
   en System.Drawing.Font.Initialize(FontFamily family, Single emSize, FontStyle style, GraphicsUnit unit, Byte gdiCharSet, Boolean gdiVerticalFont)
   en System.Drawing.Font..ctor(SerializationInfo info, StreamingContext context)
   --- Fin del seguimiento de la pila de la excepción interna ---
   en System.RuntimeMethodHandle.SerializationInvoke(IRuntimeMethodInfo method, Object target, SerializationInfo info, StreamingContext& context)
   en System.Runtime.Serialization.ObjectManager.CompleteISerializableObject(Object obj, SerializationInfo info, StreamingContext context)
   en System.Runtime.Serialization.ObjectManager.FixupSpecialObject(ObjectHolder holder)
   en System.Runtime.Serialization.ObjectManager.DoFixups()
   en System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(HeaderHandler handler, __BinaryParser serParser, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   en System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, HeaderHandler handler, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   en System.Resources.ResourceReader.DeserializeObject(Int32 typeIndex)
   en System.Resources.ResourceReader.LoadObjectV2(Int32 pos, ResourceTypeCode& typeCode)
   en System.Resources.ResourceReader.ResourceEnumerator.get_Entry()
   en System.Resources.ResourceReader.ResourceEnumerator.get_Current()
   en System.ComponentModel.ComponentResourceManager.FillResources(CultureInfo culture, ResourceSet& resourceSet)
   en System.ComponentModel.ComponentResourceManager.FillResources(CultureInfo culture, ResourceSet& resourceSet)
   en System.ComponentModel.ComponentResourceManager.FillResources(CultureInfo culture, ResourceSet& resourceSet)
   en System.ComponentModel.ComponentResourceManager.ApplyResources(Object value, String objectName, CultureInfo culture)
   en ShareX.HelpersLib.MyPictureBox.InitializeComponent()
   en ShareX.HelpersLib.MyPictureBox..ctor()
   en ShareX.MainForm.InitializeComponent()
   en ShareX.MainForm.InitializeControls()
   en ShareX.Program.Run()
   en ShareX.Program.Main(String[] args)

ShareX 13.1 (Release)
2020-05-22 01:54:39.430 - HotkeysConfig load finished: C:\Users\User\Documents\ShareX\HotkeysConfig.json
2020-05-22 01:54:42.830 - ShareX closing. Reason: Unhandled exception.
2020-05-26 16:24:29.000 - ShareX starting.
2020-05-26 16:24:29.004 - Version: 13.1
2020-05-26 16:24:29.004 - Build: Release
2020-05-26 16:24:29.004 - Command line: "C:\Program Files\ShareX\ShareX.exe" 
2020-05-26 16:24:29.004 - Personal path: C:\Users\User\Documents\ShareX
2020-05-26 16:24:29.006 - Operating system: Windows 7 Ultimate (64-bit)
2020-05-26 16:24:29.006 - Running as elevated process: False
2020-05-26 16:24:29.026 - ApplicationConfig load started: C:\Users\User\Documents\ShareX\ApplicationConfig.json
2020-05-26 16:24:30.158 - ApplicationConfig load finished: C:\Users\User\Documents\ShareX\ApplicationConfig.json
2020-05-26 16:24:30.166 - UploadersConfig load started: C:\Users\User\Documents\ShareX\UploadersConfig.json
2020-05-26 16:24:30.310 - Language changed to: Español (España)
2020-05-26 16:24:30.311 - MainForm init started.
2020-05-26 16:24:30.505 - UploadersConfig load finished: C:\Users\User\Documents\ShareX\UploadersConfig.json
2020-05-26 16:24:30.532 - HotkeysConfig load started: C:\Users\User\Documents\ShareX\HotkeysConfig.json
2020-05-26 16:24:31.032 - Unhandled exception:
System.Reflection.TargetInvocationException: Se produjo una excepción en el destino de la invocación. ---> System.ArgumentException: La fuente 'Arial' no es compatible con el estilo 'Regular'.
   en System.Drawing.Font.CreateNativeFont()
   en System.Drawing.Font.Initialize(FontFamily family, Single emSize, FontStyle style, GraphicsUnit unit, Byte gdiCharSet, Boolean gdiVerticalFont)
   en System.Drawing.Font..ctor(SerializationInfo info, StreamingContext context)
   --- Fin del seguimiento de la pila de la excepción interna ---
   en System.RuntimeMethodHandle.SerializationInvoke(IRuntimeMethodInfo method, Object target, SerializationInfo info, StreamingContext& context)
   en System.Runtime.Serialization.ObjectManager.CompleteISerializableObject(Object obj, SerializationInfo info, StreamingContext context)
   en System.Runtime.Serialization.ObjectManager.FixupSpecialObject(ObjectHolder holder)
   en System.Runtime.Serialization.ObjectManager.DoFixups()
   en System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(HeaderHandler handler, __BinaryParser serParser, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   en System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, HeaderHandler handler, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   en System.Resources.ResourceReader.DeserializeObject(Int32 typeIndex)
   en System.Resources.ResourceReader.LoadObjectV2(Int32 pos, ResourceTypeCode& typeCode)
   en System.Resources.ResourceReader.ResourceEnumerator.get_Entry()
   en System.Resources.ResourceReader.ResourceEnumerator.get_Current()
   en System.ComponentModel.ComponentResourceManager.FillResources(CultureInfo culture, ResourceSet& resourceSet)
   en System.ComponentModel.ComponentResourceManager.FillResources(CultureInfo culture, ResourceSet& resourceSet)
   en System.ComponentModel.ComponentResourceManager.FillResources(CultureInfo culture, ResourceSet& resourceSet)
   en System.ComponentModel.ComponentResourceManager.ApplyResources(Object value, String objectName, CultureInfo culture)
   en ShareX.HelpersLib.MyPictureBox.InitializeComponent()
   en ShareX.HelpersLib.MyPictureBox..ctor()
   en ShareX.MainForm.InitializeComponent()
   en ShareX.MainForm.InitializeControls()
   en ShareX.Program.Run()
   en ShareX.Program.Main(String[] args)

ShareX 13.1 (Release)
2020-05-26 16:24:31.054 - HotkeysConfig load finished: C:\Users\User\Documents\ShareX\HotkeysConfig.json
2020-05-26 16:24:36.949 - URL opened: https://github.com/ShareX/ShareX/issues?q=is%3Aissue
2020-05-26 16:24:37.320 - URL opened: https://github.com/ShareX/ShareX/issues?q=is%3Aissue
2020-05-26 16:24:37.656 - URL opened: https://github.com/ShareX/ShareX/issues?q=is%3Aissue
2020-05-26 16:24:39.358 - ShareX continue.
2020-05-26 16:25:19.856 - ShareX starting.
2020-05-26 16:25:19.859 - Version: 13.1
2020-05-26 16:25:19.860 - Build: Release
2020-05-26 16:25:19.860 - Command line: "C:\Program Files\ShareX\ShareX.exe" 
2020-05-26 16:25:19.860 - Personal path: C:\Users\User\Documents\ShareX
2020-05-26 16:25:19.862 - Operating system: Windows 7 Ultimate (64-bit)
2020-05-26 16:25:19.862 - Running as elevated process: False
2020-05-26 16:25:19.884 - ApplicationConfig load started: C:\Users\User\Documents\ShareX\ApplicationConfig.json
2020-05-26 16:25:20.908 - ApplicationConfig load finished: C:\Users\User\Documents\ShareX\ApplicationConfig.json
2020-05-26 16:25:20.916 - UploadersConfig load started: C:\Users\User\Documents\ShareX\UploadersConfig.json
2020-05-26 16:25:20.931 - Language changed to: Español (España)
2020-05-26 16:25:20.933 - MainForm init started.
2020-05-26 16:25:21.208 - Unhandled exception:
System.Reflection.TargetInvocationException: Se produjo una excepción en el destino de la invocación. ---> System.ArgumentException: La fuente 'Arial' no es compatible con el estilo 'Regular'.
   en System.Drawing.Font.CreateNativeFont()
   en System.Drawing.Font.Initialize(FontFamily family, Single emSize, FontStyle style, GraphicsUnit unit, Byte gdiCharSet, Boolean gdiVerticalFont)
   en System.Drawing.Font..ctor(SerializationInfo info, StreamingContext context)
   --- Fin del seguimiento de la pila de la excepción interna ---
   en System.RuntimeMethodHandle.SerializationInvoke(IRuntimeMethodInfo method, Object target, SerializationInfo info, StreamingContext& context)
   en System.Runtime.Serialization.ObjectManager.CompleteISerializableObject(Object obj, SerializationInfo info, StreamingContext context)
   en System.Runtime.Serialization.ObjectManager.FixupSpecialObject(ObjectHolder holder)
   en System.Runtime.Serialization.ObjectManager.DoFixups()
   en System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(HeaderHandler handler, __BinaryParser serParser, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   en System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream, HeaderHandler handler, Boolean fCheck, Boolean isCrossAppDomain, IMethodCallMessage methodCallMessage)
   en System.Resources.ResourceReader.DeserializeObject(Int32 typeIndex)
   en System.Resources.ResourceReader.LoadObjectV2(Int32 pos, ResourceTypeCode& typeCode)
   en System.Resources.ResourceReader.ResourceEnumerator.get_Entry()
   en System.Resources.ResourceReader.ResourceEnumerator.get_Current()
   en System.ComponentModel.ComponentResourceManager.FillResources(CultureInfo culture, ResourceSet& resourceSet)
   en System.ComponentModel.ComponentResourceManager.FillResources(CultureInfo culture, ResourceSet& resourceSet)
   en System.ComponentModel.ComponentResourceManager.FillResources(CultureInfo culture, ResourceSet& resourceSet)
   en System.ComponentModel.ComponentResourceManager.ApplyResources(Object value, String objectName, CultureInfo culture)
   en ShareX.HelpersLib.MyPictureBox.InitializeComponent()
   en ShareX.HelpersLib.MyPictureBox..ctor()
   en ShareX.MainForm.InitializeComponent()
   en ShareX.MainForm.InitializeControls()
   en ShareX.Program.Run()
   en ShareX.Program.Main(String[] args)

ShareX 13.1 (Release)
2020-05-26 16:25:21.215 - UploadersConfig load finished: C:\Users\User\Documents\ShareX\UploadersConfig.json
2020-05-26 16:25:21.221 - HotkeysConfig load started: C:\Users\User\Documents\ShareX\HotkeysConfig.json
2020-05-26 16:25:21.324 - HotkeysConfig load finished: C:\Users\User\Documents\ShareX\HotkeysConfig.json
2020-05-26 16:25:28.813 - File opened: C:\Users\User\Documents\ShareX\Logs\ShareX-Log-2020-05.txt

QUESTION: What seems to be the problem? I uninstalled and reinstalled it but the problem persists.
Thank you in advance.

**Comment by Jaex** [comment] 2020-05-27 00:24
Duplicate of #374

**Closed by Jaex** 2020-05-27 00:24 UTC
