### ISSUE TITLE
Second attempt to download FFMpeg.7z within same session will fail with IOException

### ISSUE THREAD

**Issue by kdrapel** [ShareX/ShareX#3005] opened 2017-12-14 19:38 UTC
1. Fresh installation
2. "Screen recording" --> FFMpeg download screen, would you like to download it, "OK"
3. Download fails
4. Second attempt "Screen recording", "OK" --> IO Exception

Looks like the same issue as #2461 that you marked as "cannot reproduce". I think you could reproduce it by simulating a timeout during the download.

System.IO.IOException: The process cannot access the file 'C:\Users\K\AppData\Local\Temp\ShareX\ffmpeg.7z' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at ShareX.HelpersLib.DownloaderForm.StartDownload()
   at ShareX.HelpersLib.DownloaderForm.DownloaderForm_Shown(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnShown(EventArgs e)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()

ShareX 12.0 (Release)

**Comment by Jaex** [comment] 2017-12-14 20:56
Duplicate of #2461

**Closed** 2017-12-14 21:01 UTC
Labels: Duplicate
