### ISSUE TITLE
HotKeys - Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by XenRevo** [ShareX/ShareX#1107] opened 2015-11-10 20:13 UTC
Shortcuts were not working for me
Went to the ShareX icon in the toolbar, right clicked -> Hotkey settings
Was presented with this screen (no hotkeys at all)
![HotKey Settings](http://i.imgur.com/jGEztQN.png?1)
Tried to fix by clicking **Restore Default Keys** this then returned an error __Object reference not set to an instance of an object__
The error code displayed

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at ShareX.HotkeySettingsForm.btnReset_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
````

**Comment by Jaex** [comment] 2015-11-10 21:22
Was it told unable to register hotkey? If you reopen ShareX is it works?

**Comment by graspee** [comment] 2015-11-11 03:22
I had a very similar problem. Today on Windows Boot, sharex complained it couldn't register its hotkeys. I went into the program to look at the hotkeys and got that same blank hotkey dialog shown above. I didn't click restore default hotkeys myself, I just attempted to close the dialog gand I got:

System.NullReferenceException: Object reference not set to an instance of an object.
   at ShareX.HotkeySettingsForm.HotkeySettingsForm_FormClosed(Object sender, FormClosedEventArgs e)
   at System.Windows.Forms.Form.OnFormClosed(FormClosedEventArgs e)
   at System.Windows.Forms.Form.CheckCloseDialog(Boolean closingOnly)

**Comment by Jaex** [comment] 2015-11-11 05:07
When it complain about hotkey did you pressed that hotkey to see which application was registered it? Maybe OneDrive?

**Comment by Jaex** [comment] 2015-11-11 07:33
OneDrive have screenshot feature now and it is installed by default in Windows 10. And most importantly even when screenshot capture feature of it is not enabled still it registers these hotkeys and not allow ShareX to register them. So only after close OneDrive then ShareX could register them.

But even then when I open hotkey settings window it was not empty like yours:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/11/cuxbzWrSyb.png)

So I'm not sure is it because that problem already fixed in my build or just I can't manage to reproduce it.

**Comment by Jaex** [comment] 2015-11-11 08:30
Adding possible conflicting process check now:

![](https://dl.dropboxusercontent.com/u/14076298/ShareX/2015/11/uGAkRy4q8m.png)

**Comment by Jaex** [comment] 2015-11-11 19:35
Only possible way I can find how you got these errors is that "Hotkey registration failed" message box was already open when you opened that hotkey settings window because as soon as that message box is closed it sets variable properly so it won't have NullReferenceException.

**Comment by XenRevo** [comment] 2015-11-12 03:22
I tried to replicate the "Hotkey registration failed" form. I was able to do so by instead of doing
1. Right click sharex icon (tool bar)
2. Clicking hotkey settings
Instead I did
1.Right Click Sharex icon (toolbar)
2.Show window
This then gave me the above window which says "Unable to register Hotkeys".

However, may I inquire as to how I can find out which other applications are using the hotkeys? OneDrive is not, and I do not have Dropbox installed. 

Furthermore, thanks for the quick reply and support.

**Comment by Jaex** [comment] 2015-11-12 03:25
There is no way to know which applications could be using hotkeys. But it is mainly very easy to figure out. Like closing applications which runs in background (tray apps) one by one and seeing which one was causing it. But you need to reopen ShareX to test it each time.

**Comment by XenRevo** [comment] 2015-11-12 03:28
I tried closing ShareX but I keep getting a window saying that there's an instance still running.
Task Manager has no ShareX Process running, would there be any sub process with different names that I could try killing that are related to ShareX?

**Comment by Jaex** [comment] 2015-11-12 03:29
ShareX won't tell there is an instance still running?! It will just activate already running process.

**Closed** 2015-11-13 09:11 UTC
Labels: Bug

**Comment by XenRevo** [comment] 2015-12-10 03:45
Do you know of anyway that I can see which programs are using the hotkeys? 
I would like to fix this.

**Comment by Jaex** [comment] 2015-12-10 03:46
I don't think there is a way.

**Comment by XenRevo** [comment] 2015-12-10 03:51
I've found [Windows HotKey Explorer](http://hkcmdr.anymania.com/index.html). However **don't run this on windows 8 or later as it will run every registered HotKey.**
Due to the fact that I am on Windows 10, I can't run it. Although if anyone else gets this problem you should recommend that tool, buddy.

Thanks though.

**Comment by Jaex** [comment] 2015-12-10 03:59
No I should not recommend it. Even this "However don't run this on windows 8 or later as it will run every registered HotKey." shows how ugly workaround it doing to try to figure out what app registered that hotkeys. There is no proper way.

**Comment by XenRevo** [comment] 2015-12-10 13:04
On earlier versions of windows it will not use stupid and somewhat _hacky_ methods to find the keys, it just does that on windows 8.
If you wont recommend it then I will, as you are just going to make it harder for your users to find their problem.

**Comment by Jaex** [comment] 2015-12-10 17:21
In all Windows versions it using same methods...
