### ISSUE TITLE
Request: allow customization of in-app hotkeys

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [ShareX/ShareX#3496] opened 2018-07-01 11:35 UTC
Currently we can customize only the global hotkeys, which are intended for the capturing itself.

What I'd like is to be able to customize the hotkeys within the app.
For example those:
https://github.com/ShareX/ShareX/issues/3490
https://github.com/ShareX/ShareX/issues/3495

**Comment by Jaex** [comment] 2018-07-05 09:02
Duplicate of #2984

**Closed by Jaex** 2018-07-05 09:02 UTC

**Comment by AndroidDeveloperLB** [comment] 2018-07-05 09:20
Why is it closed?
The request is to be able to customize the keys, no?
Also, I'm asking for more screens that we could modify the hotkeys in them, and the other post is about others.
