### ISSUE TITLE
Certain ShareX Settings Lost Upon PC Restart

### ISSUE THREAD

**Issue by DyKrass** [ShareX/ShareX#1427] opened 2016-03-21 02:36 UTC
I am running ShareX 10.8. After restarting my PC some of my ShareX settings were reset to default. Mainly my hotkeys, recording settings, and screenshot save paths. All history and image history were deleted. I still have the screenshots it saved so not a big issue there. My destinations were left intact. After setting up all of my settings as it were before, I backed them up. i was able to reproduce the issue by restarting my PC multiple times.

**Comment by Jaex** [comment] 2016-03-21 09:02
It not make sense how even history won't save for you because it saves when screenshot is uploaded instead of other places like when ShareX closing. So restarting can't affect that.

Duplicate of #702

**Closed** 2016-03-21 09:02 UTC
Labels: Duplicate
