### ISSUE TITLE
Undo does not undo movement of annotations

### ISSUE THREAD

**Issue by derekantrican** [ShareX/ShareX#4837] opened 2020-05-29 00:20 UTC
Undo can undo adding of annotations (eg a line/arrow/etc) but cannot undo moving them.

Repro steps:

1. Draw a line
2. Move it to a different location
3. Press Ctrl + Z
4. Note that the line completely disappears

Expected behavior: the step in # 2 should be undone and it should move back to the location it was after step # 1

**Comment by Jaex** [comment] 2020-05-29 10:35
Duplicate of #3673

**Closed by Jaex** 2020-05-29 10:35 UTC
