### ISSUE TITLE
Context menu uploading doesn't add the files in order and duplicates files in list

### ISSUE THREAD

**Issue by vavavr00m** [ShareX/ShareX#770] opened 2015-07-07 02:52 UTC
Number of files to be uploaded: 24
![Image](https://dl.dropboxusercontent.com/s/mt1bnxp4qbn4t99/2015-07-07_10-36-05.png)

Queued files:
![Image in queue](https://dl.dropboxusercontent.com/s/rnwgomrnynts73q/2015-07-07_10-50-10.png)

Mega error:
![Mega](https://dl.dropboxusercontent.com/s/a6nzdb45vxu73t5/2015-07-07_10-44-22.png)

**Comment by Jaex** [comment] 2015-07-07 02:57
Duplicate of #34 #200

Reason for it is Windows opens one ShareX.exe per file and single instance codes supposed to direct file paths to running ShareX but single instance codes have problem and if two or more upload happen in same time then it overwrites previous file path and gives it. And I didn't wrote this single instance code and can't figure out how to fix it.

As a workaround you can use Upload -> Upload file and select that multiple files.

About Mega it tells API not available so not to do with ShareX.

**Closed** 2016-03-04 08:55 UTC
Labels: Bug, Cannot fix
