### ISSUE TITLE
Region snapping is broken since 12.1.0

### ISSUE THREAD

**Issue by MorrisonGamer** [ShareX/ShareX#3314] opened 2018-04-16 10:14 UTC
Title. I don't really know what causes the problem, or how to reproduce it, region snapping just never works, enabled or disabled(discussed on Discord already), Even with NET 2.6.2 or the latest, it is broken, I do have Windows 7 Ultimate SP1 and restarting the program, resetting the settings does nothing.

However, when I tested 12.0.0, I haven't found a single problem with region snapping yet. It works exactly like it should. No matter if it's Steam or not(which I believe I can't access older versions).

Screenshot of ShareX 12.1.0+, with the mouse hovering over a window, and the region marker covering the whole screen: https://cdn.discordapp.com/attachments/279655394496872449/435231803356217345/unknown.png

**Comment by Jaex** [comment] 2018-04-16 10:16
![](https://jaex.getsharex.com/2018/04/chrome_yQFcAToelR.png)

**Comment by Jaex** [comment] 2018-04-16 10:16
Duplicate of #3312

**Closed by Jaex** 2018-04-16 10:16 UTC
Labels: Duplicate
