### ISSUE TITLE
Erroring On Trying To Capture W/ GIF

### ISSUE THREAD

**Issue by real-jake18** [ShareX/ShareX#3214] opened 2018-03-21 19:32 UTC
Every time I'm trying to hit my keybind to capture a GIF, it will tell me that I need to download something. I click Download and it will error in the downloading window. I cancel it, retry the entire process, then I'm presented with a new popup with logs. I copied the logs and pasted it into pastebin, maybe there's something in the logs you can find? https://pastebin.com/tV4tbAjn While this was happening, I was using 12.0.0

**Comment by Jaex** [comment] 2018-03-21 20:12
Pastebin is blocked in my country. But probably duplicate of #3189

**Closed by Jaex** 2018-03-21 20:12 UTC
