### ISSUE TITLE
Cursor is drawn at the wrong position on capture.

### ISSUE THREAD

**Issue by mzso** [ShareX/ShareX#5563] opened 2021-05-09 09:41 UTC
I just noticed this.
Never got this before. Not sure if it happened after I upgraded to a never version.
I have this recording settings:
`-y -rtbufsize 1300M -f dshow -framerate 60  -i video="screen-capture-recorder":audio="virtual-audio-capturer" -an -vcodec libx264rgb -tune zerolatency -preset superfast -crf 0 "$output$.mkv"`
Examples:
https://drive.google.com/file/d/1plX5DuuJkXtTKG7hv2pzV2DlLP44Si94/view?usp=sharing
also:
[2021-05-09_11-36-11.mp4.zip](https://github.com/ShareX/ShareX/files/6447243/2021-05-09_11-36-11.mp4.zip)

PS: I still get the borked "<filename>.mp4.mkv" as output. See attached recording.

**Comment by Jaex** [comment] 2021-05-09 09:42
Duplicate of #5562

**Closed by Jaex** 2021-05-09 09:42 UTC
Labels: Duplicate

**Comment by mzso** [comment] 2021-05-09 09:43
[**@Jaex**](https://github.com/Jaex) commented on [2021. máj. 9. 11:42 CEST](https://github.com/ShareX/ShareX/issues/5563#issuecomment-835767125 "2021-05-09T09:42:14Z - Replied by Github Reply Comments"):
> Duplicate of [#5562](https://github.com/ShareX/ShareX/issues/5562)

Whoops. I didn't notice it was already submitted somehow.
