### ISSUE TITLE
Got an issue with login to oneDrive

### ISSUE THREAD

**Issue by ferylukacs** [ShareX/ShareX#2392] opened 2017-03-28 11:26 UTC
I have a company one drive account, but has no "login.live" account associated with it, and when i try to set it up for a OneDrive Open Auth page, it redirects me to the live.login page instead of the one drive login page.

Is there a workaround? thanks

**Comment by vatterspun** [comment] 2017-05-27 20:31
This is probably hard for the dev to reproduce because he can't get a OneDrive for business account without actually purchasing it.

**Comment by Jaex** [comment] 2018-02-25 07:23
Duplicate of #1853

**Closed by Jaex** 2018-02-25 07:23 UTC
