### ISSUE TITLE
Can't upload screen to Imgur

### ISSUE THREAD

**Issue by klyushin** [ShareX/ShareX#3009] opened 2017-12-16 00:45 UTC
Imgur upload failed: (400) Forbidden

Message:
The remote server returned an error: (400) Bad Request.

Request URL:
https://api.imgur.com/3/image

Response:
{"data":{"error":{"code":403,"message":"Forbidden","type":"ImgurException","exception":[]},"request":"\/3\/image","method":"POST"},"success":false,"status":400}

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)

**Comment by Jaex** [comment] 2017-12-16 00:46
Duplicate of #2962

**Closed by Jaex** 2017-12-16 00:46 UTC
