### ISSUE TITLE
OneDrive for business uploads stopped working today

### ISSUE THREAD

**Issue by MANICX100** [ShareX/ShareX#5375] opened 2021-02-10 23:01 UTC
I have disconnected and reauthorised. No change
Full log below:

System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, JsonSerializerSettings settings)
   at ShareX.UploadersLib.FileUploaders.OneDrive.CreateShareableLink(String id, OneDriveLinkType linkType)
   at ShareX.UploadersLib.FileUploaders.OneDrive.Upload(Stream stream, String fileName)
   at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Int32 retry)

Error message:
The remote server returned an error: (400) Bad Request.

Request URL:
https://graph.microsoft.com/v1.0/me/drive/items/01JJVEJFQ5NXHKDFVSI5EZJCLYKGF5YLCW/createLink

Status code:
(400) Bad Request

Headers:
request-id: 12b9f492-07dc-411e-9236-09fe3c1c4d51
client-request-id: 12b9f492-07dc-411e-9236-09fe3c1c4d51
x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"UK South","Slice":"SliceC","Ring":"4","ScaleUnit":"003","RoleInstance":"AGSFE_IN_10"}}
Strict-Transport-Security: max-age=31536000
Content-Length: 283
Cache-Control: private
Content-Type: application/json
Date: Wed, 10 Feb 2021 22:59:35 GMT

Response text:
{
  "error": {
    "code": "invalidRequest",
    "message": "Invalid request",
    "innerError": {
      "date": "2021-02-10T22:59:36",
      "request-id": "12b9f492-07dc-411e-9236-09fe3c1c4d51",
      "client-request-id": "12b9f492-07dc-411e-9236-09fe3c1c4d51"
    }
  }
}

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.GetResponse(HttpMethod method, String url, Stream data, String contentType, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, Boolean allowNon2xxResponses)

System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, JsonSerializerSettings settings)
   at ShareX.UploadersLib.FileUploaders.OneDrive.CreateShareableLink(String id, OneDriveLinkType linkType)
   at ShareX.UploadersLib.FileUploaders.OneDrive.Upload(Stream stream, String fileName)
   at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Int32 retry)

Error message:
The remote server returned an error: (400) Bad Request.

Request URL:
https://graph.microsoft.com/v1.0/me/drive/items/01JJVEJFQ5NXHKDFVSI5EZJCLYKGF5YLCW/createLink

Status code:
(400) Bad Request

Headers:
request-id: a655334a-a51a-4358-80de-bd717d052992
client-request-id: a655334a-a51a-4358-80de-bd717d052992
x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"UK South","Slice":"SliceC","Ring":"4","ScaleUnit":"003","RoleInstance":"AGSFE_IN_10"}}
Strict-Transport-Security: max-age=31536000
Content-Length: 283
Cache-Control: private
Content-Type: application/json
Date: Wed, 10 Feb 2021 22:59:36 GMT

Response text:
{
  "error": {
    "code": "invalidRequest",
    "message": "Invalid request",
    "innerError": {
      "date": "2021-02-10T22:59:37",
      "request-id": "a655334a-a51a-4358-80de-bd717d052992",
      "client-request-id": "a655334a-a51a-4358-80de-bd717d052992"
    }
  }
}

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.GetResponse(HttpMethod method, String url, Stream data, String contentType, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, Boolean allowNon2xxResponses)

**Comment by drakonkat** [comment] 2021-02-22 13:35
I have the same error today

**Comment by tannaalok** [comment] 2021-05-05 21:23
Hi Team, any update on this issue ?

**Comment by tannaalok** [comment] 2021-05-06 15:01
@drakonkat @MANICX100 , was this issue fixed ?

**Comment by MANICX100** [comment] 2021-05-06 15:04
I switched to personal account as a necessary workaround.

6 May 2021 16:01:57 tannaalok ***@***.***>:

**Comment by AraHaan** [comment] 2021-05-06 15:04
I do not think it was.

Also Why is ShareX using Newtonsoft.Json when System.Text.Json is 100% *better* and less memory leaky?

**Comment by MANICX100** [comment] 2021-05-06 15:19
> I do not think it was.
> 
> Also Why is ShareX using Newtonsoft.Json when System.Text.Json is 100% _better_ and less memory leaky?

It is likely something as simple as Newtonsoft being the top result on NuGet for JSON. :)

**Comment by tannaalok** [comment] 2021-05-06 16:49
It was working for us till last week, something changed this week. 
@Jaex @SupSuper

**Comment by SupSuper** [comment] 2021-05-06 23:28
Duplicate https://github.com/ShareX/ShareX/issues/5553

**Comment by AraHaan** [comment] 2021-05-06 23:39
Actually that one is duplicate of this one.

**Closed** 2021-05-08 07:54 UTC
