### ISSUE TITLE
Mouse cursor on video recordings is mis-aligned

### ISSUE THREAD

**Issue by aph3rson** [ShareX/ShareX#1329] opened 2016-02-15 17:15 UTC
This might be a problem with W10x64, or FFmpeg, but the mouse cursor is very off-alignment in the final output when recording a GIF of an area.

For example, check out [this GIFV](http://i.imgur.com/G7vFuGi.gifv), a bug report I was trying to capture. I was originally clicking on the green arrow, and right around the "l" in "Explanation."

**Comment by Jaex** [comment] 2016-02-15 22:33
Look like your issue fixed 23 hours ago:
http://trac.ffmpeg.org/ticket/5008

Not sure is it released in daily build, can you try downloading latest ffmpeg and test it?

**Comment by aph3rson** [comment] 2016-02-15 22:35
Would this have been applied to the most recent release?

I just downloaded FFmpeg through ShareX this morning before capturing this, hence why I ask.

**Comment by Jaex** [comment] 2016-02-15 22:36
I don't know, I don't work in ffmpeg project.

**Comment by aph3rson** [comment] 2016-02-15 22:41
Just checked, looks like the patches haven't been put in to a new build, so I can't check it just yet.

I'll check in a few days when the newest build posts.

**Comment by Jaex** [comment] 2016-02-16 00:16
Yes new build not released yet:

Latest Zeranoe FFmpeg Build Version: git-588e2e3 (2016-02-13)

**Comment by Jaex** [comment] 2016-02-17 10:46
New build released can you try it?

**Comment by XavierBoubert** [comment] 2016-02-19 12:38
Don't works for me with the last FFmpeg version.

**Comment by XavierBoubert** [comment] 2016-02-19 12:44
The problem happends because your Windows UI size is bigger in your parameters. For example, in a Surface Pro 3, Windows 10 is by default configured to use 150% bigger UI. (Right click on your desktop, "Display parameters")

**Closed** 2016-03-01 11:43 UTC
Labels: Bug

**Comment by aph3rson** [comment] 2016-03-01 15:30
Is the bug concerning ui size with ffmpeg or ShareX?

**Comment by mohd-akram** [comment] 2016-04-29 13:21
This is still happening with the latest FFmpeg.

**Comment by varadins** [comment] 2016-08-01 13:39
This is still occurring on latest ffmpeg.  Win10x64

**Comment by Jaex** [comment] 2016-08-01 17:37
I can't fix ffmpeg issue.

**Comment by Jaex** [comment] 2018-01-26 16:35
https://github.com/FFmpeg/FFmpeg/commit/43e510d66887fe665b2c736be6ff842418f411c6

Maybe this time it is fixed in latest FFmpeg build?

**Comment by hafeild** [comment] 2018-02-21 02:35
I was able to correct this in Windows 10 on my Surface Pro 4 by changing the compatibility settings on the ffmpeg executable -- see the instructions here: https://github.com/rdp/screen-capture-recorder-to-video-windows-free/issues/56

I used this successfully to record at 175% scaling without any issues in mouse alignment.

**Comment by Jaex** [comment] 2018-03-27 10:23
We were using 7z latest release link of FFmpeg and looks like it was not updated for long months. Now latest ShareX version using zip latest release link to download it. So is anyone who had this issue can download FFmpeg using ShareX and check is cursor issue was fixed by that commit?

**Comment by RowanG1** [comment] 2018-03-27 23:01
I solved problem on Windows 10 by changing the pointer settings (color and size) to default.

**Comment by Goshik92** [comment] 2018-04-03 13:49
If you use screen-capture-recorder as your video source, you need to turn on "override high DPI scaling" and choose "Application" mode for ShareX.exe not for ffmpeg. I recorded a GIF to show how it's done: https://i.imgur.com/ew0vXho.gifv

**Comment by Quailsnap** [comment] 2019-04-09 23:19
Option does not exist for me. 
Win10 1803 17134.677

**Comment by lasselauch** [comment] 2020-02-25 11:56
> 
> 
> If you use screen-capture-recorder as your video source, you need to turn on "override high DPI scaling" and choose "Application" mode for ShareX.exe not for ffmpeg. I recorded a GIF to show how it's done (don't forget to restart ShareX after changing the setting): https://i.imgur.com/ew0vXho.gifv

Thank you! That fixed the issue for me.
Win10 1903 18362.657

**Comment by JakubKoralewski** [comment] 2020-05-22 08:43
> Option does not exist for me.
> Win10 1803 17134.677

@Quailsnap It's not in the same place but I was able to find it finally. My Windows is in Polish :confused:

![image](https://user-images.githubusercontent.com/43069023/82649053-e8606100-9c18-11ea-8c53-4e512c002bdc.png)

**Comment by dylanh724** [comment] 2020-06-21 10:16
🤔 Does the latest version fix this issue?

**Comment by dylanh724** [comment] 2020-06-21 10:16
🤔 Hmm, this is still an issue... or is this pending a new update? When would the next update possibly be released?

**Comment by ArunEdathadan** [comment] 2020-06-21 23:11
This issue is still here

**Comment by mruac** [comment] 2020-07-01 03:38
> > Option does not exist for me.
> > Win10 1803 17134.677
> 
> @Quailsnap It's not in the same place but I was able to find it finally. My Windows is in Polish 😕
> 
> ![image](https://user-images.githubusercontent.com/43069023/82649053-e8606100-9c18-11ea-8c53-4e512c002bdc.png)

Thanks for this! This fixed the issue for me.
For English steps,
1. Right click ShareX.exe > Properties
2. Compatibility > Change settings for all users
3. Change high DPI settings
4. <img width="253" alt="dllhost_mfPnDlRWRq" src="https://user-images.githubusercontent.com/19784752/86200453-d967b980-bb9b-11ea-807e-43524158e279.png">

**Comment by araRina** [comment] 2020-07-17 00:38
> For English steps,
> 
>     1. Right click ShareX.exe > Properties
> 
>     2. Compatibility > Change settings for all users
> 
>     3. Change high DPI settings
> 
>     4. <img alt="dllhost_mfPnDlRWRq" width="253" src="https://user-images.githubusercontent.com/19784752/86200453-d967b980-bb9b-11ea-807e-43524158e279.png">

All you need to edit is ffmpeg.exe, as it is not a ShareX problem. You can find ffmpeg.exe in your ShareX folder\Tools\ffmpeg.exe. If you follow the above steps from the post above this one, it fixes the cursor issue.

**Comment by AzzyC** [comment] 2021-02-10 19:07
Thank you for the solution: https://user-images.githubusercontent.com/36119634/107558416-a5914f80-6bd2-11eb-9414-f02cf46cc190.mp4
Now I need to try and find a way to make this change from command line

**Comment by wojnarw** [comment] 2021-04-10 00:56
> > For English steps,
> > 
> > 1. Right click ShareX.exe > Properties
> > 2. Compatibility > Change settings for all users
> > 3. Change high DPI settings
> > 4. <img alt="dllhost_mfPnDlRWRq" width="253" src="https://user-images.githubusercontent.com/19784752/86200453-d967b980-bb9b-11ea-807e-43524158e279.png">
> 
> All you need to edit is ffmpeg.exe, as it is not a ShareX problem. You can find ffmpeg.exe in your ShareX folder\Tools\ffmpeg.exe. If you follow the above steps from the post above this one, it fixes the cursor issue.

This is in your Documents folder on Windows, not in main program folder. And I can confirm it works.
C:\Users\user\Documents\ShareX\Tools

**Comment by L1Q** [comment] 2021-10-30 00:15
Using "GDI grab" video source proved to fix this for a user today. Please update FFmpeg and try it for yourself.

**Comment by KingZee** [comment] 2022-07-05 02:29
> Using "GDI grab" video source proved to fix this for a user today. Please update FFmpeg and try it for yourself.

This didn't work
neither did using screen-capture-recorder
I restarted sharex/restarted my computer

**Comment by Jaex** [comment] 2022-09-13 04:20
I figured recently that I could embed manifest file which contains `dpiAware` to ffmpeg.exe, that way it will be similar to that "Properties" method you guys were doing.

For next ShareX version I include ffmpeg.exe built-in, that way everyone can get this manifest patched ffmpeg.exe directly without require additional download. It is currently available in [dev build](https://getsharex.com/docs/dev-builds), would you download and test it?

**Comment by CrazyCoder** [comment] 2022-09-14 19:39
403 forbidden for the dev build:

![](https://i.imgur.com/GrYzhxC.png)

**Comment by nhan000** [comment] 2023-06-04 22:05
1. No ffmpeg.exe in C:\Users\user\Documents\ShareX\Tools in both the Windows Store version and the Installer downloaded from the website.
2. The fix Xshare.exe>compatibility>override high DPI scaling > application doesn't work for me on Windows 11.
