### ISSUE TITLE
Pausing a Screen Recording

### ISSUE THREAD

**Issue by ddouglas** [ShareX/ShareX#4011] opened 2019-03-09 17:50 UTC
I don't understand why these issues keep getting closed and called duplicates of a closed issue. This is clearly a highly requested feature and it is obvious from google searches that people have found a way to make it work. It is the one those features that would round out this application and make it one of the go to options for screen recording. Is there any possibility of this option ever being added? There are many on this platform that I am sure would support any endeavors by the creators to pursue this feature

**Comment by talanc** [comment] 2019-03-13 22:41
My thoughts on it: https://github.com/ShareX/ShareX/issues/205#issuecomment-472634252

**Comment by Jaex** [comment] 2019-03-14 06:09
Duplicate of #205

**Closed by Jaex** 2019-03-14 06:09 UTC
