### ISSUE TITLE
Upload error

### ISSUE THREAD

**Issue by AidaNightcore** [ShareX/ShareX#5187] opened 2020-11-11 09:26 UTC
Hey, I got this issue today, any way I can fix it? 

System.NullReferenceException: Object reference not set to an instance of an object.
   at ShareX.UploadersLib.ImageUploaders.Imgur.ParseError(ImgurResponse response)
   at ShareX.UploadersLib.ImageUploaders.Imgur.InternalUpload(Stream stream, String fileName, Boolean refreshTokenOnError)
   at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Int32 retry)

Error message:
The remote server returned an error: (500) Internal Server Error.

Request URL:
https://api.imgur.com/3/upload

Status code:
(500) Internal Server Error

Headers:
Connection: close
Imgur-Media-Type: imgur.v1; param=full; format=json
Content-Length: 102
Content-Type: application/vnd.imgur.v1+json
Date: Wed, 11 Nov 2020 09:09:42 GMT

Response text:
{"errors":[{"id":"","code":"500","status":"Internal Server Error","detail":"Internal Server Error"}]}

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)

System.NullReferenceException: Object reference not set to an instance of an object.
   at ShareX.UploadersLib.ImageUploaders.Imgur.ParseError(ImgurResponse response)
   at ShareX.UploadersLib.ImageUploaders.Imgur.InternalUpload(Stream stream, String fileName, Boolean refreshTokenOnError)
   at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Int32 retry)

Error message:
The remote server returned an error: (500) Internal Server Error.

Request URL:
https://api.imgur.com/3/upload

Status code:
(500) Internal Server Error

Headers:
Connection: close
Imgur-Media-Type: imgur.v1; param=full; format=json
Content-Length: 102
Content-Type: application/vnd.imgur.v1+json
Date: Wed, 11 Nov 2020 09:09:45 GMT

Response text:
{"errors":[{"id":"","code":"500","status":"Internal Server Error","detail":"Internal Server Error"}]}

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, HttpMethod method, String contentType, String relatedData)

**Comment by Jaex** [comment] 2020-11-11 09:27
Duplicate of #5186

**Closed by Jaex** 2020-11-11 09:27 UTC
