### ISSUE TITLE
Crash on windows 10 on open of captured GIF (NullReferenceException)

### ISSUE THREAD

**Issue by kell18** [ShareX/ShareX#4483] opened 2019-11-10 15:17 UTC
Here is the stacktrace 
System.NullReferenceException: Object reference not set to an instance of an object.
   at ShareX.HelpersLib.MyPictureBox.LoadImage(Image img)
   at ShareX.HelpersLib.ImageViewer.InitializeComponent()
   at ShareX.HelpersLib.ImageViewer..ctor(Image image)
   at ShareX.HelpersLib.ImageViewer.ShowImage(String filepath)
   at ShareX.TaskThumbnailPanel.PbThumbnail_MouseClick(Object sender, MouseEventArgs e)
   at System.Windows.Forms.Control.OnMouseClick(MouseEventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

ShareX 13.0.1 (MicrosoftStore)

**Comment by Jaex** [comment] 2019-11-22 09:23
Duplicate of #4303

**Closed by Jaex** 2019-11-22 09:23 UTC
