### ISSUE TITLE
Upload text to Hastebin Error

### ISSUE THREAD

**Issue by kimpeek** [ShareX/ShareX#3256] opened 2018-03-27 21:22 UTC
## System:
OS: Windows 7 Professional
Antivirus: Disabled for replicating this bug
Version: ShareX 12.1.1
Build: Release

## Settings:
After upload task: Copy URL to clipboard
Text Uploader destination: Hastebin

## Replication:
Method 1: Debug > Test text upload
Method 2: Copy text > Hotkey (Ctrl + Insert) > Upload

## Expected Result:
Upload text to hastebin and copy url to clipboard

## Actual Result:
Sharex Icon changes to `99` to indicate uploading progress is almost complete
Error Popup notification is created as seen [here](https://i.imgur.com/YmK0vYH.png)

## Exception:
```
2018-03-27 16:07:38.654 - Exception:
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at ShareX.UploadersLib.TextUploaders.Hastebin.UploadText(String text, String fileName)
   at ShareX.UploadersLib.TextUploader.Upload(Stream stream, String fileName)
   at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Int32 retry)
```

## Log:
https://hastebin.com/zabusixama.txt

I love Sharex and hope the bug report is helpful! Thanks for your hard work :)

**Comment by kimpeek** [comment] 2018-03-27 21:49
Tested this on my laptop which has ShareX 12.0 and the upload worked properly.

**Comment by campbeb** [comment] 2018-03-27 22:51
The problem is that the first computer you used was trying to upload to http://hastebin.com, but that site returns a 301 message and redirects to https://hastebin.com
For some reason, some installations (including mine) have a custom domain set by default for Hastebin. Removing this or changing it to https://hastebin.com will fix your problem.

![hastebin](https://user-images.githubusercontent.com/1089399/37999186-b429dcc6-31ef-11e8-8a00-1875f0097095.png)

(Thanks for the log file)

**Comment by kimpeek** [comment] 2018-03-27 23:04
That fixed it. Thank you for the help.

**Comment by Jaex** [comment] 2018-04-06 07:59
Duplicate of #2185

**Closed by Jaex** 2018-04-06 07:59 UTC
