### ISSUE TITLE
KB4524100 FTPS issues

### ISSUE THREAD

**Issue by TNTUP** [ShareX/ShareX#4421] opened 2019-10-12 09:43 UTC
I might be the first having that issue, I've noticed 2 of my computers has the KB4524100 installed (https://support.microsoft.com/en-ca/help/4524100/oct-8-2019-kb4524100-cumulative-update-for-net-framework) denying me uploading screenshots on my Windows Server 2016 running FileZilla Server. FTP over TLS is enabled and PROT P is enabled, but never required me to specify a client certificate?

Because, on my main computer which this KB isn't active yet (didn't reboot) can upload screenshots on my server but those who has the KB installed and active can't. 

Not ShareX fault, possibly with FluentFTP https://github.com/robinrodricks/FluentFTP/issues/347 but disabling the option "Require TLS session resumption on data connection..." isn't recommended. In the meantime, I can uninstall that KB and maybe reinstall later. Someone else on discord reported that "exact" issue by Expression93:

`I did not, mind linking me? I'll happily try it tomorrow. I've also noticed I had a couple windows updates install recently that affected .NET - For now I've resorted back to using FTP. `

Edit: Somehow October 2019 Cumulative update could cause this? On several PC I own some has different KBs

**Comment by Express93** [comment] 2019-10-12 13:39
I can confirm that KB4524100 is linked to KB4522738, in my case I have 738 not 100. I tried removing 738 and restarting, my issue persisted, I also tried installing 12.4.1 and still the issue persisted.

It is worth noting that https://github.com/robinrodricks/FluentFTP/issues/311 more precisely describes my situation, and I believe @TNTUP also.

**Comment by pclov3r** [comment] 2019-10-13 04:52
Seems the same ordeal here as well. After installing KB4522738 I can't use FTPS anymore. It's URL is empty error or this:

`System.IO.IOException: Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.IO.BufferedStream.Write(Byte[] array, Int32 offset, Int32 count)
   at System.Net.Security._SslStream.StartWriting(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security._SslStream.ProcessWrite(Byte[] buffer, Int32 offset, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at FluentFTP.FtpSocketStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at FluentFTP.FtpDataStream.Write(Byte[] buffer, Int32 offset, Int32 count)
   at ShareX.UploadersLib.Uploader.TransferData(Stream dataStream, Stream requestStream, Int64 dataPosition, Int64 dataLength)
   at ShareX.UploadersLib.FileUploaders.FTP.UploadData2(Stream localStream, String remotePath)
   at ShareX.UploadersLib.FileUploaders.FTP.UploadData(Stream localStream, String remotePath)
   at ShareX.UploadersLib.FileUploaders.FTP.Upload(Stream stream, String fileName)
   at ShareX.WorkerTask.UploadData(IGenericUploaderService service, Stream stream, String fileName)
   at ShareX.WorkerTask.DoUpload(Int32 retry)`

**Comment by thunderysteak** [comment] 2019-10-13 12:24
Can confirm that after installing KB4522738 FTPS no longer works. 
Generates `System.IO.IOException: Unable to write data to the transport connection: An existing connection was forcibly closed by the remote host.` and for strange reason generates `URL is empty.` errors as well.
Pureftp shows the client complete a TLS connection and log in and then dropping the connection.

**Comment by pclov3r** [comment] 2019-10-16 03:12
Anything new on this? getting annoying.

**Comment by pclov3r** [comment] 2019-10-25 14:19
I noticed Cannot fix was added to the issue. 

Does that mean FTPS support is being dropped?

**Comment by Jaex** [comment] 2019-10-25 14:26
I can't fix the issue because it is to do with FTP(S) library we are using.

**Comment by TNTUP** [comment] 2019-10-25 23:10
Shall I close the issue or keep it open as its not ShareX fault, but the FTP library is. I've disabled the session resumption to keep screenshotting xD

**Comment by pclov3r** [comment] 2019-11-01 05:16
I don't have time to look into this right now but i saw this https://www.bleepingcomputer.com/news/microsoft/microsoft-shares-solutions-for-windows-tls-failures-timeouts/

Anybody willing to try?

**Comment by TNTUP** [comment] 2019-11-01 08:05
@pclov3r Good catch! Though nothing tells me where to enable EMS (or else I'm lazy/blind?). By reading the article, I see there's a regedit to add if we disabled EMS, but I never disabled nor enabled EMS when I installed Windows Server 2016 (and on my PCs Windows 10). 

Does it means EMS is disabled by DEFAULT and I need to add those entries? One for the server, 5-10 on clients each if I'm right?

**Closed** 2019-11-22 14:15 UTC
Labels: Cannot fix
