### ISSUE TITLE
win10 could not capture bottom 58px hight filed , or could not annotate it 

### ISSUE THREAD

**Issue by snsnsjsn** [ShareX/ShareX#3168] opened 2018-02-26 10:20 UTC
hi , thanks for this great tool to capture screen , and annotate , but i found there is 58px bottom filed could not been marked or annotated 

just like this 

and i check all configuration could find solution

![image](https://user-images.githubusercontent.com/11435527/36665151-be015d8a-1b21-11e8-8584-fc3fb1fc9bc0.png)

**Comment by Jaex** [comment] 2018-02-26 10:22
Duplicate of #1338

**Closed by Jaex** 2018-02-26 10:22 UTC
