### ISSUE TITLE
Feature request: add "pause" button to screen recording

### ISSUE THREAD

**Issue by rcoenen** [ShareX/ShareX#6264] opened 2022-05-20 17:21 UTC
In addition to the "Stop" and "Abort" buttons while recording, add a "Pause"/"Resume" button.

**Comment by spunkerman** [comment] 2022-05-24 09:28
Duplicate of #205

**Comment by iahmedsheraz** [comment] 2022-06-21 11:04
Really need this button, all other works are just awesome. 
Thanks developers

**Comment by chenyjay** [comment] 2022-07-10 08:04
Yes, We really need this function.

**Comment by MRefaie83** [comment] 2022-08-17 08:52
really need it.

**Closed** 2022-09-03 17:22 UTC
Labels: Duplicate
