### ISSUE TITLE
ShareX 12.0 Portable, Losing watermark setting, watermark "Import"->"From file..." not working

### ISSUE THREAD

**Issue by MQAdmin007** [ShareX/ShareX#2970] opened 2017-12-02 15:25 UTC
Using ShareX since v10 through all releases, always portable.
Downloaded new v12.0, copied "ShareX" configuration files folder from the previous version.
Unlike earlier versions, watermark timestamp setting I configured in v10 got lost, replaced by default "getsharex.com" watermark instead. 

Tried to import DateTimeWatermark.json I've created and exported to file earlier, 
but **"Import"->"From file..."** has no effect.. not a blip, nothing. 

It looks like a bug. DateTimeWatermark.json below: 

-----------------------------------------------------------------------
[
  {
    "$type": "ShareX.ImageEffectsLib.Canvas, ShareX.ImageEffectsLib",
    "Margin": "0, 0, 0, 30",
    "Enabled": false
  },
  {
    "$type": "ShareX.ImageEffectsLib.DrawText, ShareX.ImageEffectsLib",
    "Placement": "BottomRight",
    "Offset": "0, 0",
    "AutoHide": true,
    "Text": "%y-%mo-%d %h:%mi%pm",
    "TextFont": "Consolas, 9.75pt, style=Italic",
    "TextColor": "145, 147, 147",
    "DrawTextShadow": false,
    "TextShadowColor": "85, 83, 83",
    "TextShadowOffset": "-1, -1",
    "CornerRadius": 4,
    "BackgroundPadding": 5,
    "DrawBorder": false,
    "BorderColor": "95, 94, 94",
    "DrawBackground": true,
    "BackgroundColor": "236, 249, 253",
    "UseGradient": false,
    "GradientType": "Vertical",
    "BackgroundColor2": "209, 239, 248",
    "UseCustomGradient": true,
    "Gradient": {
      "Type": "Vertical",
      "Colors": [
        {
          "Color": "252, 252, 252",
          "Location": 0.0
        },
        {
          "Color": "235, 241, 253",
          "Location": 50.0
        },
        {
          "Color": "193, 215, 247",
          "Location": 50.0
        },
        {
          "Color": "253, 253, 254",
          "Location": 100.0
        }
      ]
    },
    "Enabled": true
  }
]

**Comment by Jaex** [comment] 2017-12-02 18:19
Duplicate of #2964

**Closed by Jaex** 2017-12-02 18:19 UTC
