### ISSUE TITLE
Retain last used location

### ISSUE THREAD

**Issue by Karbust** [ShareX/ShareX#3879] opened 2019-01-12 23:38 UTC
Hello,

Depending on what I'm doing I always save screenshots to a different folder, but I don't seem to be able to "memorize" the last used location, it always goes either to the default or the costume folder, never the last used. Sometimes I capture a few screenshots and save on a certain folder for a certain job and I have to keep going to that folder.

I found a few issues already open, but none solved my problem.

Thanks

**Comment by Jaex** [comment] 2019-01-12 23:39
Duplicate of #3791

**Closed by Jaex** 2019-01-12 23:39 UTC

**Comment by Karbust** [comment] 2019-01-12 23:44
@Jaex I read that post, but it doesn't work for me... I'm using steam's versions, it updates itself automatically...

**Comment by Jaex** [comment] 2019-01-12 23:49
It didn't release yet.

**Comment by Karbust** [comment] 2019-01-13 00:15
Oh, ok... Do you have a release date yet?

**Comment by Jaex** [comment] 2019-01-13 00:16
No but you can use it with dev builds: https://getsharex.com/docs/dev-builds

**Comment by Karbust** [comment] 2019-01-13 00:18
No such option...

https://i.imgur.com/bMZjxik.png
