### ISSUE TITLE
[Feature request] Cut new file to clipboard

### ISSUE THREAD

**Issue by christiandull** [ShareX/ShareX#4841] opened 2020-05-30 09:07 UTC
Need "Cut file to clipboard" option:

![69324893-9038aa00-0c49-11ea-9507-f1c6b61dcfc5 (1)](https://user-images.githubusercontent.com/51074719/83324474-c5136280-a265-11ea-91be-19fa1d82e2c1.png)

This should replace click on file and press ctrl+x.

**Comment by Jaex** [comment] 2020-05-30 09:44
Duplicate of #4494

**Closed by Jaex** 2020-05-30 09:44 UTC
