### ISSUE TITLE
Change hotkey for copying image in the editor (Ctrl+Shift+C) to standard (Ctrl+C)

### ISSUE THREAD

**Issue by dkarelov** [ShareX/ShareX#7260] opened 2024-02-05 23:48 UTC
Why standard shortcut in every other app (Ctrl+C) that copies the contents to the clipboard (including standard Snipping Tool) has been changed??
This is soooo inconvenient that only this little thing prevents me from migrating to this app, as I always get it wrong. 
For some unknow reason Ctrl+C copies COORDINATES of the cursor. Who ever needs this??
At least provide an opportunity to change this crucial hotkey please!

**Comment by Jaex** [comment] 2024-02-06 08:47
Duplicate of #3495

**Closed by Jaex** 2024-02-06 08:47 UTC
