### ISSUE TITLE
Request: capture mouse clicks and keyboard shortcuts

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [ShareX/ShareX#4490] opened 2019-11-17 09:30 UTC
Currently it only allows to capture the mouse cursor, but doesn't show that we actually click anywhere.
Same goes for keyboard. It shows the result of what we type, but not the actual keyboard strokes.

For mouse, it can have various options:
1. Color for each type of mouse button (left click, right click, wheel click, others...).
2. Have checkbox to show text somewhere about which mouse button was clicked (because whoever watches the video might not understand what the colors mean).

For keyboard, we can have:
1. Have combobox: Show nothing, always show text of what was pressed, or show only if it's a special shortcut (like CTRL+C) . 

The text configurations should be the same for both of those, to make it easier to find. I suggest at the bottom right as default, with some color and outline (to have best chance of being readable).
Also by default the text size should be relatively small.

Another possible option for the position of the text is near the mouse cursor in case it's a mouse click event, and near the keyboard caret in case it's a keyboard event.

**Comment by Jaex** [comment] 2019-11-17 15:40
Duplicate of #1499

**Closed by Jaex** 2019-11-17 15:40 UTC

**Comment by AndroidDeveloperLB** [comment] 2019-11-17 15:54
@Jaex Seems it's closed, but why?
It says it's impossible, but I've seen video capturing tools that do capture the mouse and the keyboard. 
How come ?
