### ISSUE TITLE
can't undo cut-out or crop actions in image editor

### ISSUE THREAD

**Issue by andaluspc** [ShareX/ShareX#6902] opened 2023-05-28 07:56 UTC
I think the title is self explanatory.
If I do cut-out or crop of an image, I can't reverse that with ctrl+z.
This also applies to some other actions like flipping the image. I can't undo that with ctrl+z.

I would also comment on having no ctrl+y action available (a re-do action) but that has its own issue (# 6792) as I see.

**Comment by Jaex** [comment] 2023-12-27 05:38
Duplicate of #4079

**Closed by Jaex** 2023-12-27 05:38 UTC
