### ISSUE TITLE
Text Uploader (privatebin.net)

### ISSUE THREAD

**Issue by silentshotghost** [ShareX/ShareX#4711] opened 2020-03-30 09:54 UTC
text uploader for privatebin.net would be nice or even these [subdomains](https://github.com/PrivateBin/PrivateBin/wiki/PrivateBin-Instances-Directory)

**Comment by Jaex** [comment] 2020-03-30 09:57
Duplicate of #2067

**Closed by Jaex** 2020-03-30 09:57 UTC
