### ISSUE TITLE
ShareX Plugin API

### ISSUE THREAD

**Issue by Bluscream** [ShareX/ShareX#4455] opened 2019-10-25 21:02 UTC
Have you ever thought about a plugin API @Jaex?

Some .NET dll that can be placed in <ShareX\Plugins\> and provides the ability to add features that you consider "not useful to the masses" or "too niche"

**Comment by iMGDE** [comment] 2019-11-11 13:45
Like that one

**Comment by canpolat** [comment] 2019-11-12 10:46
Sounds like a duplicate of #1024

**Closed** 2019-11-12 10:59 UTC
Labels: Duplicate
