### ISSUE TITLE
Imgur upload failed: (400) Forbidden

### ISSUE THREAD

**Issue by West456** [ShareX/ShareX#3060] opened 2018-01-06 16:48 UTC
Uploading to Imgur doesnt work, getting always " Imgur upload failed: (400) Forbidden".

**Comment by SC2Mitch** [comment] 2018-01-06 16:55
Why is this a ShareX issue? Take it up with Imgur to fix their fucking awful servers.

**Comment by Jaex** [comment] 2018-01-06 23:49
Duplicate of #2962

**Closed** 2018-01-06 23:50 UTC
Labels: Duplicate
