### ISSUE TITLE
Chinese OCR adding spaces between every single character

### ISSUE THREAD

**Issue by GTRanger** [ShareX/ShareX#6352] opened 2022-07-10 04:25 UTC
#### Expected Behavior
Chinese OCR will happen normally without any extra spaces

#### Actual Behavior
OCR introduces spaces between each Chinese character

#### Steps to Reproduce
1. Open ShareX
2. Start an OCR capture
3. Select Chinese text
4. Observe the output

#### Meta
**ShareX Version**: 14.0.1
**OS**: Windows 10 Pro

**Comment by Jaex** [comment] 2022-07-10 04:27
Duplicate of #6322

**Closed by Jaex** 2022-07-10 04:27 UTC
Labels: Duplicate
