### ISSUE TITLE
The ability to search for a photo in all images (screenshots) can be an interesting and useful feature that I did not see in sharex.

### ISSUE THREAD

**Issue by NabiKAZ** [ShareX/ShareX#6774] opened 2023-02-24 01:31 UTC
The ability to search for a photo in all images (screenshots) can be an interesting and useful feature that I did not see in sharex.

**Comment by teauxfu** [comment] 2023-03-05 02:31
duplicate of #6773

**Closed** 2023-04-18 01:48 UTC
