### ISSUE TITLE
Google Photos upload doesn't work - Album list is empty

### ISSUE THREAD

**Issue by roikedem** [ShareX/ShareX#3956] opened 2019-02-18 13:41 UTC
Google Photos stopped working. after trying to re-configure it, login was successful, but album list remains empty. The "Refresh album list" button doesn't change anything.

**Comment by lucario** [comment] 2019-02-18 16:51
Download the dev build https://getsharex.com/docs/dev-builds

**Comment by lucario** [comment] 2019-02-18 16:52
Duplicate of #3884

**Closed** 2019-02-18 22:54 UTC
Labels: Duplicate
