### ISSUE TITLE
Simple video edit feature to trim the video after editing

### ISSUE THREAD

**Issue by PESER** [ShareX/ShareX#3082] opened 2018-01-18 22:23 UTC
That would make it a lot easier to record your screen and then cut the bits you don't want. Even just cutting either from the start and an end. Doesn't have to edit few points at once.

**Comment by Jaex** [comment] 2018-01-18 23:29
Duplicate of #2278

**Closed by Jaex** 2018-01-18 23:29 UTC

**Comment by mark325hr** [comment] 2024-09-20 11:39
srhre[h](fiverr)

**Comment by mark325hr** [comment] 2024-09-20 11:41
<a href="https://www.w3schools.com">Visit W3Schools.com!</a>
