### ISSUE TITLE
After taking a screenshot: 'This feature will not work when "DisableUpload" option is enabled!'

### ISSUE THREAD

**Issue by MRVDH** [ShareX/ShareX#4661] opened 2020-03-11 14:28 UTC
I'm getting this popup everytime I take a screenshot since the last update, though I haven't changed any settings.

![image](https://user-images.githubusercontent.com/6686385/76427598-d0649980-63ac-11ea-8a71-4fac665ebfd6.png)

**Comment by Jaex** [comment] 2020-03-11 14:29
Duplicate of #4652

**Closed by Jaex** 2020-03-11 14:29 UTC
