### ISSUE TITLE
Can't capture fullscreen

### ISSUE THREAD

**Issue by dev2017001** [ShareX/ShareX#3133] opened 2018-02-09 04:32 UTC
<a href="https://imgur.com/Qivc36C"><img src="https://i.imgur.com/Qivc36C.jpg" title="source: imgur.com" /></a>

Capture region can't capture fullscreen.
How to fix this problem？

**Comment by Jaex** [comment] 2018-02-09 05:53
Duplicate of #1338

**Closed** 2018-02-09 05:53 UTC
Labels: Duplicate
