### ISSUE TITLE
Error while loading zip file (DropBox)

### ISSUE THREAD

**Issue by rdbox** [ShareX/ShareX#2836] opened 2017-10-09 10:59 UTC
```
Message:
The remote server returned an error: (409) Conflict.

Request URL:
https://api.dropboxapi.com/2/sharing/create_shared_link_with_settings

Response:
{"error_summary": "shared_link_already_exists/...", "error": {".tag": "shared_link_already_exists"}}

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.GetResponse(HttpMethod method, String url, Stream data, String contentType, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies)
```

**Comment by Jaex** [comment] 2017-10-09 18:56
Duplicate of #2805

**Closed** 2017-10-09 18:57 UTC
Labels: Duplicate
