### ISSUE TITLE
Cannot input diacritical character (Polish)

### ISSUE THREAD

**Issue by Rejerf** [ShareX/ShareX#5991] opened 2021-12-17 11:16 UTC
While using Text (Outline) I'm not able to input one of the Polish diacritical character (ą). The shortcut (Right Alt+a) selects entire text instead of inserting this intended character.

**Comment by Jaex** [comment] 2021-12-17 21:34
Duplicate of #5984

**Closed by Jaex** 2021-12-17 21:34 UTC
Labels: Duplicate
