### ISSUE TITLE
Saving or uploading image output is the previous screenshot.

### ISSUE THREAD

**Issue by Ian-Korob** [ShareX/ShareX#4506] opened 2019-11-30 01:58 UTC
When I take a screenshot with sharex, it does not save or upload the screenshot I just took. Instead of this, it saves/uploads the previous screenshot! This issue persists if I delete my screenshots folder. This only happens in game, I also can't record in game, so its difficult for me to capture this issue

**Comment by SpaceRangerMav** [comment] 2019-11-30 17:24
I am having this exact same problem. I have tried different capture settings and nothing has resolved it. Even if it is my first screenshot since turning on my pc it will have a random screen as the initial capture.

**Comment by Jaex** [comment] 2019-11-30 17:56
Duplicate of #848

**Closed by Jaex** 2019-11-30 17:56 UTC
