### ISSUE TITLE
Upload issue since 12.1.1

### ISSUE THREAD

**Issue by iKatt** [ShareX/ShareX#3245] opened 2018-03-26 07:46 UTC
My screen recording mp4 upload action no longer works and spits out this error after it finishes uploading.
![image](https://user-images.githubusercontent.com/10321978/37893154-e55e7128-3125-11e8-8707-b5cd67f9520c.png)
Don't know what other info I can provide unless asked.

**Comment by Jaex** [comment] 2018-03-26 07:58
Duplicate of #3239

**Closed** 2018-03-26 07:58 UTC
Labels: Duplicate
