### ISSUE TITLE
SUGGESTION: Something minor that makes me angry

### ISSUE THREAD

**Issue by F7Sammy** [ShareX/ShareX#7328] opened 2024-03-17 11:21 UTC
Hi! First of all, I love this tool, it makes my day so much easier, so thanks a lot.

Im using Imgur as img uploader. The problem that makes me uncomfortable is when I upload an image to watch it on a browser.

Always when the img is opened on the browser, I can see all the graphic environment of the website. Otherwise, this never
happened to me before. The imgs have always been uploaded as _"Open image in a new window"_.

**An example:**

This is what the tool does now: https://imgur.com/OcRKpR4

This was what I liked and what I'm looking for: https://i.imgur.com/OcRKpR4.png

The only difference is on the prefix of the url "i." and the extension ".png"

I've tried everything on the APP but I haven't been able to make this possible. Any suggestion? Is this from devs, or I can do something about it as a user.

_Sorry for my english, I'm not native._

**Comment by Jaex** [comment] 2024-03-17 11:24
Duplicate of #7311

**Closed by Jaex** 2024-03-17 11:24 UTC
