### ISSUE TITLE
Image editor annotation colors broken

### ISSUE THREAD

**Issue by derekantrican** [ShareX/ShareX#4430] opened 2019-10-15 22:21 UTC
Somehow I stumbled upon a bug that rendered all of my image editor annotation (rect, line, arrow, etc) colors transparent:

![screenshot](https://i.imgur.com/Hg9HnrH.gif)

You can even see in the image editor that I try to change colors but it doesn't work. Any suggestions?

Log here: https://pastebin.com/L5uMwQmv

**Comment by derekantrican** [comment] 2019-10-15 22:27
I tried "solid" (rect & ellipsis) shapes again. It seems to only be the outline color that is broken. The "fill" color works fine

**Comment by Jaex** [comment] 2019-10-15 22:53
Duplicate of #4418

**Closed by Jaex** 2019-10-15 22:53 UTC

**Comment by derekantrican** [comment] 2019-10-15 23:13
@Jaex This is not the same as that issue. That issue refers to the border size being accidentally set to 0. My border size is still set to 5:

![image](https://user-images.githubusercontent.com/1558019/66876454-b8582d80-ef66-11e9-8d64-7be997f18eab.png)

**Comment by Jaex** [comment] 2019-10-15 23:16
Your ss not shows border size option when line drawing tool is selected.

**Comment by DuncanLithgow** [comment] 2020-02-25 16:00
I seem to have the exact same issue. I can make filled shapes but the freehand/line/arrow all give me anchor nodes but no content.
