### ISSUE TITLE
Delayed Screenshot - Capturing Previous Request

### ISSUE THREAD

**Issue by SpaceRangerMav** [ShareX/ShareX#4507] opened 2019-11-30 21:43 UTC
Attempting to use during gameplay and when screenshot is attempted it takes a screenshot of something different for the window. When I try it a second time it ends up being what I originally requested. The function seems to be capturing delayed image.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Jaex** [comment] 2019-11-30 22:13
Duplicate of #4506

**Closed by Jaex** 2019-11-30 22:13 UTC
