### ISSUE TITLE
Suggestion - Right click to open image in Image Editor

### ISSUE THREAD

**Issue by frankroj** [ShareX/ShareX#4780] opened 2020-04-30 18:19 UTC
It would be nice if we could right click on an image and tell it to open the image in the ShareX Image Editor.

**Comment by Jaex** [comment] 2020-04-30 19:18
Duplicate of #4766

**Closed** 2020-04-30 19:19 UTC
Labels: Duplicate

**Comment by frankroj** [comment] 2020-04-30 20:16
So sorry for this one too. I looked and looked but couldn't find the option. Time to go get my eyes checked.
