### ISSUE TITLE
Images corrupted when uploaded to FTP server

### ISSUE THREAD

**Issue by notcammy** [ShareX/ShareX#3230] opened 2018-03-23 22:02 UTC
Since the new library is used in ShareX 12.1 images are corrupted when uploaded. Usually over half of the image is missing.

[Example](https://millie.me/data/scr/chrome_2018-03-23_23-01-33.png)

**Comment by sylveon** [comment] 2018-03-23 22:11
Would be fixed by #3225

**Comment by Jaex** [comment] 2018-03-24 00:49
Duplicate of #3224

**Closed by Jaex** 2018-03-24 00:49 UTC
Labels: Duplicate
