### ISSUE TITLE
imgur upload error

### ISSUE THREAD

**Issue by tilerthps** [ShareX/ShareX#3527] opened 2018-07-12 23:55 UTC
Message:
The remote server returned an error: (400) Bad Request.

Request URL:
https://api.imgur.com/3/image

Stack trace:
   at System.Net.HttpWebRequest.GetResponse()
   at ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)

**Comment by Jaex** [comment] 2018-07-13 00:03
Duplicate of #3526

**Closed by Jaex** 2018-07-13 00:03 UTC
