### ISSUE TITLE
Lock aspect ratio while dragging

### ISSUE THREAD

**Issue by madzadev** [ShareX/ShareX#5430] opened 2021-02-25 13:21 UTC
Currently, I'm using the ALT tab to get predefined resolution frames while dragging the area to be cropped.
Is there any way we can lock the aspect ratio while dragging? Something like holding Shift while dragging by the corner?
If it's currently not possible, it would be a very handy feature in the future...

**Comment by Jaex** [comment] 2021-02-25 19:29
Duplicate of #2996

**Closed by Jaex** 2021-02-25 19:29 UTC
