### ISSUE TITLE
Imgur upload error while authorized

### ISSUE THREAD

**Issue by DarkPreacher** [ShareX/ShareX#3171] opened 2018-03-01 16:58 UTC
Can't upload to Imgur while authorized, programm gives me following error:
```
Imgur upload failed: (400) Forbidden

Message:
Удаленный сервер возвратил ошибку: (400) Недопустимый запрос.

Request URL:
https://api.imgur.com/3/image

Response:
{"data":{"error":{"code":403,"message":"Forbidden","type":"ImgurException","exception":[]},"request":"\/3\/image","method":"POST"},"success":false,"status":400}

Stack trace:
   в System.Net.HttpWebRequest.GetResponse()
   в ShareX.UploadersLib.Uploader.SendRequestFile(String url, Stream data, String fileName, String fileFormName, Dictionary`2 args, NameValueCollection headers, CookieCollection cookies, ResponseType responseType, HttpMethod method, String contentType, String metadata)
```
If I switch to Anonymous — screenshots uploaded without any problem.
Am I doing something wrong?

**Comment by Jaex** [comment] 2018-03-01 16:59
Duplicate of #2962

**Closed by Jaex** 2018-03-01 16:59 UTC
