### ISSUE TITLE
Built-In Emoji for Annotations

### ISSUE THREAD

**Issue by gooddadmike** [ShareX/ShareX#5580] opened 2021-05-21 18:59 UTC
Any windows text box control can get the normal emojis. 
There has to be a simple way to enable the default system emoji as an annotation w/o adding them as an image library.

This rich text editor (and most dumb text editors) we are using right now can do it using `Win` + `+`

💪🤓👍👋🔋🤝❤🚗🥂🎓💯🧵🤜🤛⭐🤷‍♂️🎂🎉😜🆒🎓📚📚📋💰

_Originally posted by @gooddadmike in https://github.com/ShareX/ShareX/issues/4761#issuecomment-846175712_

**Comment by Jaex** [comment] 2021-05-22 07:52
Duplicate of #4761

**Closed by Jaex** 2021-05-22 07:52 UTC
