### ISSUE TITLE
This is what it copys to my clipboard

### ISSUE THREAD

**Issue by zahin45** [ShareX/ShareX#5531] opened 2021-04-21 23:18 UTC
`<script type="text/javascript" src="/aes.js" ></script><script>function toNumbers(d){var e=[];d.replace(/(..)/g,function(d){e.push(parseInt(d,16))});return e}function toHex(){for(var d=[],d=1==arguments.length&&arguments[0].constructor==Array?arguments[0]:arguments,e="",f=0;fd[f]?"0":"")+d[f].toString(16);return e.toLowerCase()}var a=toNumbers("f655ba9d09a112d4968c63579db590b4"),b=toNumbers("98344c2eee86c3994890592585b49f80"),c=toNumbers("e8e26ae8339000066f2b967cf1191143");document.cookie="__test="+toHex(slowAES.decrypt(c,2,a,b))+"; expires=Thu, 31-Dec-37 23:55:55 GMT; path=/"; location.href="https://lyrix.cf/up.php?embed=yes&embedColor=%23fc0303&embedMDY=yes&i=1";</script>This site requires Javascript to work, please enable Javascript in your browser or use a browser with Javascript support`

**Comment by Jaex** [comment] 2021-04-22 07:45
Duplicate of #5528

**Closed by Jaex** 2021-04-22 07:45 UTC
