### ISSUE TITLE
Changing Path Problem

### ISSUE THREAD

**Issue by Cavien** [ShareX/ShareX#4054] opened 2019-04-01 04:31 UTC
After changing the path in the application settings, the ShareX folder will still be generated in my document directory. If the ShareX folder is deleted, the changed path will be invalid.

**Comment by Jaex** [comment] 2019-04-01 12:09
Duplicate of https://github.com/ShareX/ShareX/issues/2799#issuecomment-332604994

**Closed by Jaex** 2019-04-01 12:09 UTC
