### ISSUE TITLE
Support for PrivateBin

### ISSUE THREAD

**Issue by KiraSokolov** [ShareX/ShareX#3947] opened 2019-02-11 07:02 UTC
It would be cool to see support for an PrivateBin environment.
or can you say to me, how can i add it myself?
Doc: https://github.com/PrivateBin/PrivateBin/wiki/API

**Comment by Jaex** [comment] 2019-02-11 14:02
Duplicate of #2067

**Closed by Jaex** 2019-02-11 14:02 UTC
