### ISSUE TITLE
Reopening #3549: "Can't move set the paths of ShareX personal folder."

### ISSUE THREAD

**Issue by nepphhh** [ShareX/ShareX#4724] opened 2020-04-06 03:23 UTC
You cannot completely remove the personal folder from your documents. See #3549.

**Comment by Jaex** [comment] 2020-04-06 10:44
Duplicate of #3549

**Closed by Jaex** 2020-04-06 10:44 UTC

**Comment by nepphhh** [comment] 2020-04-06 13:09
@Jaex If you're going to close this, will #3549 be reopened?
