### ISSUE TITLE
Screen recording does not record my cursor in the correct location

### ISSUE THREAD

**Issue by derekantrican** [ShareX/ShareX#4855] opened 2020-06-04 16:09 UTC
See this screen recording (made with ShareX): https://www.youtube.com/watch?v=IH4FPsisWUE

Notice how the recorded cursor is not in the location of the actual items being clicked on (where the cursor actually was)

**Comment by Jaex** [comment] 2020-06-04 16:14
Duplicate of #1329

**Closed by Jaex** 2020-06-04 16:14 UTC
Labels: Duplicate
