### ISSUE TITLE
Imgur uploading, direct link no longer working for the first viewing

### ISSUE THREAD

**Issue by MrWilza** [ShareX/ShareX#7327] opened 2024-03-17 10:55 UTC
When uploading an image to Imgur, using the "Use direct link" option, it used to work exactly as described. Now however, the first time you view the image it brings you to the full website view, instead of to the direct image. Subsequent views of the image work as before, bringing you just the image alone. It never used to work this way, seems like this is something Imgur have changed on their end, annoyingly. Perhaps some kind of workaround can be implemented to automatically open the image twice in order to circumvent this, if possible? Thanks :)

**Comment by Jaex** [comment] 2024-03-17 11:03
Imgur is a third-party hosting service that we utilize, and we are not the developers of Imgur. Unfortunately, this means that we are unable to address any issues related to the Imgur website or API. It is important to clarify that this issue began more than one week before our latest update release, indicating that it is not related to our update.

**Comment by Jaex** [comment] 2024-03-17 11:21
Duplicate of #7311

**Closed by Jaex** 2024-03-17 11:21 UTC
Labels: Invalid
