### ISSUE TITLE
When I use the shortcut key to open the image effect, I get an error.

### ISSUE THREAD

**Issue by lishige** [ShareX/ShareX#7727] opened 2024-12-25 13:14 UTC
![快捷键打开图像效果出错.gif](https://github.com/user-attachments/assets/1b6f34f6-6753-4d24-a54b-83f8540c8077)
version:16.1.4.431 Dev

**Comment by Jaex** [comment] 2024-12-28 07:42
Duplicate of #7669

**Closed by Jaex** 2024-12-28 07:42 UTC
Labels: Duplicate
