### ISSUE TITLE
middle-click tray icon doing wrong action

### ISSUE THREAD

**Issue by nr1995** [ShareX/ShareX#7484] opened 2024-06-06 09:50 UTC
Hi, noob here.
I've set middle-click on the tray icon to OCR,
but after dragging to select an area and releasing,
it's just taking a regular screenshot.
Any ideas?
On v16.1 on Steam.
N

**Comment by leonlarsson** [comment] 2024-06-16 12:02
Same. I have set the left click action to be what I want middle click to be

**Comment by JLiszt** [comment] 2024-06-16 20:36
Same here... middle click just seems to do the left click assignment. By the way, seems to happen only on Windows 11. On my widows 10 PC it works fine.

**Comment by nr1995** [comment] 2024-06-16 20:54
> Same here... middle click just seems to do the left click assignment. By the way, seems to happen only on Windows 11. On my widows 10 PC it works fine.

Yeah I don't know about Windows 10, but I'm on Windows 11 here.

**Comment by Jaex** [comment] 2024-06-16 23:04
Duplicate of #6791

**Closed by Jaex** 2024-06-16 23:04 UTC
