### ISSUE TITLE
how to rename an image you just took?

### ISSUE THREAD

**Issue by SolveAllProblemsRightNow** [ShareX/ShareX#4500] opened 2019-11-25 21:53 UTC
unanswered: https://github.com/ShareX/ShareX/issues/4443

if you cant let me know

**Comment by Jaex** [comment] 2019-11-25 22:23
Duplicate of #4443

**Closed by Jaex** 2019-11-25 22:23 UTC

**Comment by SolveAllProblemsRightNow** [comment] 2019-11-25 22:30
it's unanswered
