### ISSUE TITLE
Memory leak issue

### ISSUE THREAD

**Issue by sketchycrypt** [ShareX/ShareX#7375] opened 2024-03-31 14:09 UTC
As of yesterday, ShareX has been using an excessive amount of RAM : 
![image](https://github.com/ShareX/ShareX/assets/51757052/b2056e7c-1018-4dbb-adb9-ae7a096f9468)

Checking this log, this seems to be the main error

```
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Pipes.NamedPipeServerStream.Create(String fullPipeName, PipeDirection direction, Int32 maxNumberOfServerInstances, PipeTransmissionMode transmissionMode, PipeOptions options, Int32 inBufferSize, Int32 outBufferSize, PipeAccessRights rights, SECURITY_ATTRIBUTES secAttrs)
   at System.IO.Pipes.NamedPipeServerStream..ctor(String pipeName, PipeDirection direction, Int32 maxNumberOfServerInstances, PipeTransmissionMode transmissionMode, PipeOptions options, Int32 inBufferSize, Int32 outBufferSize, PipeSecurity pipeSecurity, HandleInheritability inheritability, PipeAccessRights additionalAccessRights)
   at System.IO.Pipes.NamedPipeServerStream..ctor(String pipeName, PipeDirection direction, Int32 maxNumberOfServerInstances, PipeTransmissionMode transmissionMode, PipeOptions options)
   at ShareX.HelpersLib.SingleInstanceManager.<ListenForConnectionsAsync>d__25.MoveNext()
2024-03-31 00:37:21.735 - Exception:
System.IO.IOException: All pipe instances are busy.
```

**Comment by Jaex** [comment] 2024-04-01 04:00
Duplicate of #7329

**Closed by Jaex** 2024-04-01 04:00 UTC
