### ISSUE TITLE
Can't start after install

### ISSUE THREAD

**Issue by crazygo** [ShareX/ShareX#4257] opened 2019-08-09 11:02 UTC
System.NullReferenceException: 
  ShareX.SettingManager.ApplicationConfigBackwardCompatibilityTasks()
   ShareX.SettingManager.LoadApplicationConfig()
   ShareX.SettingManager.LoadInitialSettings()
   ShareX.Program.Run()
   ShareX.Program.Main(String[] args)

ShareX 12.4.1 (Release)

**Comment by Jaex** [comment] 2019-08-09 18:08
Duplicate of #3976

**Closed by Jaex** 2019-08-09 18:08 UTC
