### ISSUE TITLE
Support Rebrandly API

### ISSUE THREAD

**Issue by abaustin1** [ShareX/ShareX#2990] opened 2017-12-10 04:22 UTC
Hello! I'd be willing to donate some BTC for the addition of this feature to ShareX.

I'd like the option for the Rebrandly URL shortener in destination settings. Their API docs are here: https://developers.rebrandly.com/

Thanks!

**Comment by Jaex** [comment] 2017-12-10 08:40
Duplicate of #2426

**Closed by Jaex** 2017-12-10 08:40 UTC
