### ISSUE TITLE
Save elements in the editor as a project, for later editing

### ISSUE THREAD

**Issue by rogeriodec** [ShareX/ShareX#4943] opened 2020-07-24 23:47 UTC
Currently, the editor only allows saving a final image. All elements (rectangles, text boxes) are lost.
Ideally, the Save As option would allow you to save a "project" file type, where I could later re-edit existing elements, just like any other image editor, like a PSD in Photoshop.

**Comment by Jaex** [comment] 2020-07-24 23:57
duplicate of #4921

**Closed by Jaex** 2020-07-24 23:57 UTC
