### ISSUE TITLE
Add option to highlight to darken rest of the screen.

### ISSUE THREAD

**Issue by Garviell** [ShareX/ShareX#3090] opened 2018-01-23 15:45 UTC
I find myself quite frequently wanting to bring attention an area in a screenshot in a visually pleasing manner by highlighting one thing while darkening others.

As of now the only way i have found to do this is to add four dark highlights around the objects which sort of works but also messes with the colors of the 'shaded' objects.
this is the best i can get with the current tools.  The way the highlight looks while dragged would be ideal.

![image](https://user-images.githubusercontent.com/5700653/35284957-05cef0b6-0054-11e8-8da4-d0ff8e42641f.png)

I suggest adding an option to highlight where you darken the entire screen and use the highlights as exclusion zones.  That way the above effect could be achieved with a single rectangle and the darkened areas wouldn't have the weird 'lighten' effect on them

**Comment by Jaex** [comment] 2018-01-24 00:51
Duplicate of #3041

**Closed by Jaex** 2018-01-24 00:51 UTC
