### ISSUE TITLE
When entering Screen region select 2nd monitor overlaps first partially (fresh install)

### ISSUE THREAD

**Issue by zerozapper** [ShareX/ShareX#5408] opened 2021-02-18 19:44 UTC
When entering capture mode, part of the 2nd montitor overlaps with the first, making it basically impossible to screenshot anything on the first monitor, this is a fresh install (both windows 10, and ShareX)

**Comment by TravitoDLM** [comment] 2021-06-04 13:02
I can corroborate this. I have a three-monitor setup, a WQHD (3440x1440) ultrawide flanked by two standard 1080p monitors. If I try to start a screen capture on the ultrawide, it does the above. I really don't have a good way of describing it in words so here's a couple screenshots I took with the default Win+PrintScreen key combo.

I can work around by clicking onto a different monitor and then doing a region capture, but my primary workflow is to quickly hit region capture, which I have set to multi-region mode, make my selection, annotate it, and then either copy / upload / save the screenshot using the post-capture menu. It is super, super frustrating to try and quickly take a screenshot and have the overlap issue occur. I've been resorting to Win+Shift+S for captures where I don't need to annotate and just need to quickly get an image onto the clipboard.

I am using ShareX 13.5 on Windows 10 LTSC build 1809
![Actual layout](https://user-images.githubusercontent.com/10532219/120805156-130f1600-c50b-11eb-8f8e-aaeb6315c2f8.jpg)
![Overlap Issue](https://user-images.githubusercontent.com/10532219/120805167-160a0680-c50b-11eb-8c43-2d30670a9596.png)

**Comment by awebre** [comment] 2021-08-11 18:49
I'm also having this issue. It appears that with multiple monitors the "primary" monitor is super imposed on any secondary monitors when Capture Region is triggered. I've attempted to go back several versions with fresh installs with no success. I don't remember seeing this until fairly recently, but was able to reproduce with 13.5, 13.4, and 13.0.

**Comment by Jaex** [comment] 2021-08-11 21:50
@awebre I saw people reporting similar issues so many times and in all of them it was to do with some software in their pc moving region capture window to another monitor automatically and breaking ShareX. You also saying it started recently, which proves something in your pc could be changed and now that thing sabotaging ShareX region capture window.

**Comment by TravitoDLM** [comment] 2021-08-13 18:39
> @awebre I saw people reporting similar issues so many times and in all of them it was to do with some software in their pc moving region capture window to another monitor automatically and breaking ShareX. You also saying it started recently, which proves something in your pc could be changed and now that thing sabotaging ShareX region capture window position.

This turned out to be the issue in my case! @awebre and @zerozapper: if you happen to use the windows PowerToys' FancyZones tool, be sure to exclude sharex.exe.

Thanks @Jaex!

**Comment by silversword411** [comment] 2021-08-30 17:46
Hopefully this will help others in the future if they come across this.

I too was having the problem, and in my case I use powerpro (a 25+ year old windows tool that allows mind boggling numbers of customization to your windows experience). One of those options is: "Force new windows on screen."

I think what sharex does when doing a region capture is: at the time you hit the hotkey for region capture it "duplicate all monitor contents" and creates a frameless new window (with a hidden title of "sharex - region capture") which overlays the visible data....allowing you to auto-crop using the square selection tool. Powerpro is seeing this "new window" and is forcing it to specific coordinates for it's top left corner. I'm sure people experiencing issues should look for utils interacting with window positions.

Adding "sharex*" to the exclude list fixed it for me

<img width="394" alt="pproexcludesharex" src="https://user-images.githubusercontent.com/13395348/131381828-0b16ddce-69dc-4c5f-b98c-a69aaf53a6ff.png">

**Comment by superuser7777** [comment] 2022-02-08 12:21
I'm experiencing the same phenomenon. I don't use Windows PowerToys.
Do you have a solution?
Is this a bug?

SharaeX latest
Win10 LTSC 1809

**Comment by silversword411** [comment] 2022-02-08 17:44
> Is this a bug?

No, it's something specific to your computer. You have something installed (utility, graphics card drivers with an option etc) that is moving/centering/placing onscreen all new program windows to "make sure they're visible" (as in if a program tried to create a new window off-screen, it's moving that window on-screen)

**Comment by superuser7777** [comment] 2022-02-12 07:33
> No, it's something specific to your computer.
Thanks for the comment.
It took a while, but the problem was solved. When a monitor with a refresh rate of 59 Hz and 60 Hz is used at the same time, the 59 Hz monitor is magnified. 
I don't know if it is a problem with the graphics driver or the utility, but please refer to it:)

**Comment by silversword411** [comment] 2022-02-12 13:55
> Thanks for the comment. It took a while, but the problem was solved. When a monitor with a refresh rate of 59 Hz and 60 Hz is used at the same time, the 59 Hz monitor is magnified. 

I've never heard of refresh rate causing magnification...that's usually DPI settings. Interesting.

**Comment by Tur30** [comment] 2022-08-08 02:31
This is **caused by another program** on your device. You must close on by one program to figure out which **program interferes with ShareX**. I've opened up my system tray and started closing one by one app. In the end I realised it was software called **Window Centering Helper** which was giving me headaches.

**Closed** 2022-08-08 02:35 UTC
Labels: Invalid

**Comment by decrypt-ai** [comment] 2026-03-22 21:43
Fix: Uncheck "Restrict region capture and cursor within the active monitor"

If your second monitor's content is overlapping the first when you enter region capture, ShareX may be rendering the capture overlay on a single monitor instead of spanning the full virtual screen.

Path: Task Settings → Capture → Region Capture → scroll to the very bottom → uncheck "Restrict region capture and cursor within the active monitor"

Also check: If you use PowerToys FancyZones or similar window management tools, they can interfere with ShareX's fullscreen overlay — try disabling them temporarily to rule that out.

Detailed write-up with screenshot: https://github.com/ShareX/ShareX/issues/4862#issuecomment-4107032714

Verified on ShareX 19.0.2, Windows 11, dual monitors with same scaling.
