### ISSUE TITLE
Open ShareX Image Editor from Command Line

### ISSUE THREAD

**Issue by Ranger2000** [ShareX/ShareX#5427] opened 2021-02-24 15:09 UTC
The solution in the issue https://github.com/ShareX/ShareX/issues/5065 does not work

ShareX.exe -ImageEditor "filepath" does not do anything 😪

**Comment by Jaex** [comment] 2021-02-24 15:10
Duplicate of #5065

**Closed by Jaex** 2021-02-24 15:10 UTC
