### ISSUE TITLE
Update 12.1 removed ShareX editor

### ISSUE THREAD

**Issue by edmunek** [ShareX/ShareX#3223] opened 2018-03-23 10:08 UTC
Since recent updates, plenty of people were changing the "after screenshot" editor by disabling the "UseShareXForAnnotation". Yesterday an update 12.1 arrived and removed this functionality.
Why if the editor is for some people completely unusable, unlogical and just terrible?

https://github.com/ShareX/ShareX/issues/2621
https://github.com/ShareX/ShareX/issues/2436#issuecomment-294494879
https://github.com/ShareX/ShareX/issues/3220

At this particular moment I am thinking about no longer using ShareX as I am finding this product going in wrong direction

I am also using multiple monitors and using the ShareX editor is just a gigantic step back in ergonomy of using this tool.

**Comment by Jaex** [comment] 2018-03-23 10:09
Duplicate of #3220

**Closed by Jaex** 2018-03-23 10:09 UTC
