### ISSUE TITLE
add a general clipboard history viewer

### ISSUE THREAD

**Issue by megaBadger** [ShareX/ShareX#3255] opened 2018-03-27 21:05 UTC
Would love if ShareX tracked all clipboard entries, not just the images taken with greenshot but text or documents as well. Perhaps this could be a separate item under the tools menu? Or maybe this is outside of the scope y'all want ShareX to cover. 

I realize there are cool apps like Clipdiary and others, but it would be nice if ShareX could do it since it has replaced so many of my other applications.

**Comment by Jaex** [comment] 2018-04-06 08:02
Duplicate of #1331

**Closed by Jaex** 2018-04-06 08:02 UTC
