### ISSUE TITLE
Arithmetic operation resulted in an overflow

### ISSUE THREAD

**Issue by AncoFilms** [ShareX/ShareX#3766] opened 2018-11-18 04:46 UTC
System.OverflowException: Arithmetic operation resulted in an overflow.
   at ShareX.MainForm.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

ShareX 12.3 (Release)

**Comment by Whats-In-My-Vape** [comment] 2018-11-18 04:54
Oh I got that too, Uninstall and reinstall

**Comment by AncoFilms** [comment] 2018-11-18 04:57
so i had an old version and updated to 12.3, that broke everything so i did that(uninstall and reinstall) and just got the error. i can un/re again but it would be a repeat

**Comment by AncoFilms** [comment] 2018-11-18 04:58
it stopped my restart which is how i noticed it

**Comment by L1Q** [comment] 2018-11-18 05:04
Try reproducing your issue in a [dev build](https://getsharex.com/docs/dev-builds)

**Comment by AncoFilms** [comment] 2018-11-18 05:05
it just happened, idk how to make it happen, the log is a bunch of successful screenshots then that

**Comment by AncoFilms** [comment] 2018-11-18 05:06
2018-11-17 17:27:49.183 - Task completed. Filename: TABPC_2018-11-17_17-27-47.jpg, Duration: 1725 ms
2018-11-17 20:44:02.705 - Unhandled exception:
System.OverflowException: Arithmetic operation resulted in an overflow.
   at ShareX.MainForm.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

ShareX 12.3 (Release)
2018-11-17 20:44:14.784 - URL opened: https://github.com/ShareX/ShareX/issues?q=is%3Aissue

**Comment by L1Q** [comment] 2018-11-18 05:06
Does it happen right when you start ShareX?

**Comment by AncoFilms** [comment] 2018-11-18 05:07
no i didnt, mine launches at login so i was loging off after a day of gaming and the error stopped my restart/logoff

**Comment by AncoFilms** [comment] 2018-11-18 05:08
i guess the trigger would be my pc telling it to turn off/exit the program

**Comment by AncoFilms** [comment] 2018-11-18 05:08
when i hit logoff, but idk exactly

**Comment by L1Q** [comment] 2018-11-18 05:13
Please try reproducing this (e.g. starting ShareX and rebooting again) with your version and dev build. We need to know if this was fixed already.

**Comment by L1Q** [comment] 2018-11-18 05:15
It would also be very useful if you could provide information about your operating system.
What version of Windows are you running?
Your can learn this by pressing Win+R, entering ``winver`` into the field, and pressing enter.

**Comment by AncoFilms** [comment] 2018-11-18 05:20
I am on windows 1809 OS build 17763.134
4 restarts and 4~5 screenshots with sharex running everytime, and the error hasnt come back, i just installed dev build and will try 4 more restarts, it may be a problem with running without doing anything for a while cause it was 3~4 hours of no input to sharex then a restart but i dont know for sure cause im not a pro :D

**Comment by AncoFilms** [comment] 2018-11-18 05:25
*idk what u can see about the above comment cause for me it has a line through half of it*
after installing the dev build... 4 restarts with sharex running and 5 screenshots each and there is no error on restart

**Comment by Jaex** [comment] 2018-11-18 08:59
Duplicate of #3738

**Closed by Jaex** 2018-11-18 08:59 UTC
