### ISSUE TITLE
Illegal Characters in Path

### ISSUE THREAD

**Issue by FatassChink** [ShareX/ShareX#4114] opened 2019-05-07 14:42 UTC
Has been reported multiple times but all of them were closed so I thought I'd start a new one. Every time I click on 'Application Settings' or try to take a screenshot, it throws 'System.ArgumentException: Illegal characters in path' at me.

The error for trying to go into the 'Application Settings':
![ShareX-Error1](https://user-images.githubusercontent.com/50371587/57308256-ef840200-70dd-11e9-9515-f3e0be0fc3c0.png)

The error for trying to take a screenshot:
![ShareX-Error2](https://user-images.githubusercontent.com/50371587/57308277-f9a60080-70dd-11e9-99c4-d9f4b9aa68b9.png)

The current path it's set to save images to is 'C:\Users\SirLi\Desktop\杂物\Media\Obrazy\ShareX'. The issue started when I changed the folders name from '杂物' to 'Rodaí' while the program was open (changing the folder's name back to what it was before didn't fix it). I've changed that folder's name before without the program breaking so I don't think it's a 100% certainty to happen.

**Comment by FatassChink** [comment] 2019-05-07 15:03
I managed to get the program to work properly again by uninstalling the program, moving the 'ShareX' folder from 'My Documents' to my desktop, then reinstalling the program.

**Comment by Jaex** [comment] 2019-05-08 11:16
I check "Use custom screenshot folder" checkbox and input "'C:\Users\username\Desktop\杂物\Media\Obrazy\ShareX" for textbox under it. Then I close application settings window and reopen it. There is no error show up.

Then I took screenshot and even there is no such folder in desktop still ShareX created all folders automatically and saved screenshot to there.

So I'm unable to reproduce your issue.

**Comment by Jaex** [comment] 2019-05-08 11:21
Now I noticed adding `"` character to path gives this error. Is it possible your path had such character?

**Comment by Jaex** [comment] 2019-05-08 11:24
Duplicate of #2359

**Closed** 2019-05-08 11:25 UTC
Labels: Duplicate
