### ISSUE TITLE
ScreenShots being cutoff/Corrupted with FTP Uploads

### ISSUE THREAD

**Issue by Roxashe** [ShareX/ShareX#3235] opened 2018-03-25 09:18 UTC
As per the subject, all screenshots I'm uploading seem to be getting corrupt when uploading. Its the exact same issue as Issue#1929 and only started with ShareX V12.1

**Comment by Jaex** [comment] 2018-03-25 09:19
Duplicate of #3224

**Comment by Torubloo** [comment] 2018-03-25 09:19
https://github.com/ShareX/ShareX/issues/3224

**Closed by Jaex** 2018-03-25 09:19 UTC
Labels: Duplicate
