### ISSUE TITLE
Imgur login 400 bad request.

### ISSUE THREAD

**Issue by c933103** [ShareX/ShareX#3030] opened 2017-12-29 15:24 UTC
I tried to authorize my imgur account but it say failed, so I try to manually reauthorize it, and then I get directed to [https://api.imgur.com/oauth2/authorize?client_id=(a alphanumeric string)&response_type=pin] and then I get 400 bad request as a result

**Comment by Jaex** [comment] 2017-12-29 15:26
Duplicate of #3027

**Closed** 2017-12-29 15:26 UTC
Labels: Duplicate

**Comment by c933103** [comment] 2017-12-29 15:49
3027 is upload, this is login, although it is the same error 400 and likely imgur's problem
