### ISSUE TITLE
[Video Thumbnailer] Thumbnails generated are the same frame over and over

### ISSUE THREAD

**Issue by iiiGerardoiii** [ShareX/ShareX#4860] opened 2020-06-07 01:09 UTC
The thumbnailer works but incorrectly and I don't know why. If I make it 9 frames it will generate the same thumbnail 9 times. It also gives the duration and bitrate wrong.

What could that be?

A few examples:

![rick and morty s04e10 1080p webrip x264-btx_Thumbnail](https://user-images.githubusercontent.com/6264194/83957603-c547cb00-a82e-11ea-9f01-b5f8ba3ea77e.jpg)

![The smallest roar-quh1adjxapd31_Thumbnail](https://user-images.githubusercontent.com/6264194/83957911-89623500-a831-11ea-8fd9-df0e07b8ea83.jpg)

I'm using ShareX 13.1 on Windows 10

**Comment by Jaex** [comment] 2020-06-07 01:12
Duplicate of #4705

**Closed by Jaex** 2020-06-07 01:12 UTC

**Comment by iiiGerardoiii** [comment] 2020-06-08 15:03
Oh, I saw that other issue but thought it was a different thing since it was all black images, but now I realize that their videos started in black.

Apologies for the duplicate my friend.
