### ISSUE TITLE
OneDrive for Business Authentication

### ISSUE THREAD

**Issue by MrAmos123** [ShareX/ShareX#3159] opened 2018-02-21 09:17 UTC
I'm trying to add my business OneDrive account, but I can't as the Auth page in ShareX redirects to login.live which doesn't work with Business accounts. 

I tried building the URL myself using:
https://docs.microsoft.com/en-us/onedrive/developer/rest-api/getting-started/graph-oauth

But doesn't seem to work: 
https://login.microsoftonline.com/common/oauth2/v2.0/authorize?client_id=000000004013BA0E&scope=wl.basic+onedrive.readwrite&response_type=access_token&redirect_uri=https%3a%2f%2fgetsharex.com%2fcallback%2f

If anyone knows where I messed up that'd be appreciated, plus can we get native OneDrive Business Support

**Comment by Jaex** [comment] 2018-02-25 07:24
Duplicate of #1853

**Closed by Jaex** 2018-02-25 07:24 UTC
