### ISSUE TITLE
Right-click tray icon on v13.6.1 throws exception

### ISSUE THREAD

**Issue by KeyserS0ze** [ShareX/ShareX#5820] opened 2021-09-13 23:00 UTC
Updated from v13.5.0 to v13.6.1. The updated executable launches nicely, and everything seems to work fine from the startup window. Upon closing the window, and attempting to open the tray icon context menu, this exception is thrown:

```c#
System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at System.Windows.Forms.ToolStripItemCollection.CheckCanAddOrInsertItem(ToolStripItem value)
   at System.Windows.Forms.ToolStripItemCollection.Add(ToolStripItem value)
   at System.Windows.Forms.ToolStripItemCollection.AddRange(ToolStripItem[] toolStripItems)
   at ShareX.MainForm.<PrepareCaptureMenuAsync>d__52.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ShareX.MainForm.<tsmiCapture_DropDownOpening>d__149.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

ShareX 13.6.1 Portable
```

This also happens with version 13.6.0.

Downgrading to v13.5.0, no exceptions are ever thrown. It behaves as it has always been.

Weirdly, this fault could not be reproduced on a brand new virtual machine.

**Comment by Jaex** [comment] 2021-09-14 23:31
I couldn't reproduce your issue therefore I'm unable to verify the fix. But it should be fixed most likely.

**Closed** 2021-09-14 23:30 UTC
Labels: Bug
